### ISSUE TITLE
Infernal Mobs - console spam

### ISSUE THREAD

**Issue by canilsen** [AtomicStryker/atomicstrykers-minecraft-mods#10]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/abebfeb9883e0dd046100cbc8c04ccdf2b9c5273/InfernalMobs/src/main/java/atomicstryker/infernalmobs/common/MobModifier.java#L142

Would it be possible to add a config to toggle this system message off? I changed some attributes for infernal mobs in our world, and I can't find a way to get the console spam to stop. It doesn't seem to affect the server either, so simply turning it off would be allright.

**Comment by canilsen** [comment]
As a solution for myself, I edited out that elseif, and remade jar. But I would like to see the option to turn it off, as a debug config perhaps.

**Comment by AtomicStryker** [comment]
Does never happen (or should not) unless you load an existing save with a differing modifier set. If you insist on doing something like this, i would suggest killing all entities on the server. Although i do see the issue - Infernal Mobs will keep logging this and not "fix" the error.

**Comment by Wulfson** [comment]
The code change in 44445010f1d01f3c74cc142d0910dff9eeaf22ad seems to have made it so the console spam now ends up being "Was [], now trying to set [{modifiers}]"
Seems like the check at https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/master/InfernalMobs/src/main/java/atomicstryker/infernalmobs/common/MobModifier.java#L136 should check for an empty string as well, and skip logging in that case.

**Comment by AtomicStryker** [comment]
Aye. But i already fixed this https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/c08c265a40e0a1e44f712005f35b12159df72254

**Comment by AtomicStryker** [comment]
And since i could already anticipate the next request the same hotfix was pushed to the 1710 version branch

**Comment by Wulfson** [comment]
Awesome, thanks!

**Comment by demycat** [comment]
Hello, I understand that you may not update older versions, but I wanted to share a similar issue with version 1.7.10, where I disabled one tag and my console is now flooded with spam.

<img width="977" height="152" alt="Image" src="https://github.com/user-attachments/assets/a7692494-3a82-4140-9630-a9bb8c6e42b3" />

**Comment by AtomicStryker** [comment]
See third comment. Your mobs are now tagged with modifiers which the mod can longer recreate. Kill them off or reset their nbt data.

**Comment by demycat** [comment]
> See third comment. Your mobs are now tagged with modifiers which the mod can longer recreate. Kill them off or reset their nbt data.

I was following the advice from the third comment, but I don't know any commands to kill all mobs or how to delete mob nbt data.
I tried doing the following:
1. Switched to peaceful mode.
2. Flew around the places I visit most often.
3. Turned hard mode back on.

But that didn't help, because after about 5-10 minutes, these messages appeared and continue to spam, which is why I wrote to you to get additional help.

**Comment by AtomicStryker** [comment]
If you dont have server admin tools to do things like kill all entities, or the knowledge to edit the savefile, the easiest thing would be honestly to start a new world savefile on the server.

If you dont want to do that, you can look into minecraft save/nbt editors, i see there is even online versions. You need to go through all entities that have nbt value with "Sticky" and remove it. There might be hundreds or thousands.
