### ISSUE TITLE
[1.11.2]  Cascading worldgen lag warning

### ISSUE THREAD

**Issue by Geethebluesky** [AtomicStryker/atomicstrykers-minecraft-mods#100]
Hello,

I'm getting this message while loading a Forge 2284 server:

[Server thread/WARN] [FML]: Ruins Mod loaded a new chunk (2, 2  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Just doing what's suggested. :)

**Comment by AtomicStryker** [comment]
I am aware that Ruins may cause cascading worldgen and lag. Since that's literally what it does i am unconcerned.
