### ISSUE TITLE
[Battle Towers] Reload loot tables command

### ISSUE THREAD

**Issue by Revvilo** [AtomicStryker/atomicstrykers-minecraft-mods#101]
Would it be at all possible to add some sort of reload loot tables command as a kind of quality of life tweak?
Right now it gets quite tedious having to restart a large modpack over and over to test the loot tables and such.

**Comment by AtomicStryker** [comment]
Possible, yes, but i am very busy and if i do find some spare time i shall invest it in Factorio.

**Comment by Revvilo** [comment]
Ah, no worries, whatever floats your boat my dude.
