### ISSUE TITLE
Lag spikes from MM_Ender.teleportTo

### ISSUE THREAD

**Issue by Player3324** [AtomicStryker/atomicstrykers-minecraft-mods#102]
I've observed the method in the subject spending over 17 seconds in teleportTo within a single tick. There's no recursion involved, the version is 1.10.

Looking at the code I think the following loop underflows y, it certainly doesn't handle negative y:

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.11/InfernalMobs/src/main/java/atomicstryker/infernalmobs/common/mods/MM_Ender.java#L84

**Comment by AtomicStryker** [comment]
No it does not. Though to be fair, this would only happen if there are holes into the void in the world, as in any other case there would be movement blocking blocks atleast one layer deep at some y over 0.

I'm pretty sure i copied the vanilla Enderman teleport code at that point in time.

**Comment by Player3324** [comment]
Don't ask me why they get below y=0 or it doesn't hit a solid block, I just don't see any other cause for the excess getMaterial calls that most certainly go to Blocks.AIR via the y bounds check. Vanilla currently checks y > 0, not y < 96.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/b7d231a772ff69dee52f8005d13defa0fca7ac89
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/7f027e8a1eae3572ab053c94c2627660f7666245
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/e59cb988ea5df090d66aa84a65b246f6f81a5954
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/83b24a40b4424e8483ede69eee889fcb7d20c0f4
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/aa60058532448fb937e3ce0305bd68877ae75c1c
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/d3641fbeeb2bb46f09b67b17950910c58ff0b937

WHY IS THERE SO MANY VERSIONS
