### ISSUE TITLE
[Infernal Mobs][1.10][MC1.10.2] Passive Mobs throw hostile potions

### ISSUE THREAD

**Issue by Aedda** [AtomicStryker/atomicstrykers-minecraft-mods#104]
This may be intentional but it seems counter-intuitive. I've encountered non-hostile passive Zombie Pigman in the Nether who is an Alchemist and if I get even remotely close to it it begins tossing potions at me.

Their full description is:
Rare witchkin PigZombie the Undying
1UP Fiery Berserk Alchemist

**Comment by AtomicStryker** [comment]
That's "sort of" a vanilla bug. What is happening is that minecraft rapidly has the Zombie Pigman target you, then drop the target as he is not "hostile" yet. But targeting you triggers Infernal Mods.

**Comment by Aedda** [comment]
Interesting! As I normally never attack the things anyway I'll just mark them as non-infernal and that should fix the issue in my case. 😃

**Comment by AtomicStryker** [comment]
I can't think of a good solution that wouldn't be coded specifically for Pigmen (and Endermen, maybe?). Just adding them to the exclusion list is easiest for everyone.
