### ISSUE TITLE
[Battle Towers] Tower collapse getting stuck in infinite loop

### ISSUE THREAD

**Issue by Revvilo** [AtomicStryker/atomicstrykers-minecraft-mods#106]
Whilst fighting the Tower Golem, sometimes he will _quite convieniently_ vanish into the ground and fall all the way out of the world. this comes at a price, though, he will eventually (I presume) die and cause the tower to collapse, but 30ish seconds later he will die again... and again... and again, Infinitely. Obviously causing severe lag due to the multiple explosions going off at once.
It is only solved by restarting the server/world or reloading the chunks that the tower is in.
This problem renders the mod very difficult to use because he falls out of the map quite frequently.

**Comment by AtomicStryker** [comment]
I am aware of the problem, though the golem becoming a schroedingers explosion cause is a new detail. Which versions (MC, BT) are we talking about.

**Comment by Revvilo** [comment]
MC is 1.10.2
And BT is just 1.10.2? I don't see anywhere, whether it be the MCMod.info or Curseforge, that the mod version is shown...
It did seem to start happening when I updated a lot of mods in my pack, but the pack was undergoing a lot of development so I didn't think much of it.
Unfortunately, the game output/log doesn't provide anything either besides the repetition of the collapse message.
PS: Sorry about that, I clicked the wrong button.

**Comment by AtomicStryker** [comment]
OK I've had another look at the code and i may have figured out the problem. https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/1923a9afc838b492091f7f64590b10a2eb5aed39

The version can be figured out by looking at the changelog file in the jar or the ingame mods menu.

Try the latest build: https://github.com/AtomicStryker/github.io/blob/master/files/1.10.2/BattleTowers-1.10.2.jar

**Comment by Revvilo** [comment]
Thanks, man, looks promising so far!
Will keep you posted if anything arises.
