### ISSUE TITLE
Suggestion for a Roguelike potion: Purgative

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#107]
This potion would inflict 1 second apiece of Poison III, Blindness II, Wither II, Hunger III, Nausea II, and so on for all the negative statuses (except Harming), matching or incrementing the highest level they're likely to encounter in the RLD.  The point is to trump any existing statuses and replace their durations, in one brief and painful stroke.  

If you're feeling nice, you could add a level or two of Healing (to help keep the potion from killing an already injured character), and perhaps a few seconds of Regeneration I or II, for recovery afterwards.  (I wouldn't bother restoring their saturation. ;-) ).

**Comment by AtomicStryker** [comment]
But unless my memory is worse than usual, i don't have any mods that add potions to the game? Why come to me of all people with this?

**Comment by MentalMouse** [comment]
Whoops, for some reason I thought Roguelike Dungeons was yours.  Never mind...
