### ISSUE TITLE
Wrong display in TheOneProbe

### ISSUE THREAD

**Issue by AndreiTS** [AtomicStryker/atomicstrykers-minecraft-mods#108]
1.11.2

![2017-05-24_13 44 13](https://cloud.githubusercontent.com/assets/13489837/26415851/44ecd39c-408a-11e7-91ed-1e407af3b921.png)

**Comment by AtomicStryker** [comment]
Uhhh ask the "One Probe" developers? I don't know what it is their mod is querying

**Comment by AndreiTS** [comment]
https://github.com/McJty/TheOneProbe/issues/165
![sem titulo](https://cloud.githubusercontent.com/assets/13489837/26499797/3df4da72-420a-11e7-85df-94ced97a6685.png)

**Comment by AtomicStryker** [comment]
Yeah so this is something i need to fix. MC changed what is right ... surely they must be wrong 🐙

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/2f4aa69d47fdafeed2033c5e4c38205ff7abe2b1

Pushes to the repositores are out. Redownload for fixed version. Compatible with existing servers and everything.

And thank you for bringing it to attention
