### ISSUE TITLE
[Ruins] suggestions regarding config and packing

### ISSUE THREAD

**Issue by TheTrueForce** [AtomicStryker/atomicstrykers-minecraft-mods#115]
I have noticed a couple of gotchas with Ruins, both to do with how mods generally work these days. I think both will require some amount of rewriting though.

One is that the download on Curse is not the mod itself, which is a problem because the Twitch App, which used to be Curse Voice, and includes a very convenient way to build a modpack from Curse-hosted mods, just downloads it and dumps it in the mods folder. Could this be changed to have the downloaded file be the mod jar. please?
I know there is a way to store a default config file in a mod jar and have it get extracted if the one in the config folder is absent; maybe something similar could be done for the resources folder and docs.

The other is that the config file is in the mods folder. Most Forge mods these days put their config files in the config folder, and as a result I didn't think to look further, and only found it because I stumbled across it and thought "what's this?" and opened it. Could this be fixed, please?

**Comment by AtomicStryker** [comment]
While curse might just force me to do this anyway (there have been signs), packing the "default" template set into the mod jar itself isn't how i want to do it. So, brutally short: I could, i don't want to, i might have to anyway.

Technically the config in the mods folder is merely a template, the actual config will be found in each world save folder (so you can configure each ...). They are copied from the mods one, though.

**Comment by TheTrueForce** [comment]
Another way I just thought of is: You could have the mod download them from this repo, if they're on here (I didn't check).
But anyway, Thanks for the reply. That's interesting with the config though... Certainly unusual that it's not global. If you document it more/more visibly, it may reduce the confusion for newer users. I know that documenting something is not the easiest thing in the world. Commenting code is a bit of a chore at times; I imagine that building a doc for a whole mod from the ground up is much worse.

**Comment by AtomicStryker** [comment]
Ruins comes as jar now. Happyness all around! Wee
