### ISSUE TITLE
Multimine open,close,write its config repeatedly

### ISSUE THREAD

**Issue by leagris** [AtomicStryker/atomicstrykers-minecraft-mods#116]
This is very inefficient
Takes tick time
Force system to flush data to disk.
Is wearing SSD drives.
Only Multimine does this

And here it does this with a 200k config every few seconds.

**Comment by AtomicStryker** [comment]
What you are probably experiencing is Multi Mine writing each block and item to the config banlist as they are encountered (however, each only once ...). After a block or item was loaded from the config (and saved if not previously in there) once, they are cached in memory.

I don't recall why i chose this approach and with stupidly large modpacks and mountains of mod objects it might be an issue. That being said, if a 200k config file being written over and over will take a couple hundred years to kill your SSD. Complain to me then.

**Comment by AtomicStryker** [comment]
Well i vaguely remember people complaining about not being able to add mod items to the banlists correctly, that may have been the origin

**Comment by leagris** [comment]
just ok

**Comment by ThaDaVos** [comment]
Please change the implementation it causes a lot of TPS lag... see this issue: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/291
