### ISSUE TITLE
Dynamic Lighting in forge 1.12 - 14.21.0.2327

### ISSUE THREAD

**Issue by sebasjham** [AtomicStryker/atomicstrykers-minecraft-mods#117]
I tried cloning the dynamic lighting mod to run in forge version 14.21.0.2327 MDK.  Is it likely to work in 1.12, for I have not been able to do it?

**Comment by AtomicStryker** [comment]
It works, i already tested it on actual MC. If you are trying to run the eclipse client, bear in mind you have to add the Dynamic Lights project to the run configuration, and also, you have to add the Dynamic Lights jar to the /mods/ folder of the runtime (make sure to delete everything except META-INF inside it) or the coremod part won't trigger.
