### ISSUE TITLE
Glitchy Lighting while walking vs 1.12

### ISSUE THREAD

**Issue by kissi1337** [AtomicStryker/atomicstrykers-minecraft-mods#119]
Dynamic Lights Mod.

While walking I have noticed that the lighting updates are not fluid at all. They are very glitchy and flicker.

https://i.gyazo.com/0a30ecf29ab2d62922d85a9f675971f6.png
Version and showing it alone in the testing with latest Forge release.

https://i.gyazo.com/ef2bcc71def42c77d5a43873dcd9dcb0.gif
GIF of what is happening. FPS is showing a steady 47-50, but it does drop due to the flickering of the light. Steady at 60fps when not in motion. (Beginning of GIF)

If you need more information I'll gladly do what I can to offer it. Thank you.

**Comment by AtomicStryker** [comment]
There's always a chance "optimizations" by the MC devs finally break Dynamic Lights completely. I will check it out, maybe, eventually.

**Comment by AtomicStryker** [comment]
1.12 and 1.12.1 seem to halt the rendering while any light update is happening, which results in this choppiness. There is nothing i can do about it, as Dynamic Lights merely tricks the engine, and doesn't replace it (such as Optifine does, for example). Try Optifine, if it still offers Dynamic Lights compatibility.
