### ISSUE TITLE
Localize Dynamic Lights and Update Checker

### ISSUE THREAD

**Issue by Adaptivity** [AtomicStryker/atomicstrykers-minecraft-mods#12]
These strings should be localizable:
[Update Check](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/master/UpdateCheckerMod/src/main/java/atomicstryker/updatecheck/common/UpdateCheckMod.java#L81-L83), [Dynamic Lights control](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/abebfeb9883e0dd046100cbc8c04ccdf2b9c5273/DynamicLights/src/main/java/atomicstryker/dynamiclights/client/DynamicLights.java#L92) and [Dynamic Lights Messages](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/abebfeb9883e0dd046100cbc8c04ccdf2b9c5273/DynamicLights/src/main/java/atomicstryker/dynamiclights/client/DynamicLights.java#L123) (ChatComponentTranslation should be used there)

Also, some other your mods uses *ChatComponentText* it should be replaced with *ChatComponentTranslation*, StatCollector with ChatComponentText will not work server side. (Messages will always be in English, as server always uses English localization)

**Comment by AtomicStryker** [comment]
Not enough of a priority to overcome my lazyness. If you put in pull requests i'll merge them, but its unlikely i fix this of my own motivation.
