### ISSUE TITLE
Gets stuck on load - Ruins - 1.12

### ISSUE THREAD

**Issue by teamaonn** [AtomicStryker/atomicstrykers-minecraft-mods#123]
See attached report.
[Log 6-30.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1116359/Log.6-30.txt)

**Comment by AtomicStryker** [comment]
Field access error, Forge is messing around. It worked for the Forge it was built with (2321)
I will check out the problem

**Comment by teamaonn** [comment]
I understand, I'm using 2387 if it helps

**Comment by AtomicStryker** [comment]
I've updated all my mods to 2387 and pushed them to curse. You should be able to get them soonish.

**Comment by teamaonn** [comment]
issue persists
