### ISSUE TITLE
New World Generation Gets stuck - Ruins - 1.12

### ISSUE THREAD

**Issue by teamaonn** [AtomicStryker/atomicstrykers-minecraft-mods#124]
See attached log. (PS, Love your plugins)
[Log 2 6-30.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1116371/Log.2.6-30.txt)

**Comment by teamaonn** [comment]
[Log 3 6-30.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1116539/Log.3.6-30.txt)
Another attempt

**Comment by AtomicStryker** [comment]
Please don't open several issues about the same problem
