### ISSUE TITLE
Still getting stuck on load - Ruins - 1.12

### ISSUE THREAD

**Issue by teamaonn** [AtomicStryker/atomicstrykers-minecraft-mods#125]
Updated to your newest curse version. Attached document.
[Log 3 6-30.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1116583/Log.3.6-30.txt)

**Comment by AtomicStryker** [comment]
Curse rejected the file because they finally enforce "jar only". Grab it from my website http://atomicstryker.net/ruins.php
