### ISSUE TITLE
Ruins Freezes on World Generation on Dedicated Server and Battle Towers Crashes on World Generation on Dedicated Server (1.12)

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#126]
title tells everything, plz fix. using forge 2395. 1.12.
ruins mod causes dedicated server freeze on world generation.
battle towers crashes on world generation, dedicated server. 
[crash-2017-07-04_21.21.23-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1122815/crash-2017-07-04_21.21.23-server.txt)

**Comment by AtomicStryker** [comment]
Forge changed their API again. Stay on the last working version, i will not keep up with Forge versions, i will wait until they stop breaking things and update then.

**Comment by ghost** [comment]
it only happens on dedicated server, it works on client side fine.
ruins and BT did never work on dedicated server (any forge version)
here is a crash report that with forge 2387.
[crash-2017-07-05_00.49.11-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1123110/crash-2017-07-05_00.49.11-server.txt)

**Comment by kenijey** [comment]
HEY REOPEN THIS

**Comment by AtomicStryker** [comment]
Please don't allcap at me, it's rude. I fixed the biome name issues.

**Comment by ghost** [comment]
yess it works now, thank you :D
