### ISSUE TITLE
MC 1.11.2 - Compatibility Issue with Voidcraft

### ISSUE THREAD

**Issue by blackviperr** [AtomicStryker/atomicstrykers-minecraft-mods#128]
Can no longer fly properly with voidcraft installed, only allows me to fly-jump where I fly for like 0.3 seconds and land on the ground again. (like spacemen on the moon lol) Have also contacted author of voidcraft.

**Comment by Tamaized** [comment]
On a side note, my checks work the same as Botania's where I only turn on or off when needed.
https://github.com/Tamaized/VoidCraft/blob/1.12/src/main/java/tamaized/voidcraft/common/events/XiaFlightHandler.java#L23-L37
