### ISSUE TITLE
[Dynamic Lights] Disabling modules without modifying the .jar

### ISSUE THREAD

**Issue by pennywis3** [AtomicStryker/atomicstrykers-minecraft-mods#13]
Modpacks hosted on Curse cannot redistribute mods, and will instead directly download a version from CurseForge. This means modpack authors cannot disable single modules from Dynamic Lights for a public (Curse hosted) modpack.
It would be very much appreciated if you could find a different way to make that work.

**Comment by AtomicStryker** [comment]
I am pretty sure fml/forge allows you to disable mods by configuration

**Comment by pennywis3** [comment]
Learn something new every day. I knew about the "Disable" button in the "Mods" menu, but I think that just fires an event that nobody ever listens to. After googling and looking through some FML code, I then discovered that one can indeed create a "fmlModState.properties" file in the config folder and specify something along those lines:
```
DynamicLights_entityClasses=false
DynamicLights_dropItems=false
```
It's there, but I don't think it's very well known.

**Comment by AtomicStryker** [comment]
I somewhat knew, so its known enough :D
