### ISSUE TITLE
[1.12] Battle Towers - Crash

### ISSUE THREAD

**Issue by MokahTGS** [AtomicStryker/atomicstrykers-minecraft-mods#132]
Getting a random crash from Battle Towers:

https://pastebin.com/tB94EKFz

**Comment by AtomicStryker** [comment]
Welp i did a copypasta there, but the gist is visible? "because it was denied file write access to C:\Minecraft\Instances\Dev-1.12\saves\Test 2\DIM-2\BattletowerPositionsFile.txt"

**Comment by AtomicStryker** [comment]
Someone in minecraftforums had the same issue and suggested a RAM upgrade fixed it for him. Generally speaking, this is "Hardware/OS something something" and not directly related to my mods.
