### ISSUE TITLE
Suggestion: A way to specify what dimension(s) Battle Towers can spawn in

### ISSUE THREAD

**Issue by Winddbourne** [AtomicStryker/atomicstrykers-minecraft-mods#133]
It would be really nice to be able to specify which dimension(s)  Battle Towers can spawn in. 

I was fooling around with a mod pack idea and I had roguelike dungeons spawning only in the nether and I was going to place the battle towers in a dimension from Cavern mod called "Huge Cavern" which has a lot of open space . . . give people some variety in what they could find without having all the different dungeon types generating in the same place or (at all) in the "main" Overworld dimension. 

It causes a lot less overall lag spiking if I split up the more intensify world generation options to different dimensions, biomes, etc. . . .

**Comment by AtomicStryker** [comment]
Have you looked at your battletowers.cfg? There is both the option to restrict by Biome and by Chunk Provider (which is a more accurate way of saying dimension)

**Comment by Winddbourne** [comment]
Thank you I did look but I must have missed it, or more likely didn't
realize what was meant by chunk provider. Thank you!

**Comment by Winddbourne** [comment]
I just reinstalled Battle Towers and did a search in word for both Chunk
Provider and Restricted and it simply isn't there. I was hoping I just was
being a ditz; as that can happen. lol

Anyway I'm sending you a copy of the BattleTowers.cfg file that was
generated. Perhaps you can find it, or if it isn't there make a quick
update to fix the problem.

**Comment by AtomicStryker** [comment]
Next thing you're going to tell me you are playing on the ancient 1710 version

**Comment by Winddbourne** [comment]
Of course not. I'm using 1.12 . . . there isn't a lot of content out for it
yet; but I'm taking the opportunity to make a very focused performance pack
with a bit of added exploration thrown in for fun.

**Comment by AtomicStryker** [comment]
The biomes and providers probably only show up AFTER they were encountered the first time - have you generated worlds yet?

**Comment by Winddbourne** [comment]
I have generated worlds, though I'm not sure if I generated them with the
battle towers installed. I tend to look at my config options before I spend
a lot of time with a mod. I'll do a test install and run really quickly and
see if that is the issue. I'm going to cross my fingers and hope that is
the problem.

**Comment by Winddbourne** [comment]
Ok, that is at least part of the problem. I got my it to show chunk
providers, and it has chunkproviderserver allowed. I also went into
caveland but that hasn't shown up. Which could be a problem with the other
mod.

**Comment by Winddbourne** [comment]
Eeek the typos. I got it to show chunk providers.
