### ISSUE TITLE
Neutral mobs attack anyway

### ISSUE THREAD

**Issue by lendrick** [AtomicStryker/atomicstrykers-minecraft-mods#134]
When I go to the nether, I get attacked by neutral zombie pigmen.  I feel like it would make more sense if neutral mobs didn't attack unless they were aggroed.  If this is an intended feature, a config option to turn it off would be nice.

Note that turning this off just for zombie pigmen isn't a great solution, because you would lose out on the added risk that you get if you aggro them.

**Comment by lendrick** [comment]
Quick note:  This is in the 1.10 verison.

**Comment by AtomicStryker** [comment]
That's a quirk of the minecraft engine, or rather, how Pigmen are implemented. The AI is constantly "targeting" the player (which Infernal Mobs reacts to) but a flag inside the entity update itself aborts the attack every tick unless the player has aggroed them.

I can think of solutions - such as making sure an entity was "targeting" a player uninterrupted for several ticks before triggering mods - but it's a bit of a pain to do this to fix what is essentially an engine error.

I suggest to just add pigmen to the Infernal Mobs blacklist.

**Comment by ghost** [comment]
Would an option to make pigman always hostile be possible?

**Comment by AtomicStryker** [comment]
That's not in the scope of my mod, but i wouldn't be surprised if there is a mod out there doing exactly this.
