### ISSUE TITLE
battletowers 1.11.2 - ChestGenHook is borked

### ISSUE THREAD

**Issue by XombyCraft** [AtomicStryker/atomicstrykers-minecraft-mods#137]
`battletowerchestitems {
    S:"Floor 1"=stick-0-75-5-6;wheat_seeds-0-75-3-5;planks-0-75-5-6;reeds-0-75-3-5
    S:"Floor 2"=stone_pickaxe-0-50-1-1;stone_axe-0-50-1-1;torch-0-80-3-3;stone_button-0-50-2-2
    S:"Floor 3"=bowl-0-75-2-4;coal-0-90-4-4;string-0-80-5-5;wool-0-75-2-2
    S:"Floor 4"=glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2
    S:"Floor 5"=brown_mushroom-0-75-2-2;red_mushroom-0-75-2-2;sapling-0-90-3-3;wheat-0-75-4-4
    S:"Floor 6"=sign-0-50-1-2;fishing_rod-0-75-1-1;pumpkin_seeds-0-60-2-2;melon_seeds-0-60-3-3
    S:"Floor 7"=iron_sword-0-60-1-1;gunpowder-0-75-3-3;leather-0-75-4-4;fish-0-75-3-3;dye-0-60-1-2
    S:"Floor 8"=chainmail_helmet-0-40-1-1;chainmail_chestplate-0-40-1-1;chainmail_leggings-0-40-1-1;chainmail_boots-0-40-1-1;ChestGenHook:dungeonChest:3
    S:"Floor 9"=bookshelf-0-70-1-3;redstone_lamp-0-60-2-2;waterlily-0-75-3-3;brewing_stand-0-50-1-1;ChestGenHook:dungeonChest:5
    S:"Item Generations per Floor"=7
    S:"Top Floor"=ender_pearl-0-50-2-20;diamond-0-100-2-20;redstone-0-75-5-64;gold_ingot-0-90-8-16;ChestGenHook:dungeonChest:7
}`
from the config file.

ChestGenHook returns zero items.  If I strip out the manually entered items and just leave the ChestGenHook bits, all chests in tower are empty.

**Comment by AtomicStryker** [comment]
There is nothing wrong with the ChestGenHook, however the correct resource for dungeon chests is not "dungeonChest" but "chests/simple_dungeon" in 1.12

EDIT:
I had forgotten the default rules actually contain 3 of these. I will change the default to the correct string, thanks for pointing it out.

**Comment by XombyCraft** [comment]
so I should change
`ChestGenHook:dungeonChest:7` 

in the config file to
`ChestGenHook:chests/simple_dungeon:7`
?

As I mentioned, I'm running this on 1.11.2 using the version you posted on CF on Jun 15

edit: these dont work:
ChestGenHook:dungeonChest:7
ChestGenHook:chests/simple_dungeon:7
ChestGenHook:simple_dungeon:7

**Comment by AtomicStryker** [comment]
ChestGenHook:chests/simple_dungeon:7
That's the correct one. And yes it works.
A full list of 1.11+ resources here: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.12/Ruins/src/main/resources/ruins_config/chestgen_locations_1.11.txt

I just looked at the ChestGenHook result in my debugger and the result was definitely not empty:

1xitem.saddle@0, 3xitem.wheat@0, 3xitem.beetroot_seeds@0, 8xitem.rottenFlesh@0, 4xitem.sulphur@0, 5xitem.sulphur@0

If you are not getting items, you are doing something else wrong.

**Comment by XombyCraft** [comment]
ok so... just to verify, I deleted the config file so it would regen.
then modified as below:

battletowerchestitems {
    S:"Floor 1"=stick-0-75-5-6;wheat_seeds-0-75-3-5;planks-0-75-5-6;reeds-0-75-3-5
    S:"Floor 2"=stone_pickaxe-0-50-1-1;stone_axe-0-50-1-1;torch-0-80-3-3;stone_button-0-50-2-2
    S:"Floor 3"=bowl-0-75-2-4;coal-0-90-4-4;string-0-80-5-5;wool-0-75-2-2
    S:"Floor 4"=glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2
    S:"Floor 5"=brown_mushroom-0-75-2-2;red_mushroom-0-75-2-2;sapling-0-90-3-3;wheat-0-75-4-4
    S:"Floor 6"=sign-0-50-1-2;fishing_rod-0-75-1-1;pumpkin_seeds-0-60-2-2;melon_seeds-0-60-3-3
    S:"Floor 7"=iron_sword-0-60-1-1;gunpowder-0-75-3-3;leather-0-75-4-4;fish-0-75-3-3;dye-0-60-1-2
    S:"Floor 8"=chainmail_helmet-0-40-1-1;chainmail_chestplate-0-40-1-1;chainmail_leggings-0-40-1-1;chainmail_boots-0-40-1-1;ChestGenHook:chests/simple_dungeon:3
    S:"Floor 9"=bookshelf-0-70-1-3;redstone_lamp-0-60-2-2;waterlily-0-75-3-3;brewing_stand-0-50-1-1;ChestGenHook:chests/simple_dungeon:5
    S:"Item Generations per Floor"=7
    S:"Top Floor"=ender_pearl-0-50-2-2;diamond-0-70-2-2;redstone-0-75-5-5;gold_ingot-0-90-8-8;ChestGenHook:chests/simple_dungeon:7
}

and... dungeon loot still doesn't show up. just the explicitly defined stuff.  So, either I'm missing something simple here, or what your debugger says and what actually shows up are two different things.  OR, there's a bug somewhere in the 1.11.2 version.

PS: is the fact that the default config lines are hard-coded in the SRC a contributing factor, possibly?

**Comment by XombyCraft** [comment]
OK, just to rule out mod conflicts, I set up a new forge install with JUST battle towers.  again, 1.11.2.
Edited the config like so:
battletowerchestitems {
    S:"Floor 1"=stick-0-75-5-6;wheat_seeds-0-75-3-5;planks-0-75-5-6;reeds-0-75-3-5
    S:"Floor 2"=stone_pickaxe-0-50-1-1;stone_axe-0-50-1-1;torch-0-80-3-3;stone_button-0-50-2-2
    S:"Floor 3"=bowl-0-75-2-4;coal-0-90-4-4;string-0-80-5-5;wool-0-75-2-2
    S:"Floor 4"=glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2
    S:"Floor 5"=brown_mushroom-0-75-2-2;red_mushroom-0-75-2-2;sapling-0-90-3-3;wheat-0-75-4-4
    S:"Floor 6"=sign-0-50-1-2;fishing_rod-0-75-1-1;pumpkin_seeds-0-60-2-2;melon_seeds-0-60-3-3
    S:"Floor 7"=iron_sword-0-60-1-1;gunpowder-0-75-3-3;leather-0-75-4-4;fish-0-75-3-3;dye-0-60-1-2
    S:"Floor 8"=ChestGenHook:chests/simple_dungeon:3
    S:"Floor 9"=ChestGenHook:chests/simple_dungeon:5
    S:"Item Generations per Floor"=7
    S:"Top Floor"=ChestGenHook:chests/simple_dungeon:7
}

result is... three empty chests.

For giggles, I set up the SAME test for 1.12.1 and...  EMPTY CHESTS...  please share your magical installation with me!

**Comment by AtomicStryker** [comment]
Ok ... funny story. So i told you the chestgenhook works, and it did, except when i checked the code that puts the result into the chests it ... did not.

Something something ported code. Take the fixed version 1.5.9 and have fun with it.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/dc33ae7bf6f2f9dd5f995139a25cccad80691ad2

**Comment by XombyCraft** [comment]
lol.  That was going to be my next guess... that the "what to put in the chest" worked, but the "actually puts it in the chest" didn't.

**Comment by XombyCraft** [comment]
BTW - works PERFECTLY now.
