### ISSUE TITLE
Not working with MC 1.12.1

### ISSUE THREAD

**Issue by Leeo97one** [AtomicStryker/atomicstrykers-minecraft-mods#138]
When used with Minecraft 1.12.1, the mod is loaded without error but do not work at all in-game.

**Comment by AtomicStryker** [comment]
Which mod? If you are talking about a coremod mod, these have 1.12.1 updates on curse available

**Comment by Leeo97one** [comment]
Oh sorry, I was talking about Multi Mine. I don't know for Curse because I always download your mods directly on your website ^_^
Thanks anyway!

**Comment by AtomicStryker** [comment]
Thanks, i will update my homepage ... EVENTUALLY
