### ISSUE TITLE
1.11.2 Infernal Mods Config not saving

### ISSUE THREAD

**Issue by Iteries** [AtomicStryker/atomicstrykers-minecraft-mods#139]
1.11.2 Infernal Mods Config not saving.
Howdy,
I been using this mod for a long time since been 1.7.10 MC and do change up or down the config and as well adding to the treasure drop.  However, since now playing 1.11.2 it seems I cannot saving the config changes.  Did something change in the change over from 1.10 to current?
Attached is the changed file I use. 

[infernalmobs(txt).txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1273194/infernalmobs.txt.txt)

**Comment by AtomicStryker** [comment]
What do you mean, cannot save? Do you mean it gets overwritten on every launch of MC? Or are you editing ingame?

**Comment by Iteries** [comment]
overwritten.   I even noticed the new config and updated but yeah it's being overwritten and now crashing if I do any changes.  I doubled checked all the IDs of mods so I don't get why the crashing now.
[infernalmobs2.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1276524/infernalmobs2.txt)

**Comment by Iteries** [comment]
Suggestion change for non-coders.  Have an option config pre-game for turning on/off the abilities of Mobs.  Just once change say a restart so options are ready set as well as add/substracting loot drops.  So far its for us to see mod.info.   Good portion of single=player mode do not know coding (programing).  Myself only a smear of knowledge being old school DOS but that been ages ago.
Sorry but I am trying to be constructive.

**Comment by AtomicStryker** [comment]
Please don't mix issues or bring up new unrelated things. I would prefer suggestions in the MinecraftForum thread, or in a seperate issue here on github. If you had a crash, show me the crash log and i might be able to help.

**Comment by Iteries** [comment]
okay, I zipped up all these extended files that I get now.  I thought it was Biblocraft because my graphic card not up to snuff but biblocraft not crashing me just giving me visual blunders, which I am removing that mod to start over.  I have also attached the logs, I think are the right ones.  Sorry about before too. 
Error extensions
[infernalmobs.cfg_20170903_000724.zip](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1290272/infernalmobs.cfg_20170903_000724.zip)  
Logs- attempts and crash
[crash-2017-09-03_02.03.37-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1290317/crash-2017-09-03_02.03.37-server.txt)
[crash-2017-09-05_00.54.27-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/1290318/crash-2017-09-05_00.54.27-server.txt)

Currently undergoing total reloading of MC with mods (32 in all) Forge 2454, Optfine HD_U_C3

**Comment by AtomicStryker** [comment]
Your config "resets" because it became invalid. It is invalid because you have line breaks in lines that don't allow them (which, for the record, is ALL OF THEM), and also lists that end on a separator (comma).

**Comment by AtomicStryker** [comment]
I will elaborate with an example: Look at infernalmobs.cfg_20170903_020923.errored

line 84 ends on a comma
line 85 ends with a comma, linebreak ... continues in line 86 ... ends with comma, linebreak ... continues in line 87

To fix this config file, you need to remove the last character in line 84 and merge lines 85, 86, 87 back to a single line
