### ISSUE TITLE
Ruins 1.12, 1.12.1 - Multi-word biome folders unusable

### ISSUE THREAD

**Issue by st753m** [AtomicStryker/atomicstrykers-minecraft-mods#144]
Structures placed in multi-word biome folders within config/ruins_config do not generate.

Minecraft Version: 1.12 and 1.12.1
Ruins Version: Every version for 1.12 and 1.12.1 since changing from .zip to .jar format
Forge Version: 14.22.0.2474 and 14.22.0.2480 for 1.12.1 tested recently

Steps to duplicate:
 - Place one or more templates within a biome folder with multiple words (extreme_hills, ice_flats, anything with an underscore)
 - (Optional: remove templates from generic to avoid interference)
 - Generate a world and search for ruins in that biome (a single-biome customized world is preferable)

I have tried using the Ruins-generated biomes (extreme_hills) as well as the old .zip spelling (Extreme Hills)

**Comment by QuarterAnimal** [comment]
When parsing the "specific_xxx" variables in the config file, the underscore character is being used as a delimiter. As a result, the first underscore in a biome name and everything after it is dropped (i.e., "extreme_hills" is read as "extreme"). The intended biome, therefore, winds up with a biome-specific spawn chance of zero and only generic templates are used.

**Comment by AtomicStryker** [comment]
Oh, the pull merge auto closed this? So i see. 16.9 for 1.12 and 1.12.1 should have the fix, thanks for reporting it.
