### ISSUE TITLE
Boss Bar showing inconsistently

### ISSUE THREAD

**Issue by D3nnis3n** [AtomicStryker/atomicstrykers-minecraft-mods#147]
Hello,
i've got the Problem that the Boss Bar that is enabled and supposed to Show up when confronted with an infernal mob only Shows very inconsistently. Most times i don't see the bar at all, sometimes i see it for a short while, but if i go away some block i do no longer see it and also don't see it again when i go back into fight. I have this Problems for ages and thought i'd Report it.

**Comment by AtomicStryker** [comment]
Please check existing or past issues before opening a new one, this is literally the previous one: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/pull/146

**Comment by D3nnis3n** [comment]
Eh tanks for the headsup, but that issue does not show up in your issue list. Neither under closed nor unter open. Therefore i was not able to find it. I can't find it without clicking that link at all. Despite that, i'm sorry nevertheless.

**Comment by AtomicStryker** [comment]
I am assuming version 1.12.1 by the way, for which the fixed version can be found for example here https://mods.curse.com/mc-mods/minecraft/227875-atomicstrykers-infernal-mobs

**Comment by AtomicStryker** [comment]
Well, you are right. It WAS an issue before the fix pull request came in ... don't know what github is doing there, honestly

**Comment by D3nnis3n** [comment]
Eh, i'm using that version and am having the same problem, still. I'll doublecheck. It's hard to keep track as you don't use version numbers in the jars. I report back if i have been dumb or really stil got the problem.

As for the issue: Yeh, i saw it in the pull requests now, but honestly i'm no developer and keep away from that tab. I'll look into this in the future, too.

**Comment by D3nnis3n** [comment]
Okay, my fault. But it only appears when hovering over the head, which is a bit suboptimal, if someone would ask me - i would prefer to have that overlay as soon as i hover any body part. Also, when i would be allowed to request a feature: I Would like version numbers in the jar *g*

Sorry anyways for my bad report.

**Comment by AtomicStryker** [comment]
I had specifically not changed the version for this bugfix as it is a client-only bugfix that doesn't break compatibility. If there is a problem with the "view hitbox" please document it with screenshots (in a new issue) - assume i don't have the time to start up mc and check for myself.

**Comment by D3nnis3n** [comment]
I'll do that. But it seems like in jars you only use Version number of minecraft, for all versions for that. That makes it really hard to distinguish the versions for each minecraft Version as they're all named the same.

**Comment by AtomicStryker** [comment]
That's for reasons of "hotswapping" jars on filehosters. The changelog.txt and mcmod.info inside will have the "actual" mod version.

**Comment by D3nnis3n** [comment]
That's okay, if it is okay for you. But out of a perspective of a user of 200 mods where you are the only one not having versions in the jars it's hard, as i work with them to update. I do not read the changelogs or the mcmod info when i update my mods ;) It was just a Suggestion. Please do not feel attacked by my Suggestion :) That was indeed the reason why i had not had the newest Version. I Name my mods like this: 

[CS]-TinkerIO-2.5.4e
for Client / Server - Mod Name - Addon - Version
