### ISSUE TITLE
Boss Health Overlay only on Heads and through Walls

### ISSUE THREAD

**Issue by D3nnis3n** [AtomicStryker/atomicstrykers-minecraft-mods#148]
I just try it, Close it outright, if it's not okay:

1. Boss Overlay only appears when aiming at the head, not at the Body - seems pretty suboptimal to me.
2. Boss Overlay appears despite there is no line of sight to the mob. If there is an mob two rooms away from me and i mange to Point my Cursor where his head would be if there weren't four walls in between while Building the overlay get's also shown. That's scary as the boss mob is not in near but the overlay is shown.

**Comment by D3nnis3n** [comment]
Here is a screenshot for 1:
https://ibb.co/nrAM8k

Making a screenshot for 2 is pretty hard, i try it.

**Comment by D3nnis3n** [comment]
Here is a Picture for 2:
https://ibb.co/he0qZQ

Creeper also has the Problem i Need to Point above him to see the overlay, as he is not as big as a Zombie. But if he is behing a wall or in another room, or between fifteen walls or even a layer beyond you and you hit the spot with your Cursor you can see this overlay - up to say 16 blocks away?

This also makes it possible to spot where infernal Mobs are without seeing them, which is not that great.

I hope the screenshots help.

**Comment by AtomicStryker** [comment]
I found some spare time and invested it for you https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/100090201d88ca5312281b48c176bc4ec328f4bc

1.7.3
- reworked time based attack logic - nonhostile mobs (eg pigmen or creative mode) will no longer affect you unless actually in combat
- reworked hitscan for health bars, now works more reliably

Enjoy

**Comment by D3nnis3n** [comment]
Whoa, thank you very much! Seems like even Version numbers are to come! I'll run and test! :)

**Comment by D3nnis3n** [comment]
Overlay works great now. For the not attacking in creative: This does not work with pigmen and i only could find a rare pigman. I read on another issue that those had a Special behaviour, is this the cause? If yes, i suppose everything is working great.
