### ISSUE TITLE
[Suggestion] Integration / Addon with GameStages

### ISSUE THREAD

**Issue by KAfable** [AtomicStryker/atomicstrykers-minecraft-mods#153]
Would it be possible to add in Infernal Mobs integration with Game Stages API (https://minecraft.curseforge.com/projects/game-stages)? Some possible use cases would be allowing certain players to unlock some of the more difficult modifiers (such as teleport/ninja) depending on the stage of the player. In addition as a player advances through the stages, we could have increased spawn rates of epic/boss mobs.

I mostly want to use Infernal Mobs as a form of difficulty advancement in my pack since it adds different mob behaviors and mechanics that's better than pure numbers scaling, and as the player unlocks different dimensions, the mobs can get more difficult now as well.

Thanks,

**Comment by AtomicStryker** [comment]
This doesn't really work on server? Which player would the server "target"? Even in single player this would cause issues, as mobs are spawned WAY in advance of a player getting near - presumably the player does not move all that much for the initial mine and gaining much progress, while all mobs he encounter remain noob tier

**Comment by KAfable** [comment]
So I implementation on server would probably be individual, as stages should be stored per player. If there's a group of players in close proximity, then the most fair thing would be mobs spawning with infernal modifiers according to the highest advanced player.

It might've been better if I linked this instead which is a pre-existing mob add-on with game stages. I'm not sure exactly how you implement your modifiers, and can't offer much insight, but the game stages and advancements are decided by the modpack devs. It doesn't have to be only distance, I can make it so once a player crafts their first iron chestplate, they advance a stage and suddenly mobs can spawning with ghastly modifier.

https://minecraft.curseforge.com/projects/mob-stages

**Comment by AtomicStryker** [comment]
So i've looked at the API and it works like i assumed it would - when a mob spawns it simply checks all players and a "high level" player needs to be close for high level mobs to spawn. In the context of Infernal Mobs, you would likely never ever see high level mobs unless you already were high level and specifically set out on a journey into new chunks.

Excuses aside, implementing this is a couple hours of work.

**Comment by KAfable** [comment]
I think that's a reasonable form of progression - I originally planned to scale my pack in terms of dimensions, so that mobs in later dimensions would be have more modifiers / greater scaling. They start off mostly in a skyblock, but need to venture to various dimensions to get various materials.

**Comment by AtomicStryker** [comment]
Well, as you can do THAT right now and i am not planning to implement this anytime soon, i would suggest you do that. This goes on my "if you're bored and want to sink some hours into mc coding" list.

**Comment by KAfable** [comment]
I can't implement it to the degree of accuracy I wanted since the dimension blacklist is a blacklist for _all_ modifiers, whereas my hope was that only certain modifiers would be unlocked after hitting a specific advancement. For example 1st dimension is only gravity and darkness, and then later it will be Ghastly/Lifesteal, and then last all modifiers will be unlocked.

But I understand, thank you for your time and for the mod.
