### ISSUE TITLE
Can't heal dead bat

### ISSUE THREAD

**Issue by TBlazeWarriorT** [AtomicStryker/atomicstrykers-minecraft-mods#155]
1.12.2, latest version everything (latest recommended forge)
The mods I'm using are AutoSwitch, AmbientSounds, BetterFoliage, ClientTweaks, DynamicSurroundings, InfernalMobs, InventoryTweaks, LevelUp Mod, MultiMine, Neat Mod, OptiFine, PetBat, RoguelikeDungeons, Skillable mod and ZombieAwareness.

My bat got killed by a modified zombie from Infernal Mobs I believe, and I can no longer heal him.
I tried repairing him using both him and a pumpkin on an anvil, crafting on a crafting table (tried all slots) and dropping both on ground, nothing seems to revive my bat. I believe there must be something broken or a compatibility issue.
I opened this issue for help, as I'm particularly curious about this, since the bat and everything works perfect, except for healing him.
Thanks

**Comment by AtomicStryker** [comment]
It worked fine in my debug playtest - make sure to drop the pumpkin pie first, then, as it lies on the ground, drop the inert bat ontop of it.

I may re-enable the craft-to-heal part when the Forge recipe manager lets me.

**Comment by TBlazeWarriorT** [comment]
![ezgif com-optimize 9](https://user-images.githubusercontent.com/25572454/32419662-d5055d94-c264-11e7-8a1c-c914dac6d2c9.gif)
Tried again, even included a GIF of the attempt if it helps. Bat still not healing.

**Comment by AtomicStryker** [comment]
Make sure you are using the latest file? https://github.com/AtomicStryker/github.io/blob/master/files/1.12.1/PetBat-1.12.1.jar

If that doesn't work, we will have to make a debug variant for you

**Comment by TBlazeWarriorT** [comment]
I removed Petbat-1.12 and replaced it with PetBat-1.12.1. The bat now properly heals using pumpkin, and the mod should be usable, I hope, thanks a lot.
But I accidentally dropped the bat flute too, and the item gets deleted whenever I drop it. It gets deleted as soon as I drop it (I tried placing it on a chest and taking it back, seems fine), is that supposed to be like that? The bat doesn't disappear though (thankfully I backed my map up, so I could get my Bat Flue back for now)

**Comment by AtomicStryker** [comment]
Yes, bat flutes cannot be dropped to world.

**Comment by TBlazeWarriorT** [comment]
I assume everything is OK then, thanks!

**Comment by AtomicStryker** [comment]
That is good to hear. Thank you
