### ISSUE TITLE
Minor sound errors

### ISSUE THREAD

**Issue by PhoenixRiver** [AtomicStryker/atomicstrykers-minecraft-mods#156]
Just looking into the latest version of Minions and noticed that two of the sound files are not being loaded, just the directory and they are there but include capital letters but the versions being looked for don't have those capitals - changing the asset names fixed the problem; they are baseballbatjingle.ogg and fff.ogg - hope this helps! :D

**Comment by AtomicStryker** [comment]
Sorry, i had forgotten about this but then i remembered. https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/246555b33cf1d97d0fb64e583d351c924eca16ff, https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/b8879c82305ecd54da24afda94c10357f9f3639a thank you for mentioning it.

**Comment by PhoenixRiver** [comment]
No problem and thank you for the fix :)
