### ISSUE TITLE
Minecraft 1.12.2 serverside crash in postinit

### ISSUE THREAD

**Issue by ASpieler** [AtomicStryker/atomicstrykers-minecraft-mods#157]
pertinent information is here:

```
net.minecraftforge.fml.common.LoaderExceptionModCrash:` Caught exception from Minions (minions)

Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at twilightforest.block.BlockTFSapling.func_149732_F(BlockTFSapling.java:133) ~[BlockTFSapling.class:?]
        at atomicstryker.minions.common.MinionsCore.getViableTreeBlocks(MinionsCore.java:289) ~[MinionsCore.class:?]
```

before you try to tell me the erroring mod is The Twilight Forest, and pass it off like you did with #109, you need to reexamine your code, line 289 of MinionsCore.java calls getLocalizedName, which in turn calls net/minecraft/client/resources/I18n, which is a client-side only class. and for verification, i got this error with and without TF in the pack, but not without minions.

Please fix this, I and others would love to use your mod on a server, and as it currently sits, it can't be used.

**Comment by AtomicStryker** [comment]
How could i say no to passive-aggressiveness
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/96ce50959247faf0836f912b700625f287841cc9

**Comment by ASpieler** [comment]
thank you for the prompt fix, as I said, several of us were looking forward to using this on a server, and we do appreciate the work you put into all of your mods.

P.S. yes, that fixed it, it is now getting along fine with 262 other mods in a huge pack, so, again, thank you.
