### ISSUE TITLE
API for DynamicLights

### ISSUE THREAD

**Issue by olee** [AtomicStryker/atomicstrykers-minecraft-mods#16]
Hi there

A friend and me would like to refer to your DynamicLights mod as a dependency to add some dynamic light sources. I got this working by putting a deobf copy of your DynamicLights jar into the "libs" folder of our gradle mod project. This works fine for lokal development, but now we would like to move this project to github. The problem is that we would have to commit the deopfuscated version of your mod to the repository. I think you probably won't like that which is why I am asking you here:

Is there any API jar for DynamicLights (as far as I can see not) or would you mind providing one?
If not, is there some other way you could tell us to link to your mod for building?

Regards
olee

**Comment by AtomicStryker** [comment]
You can certainly just use gradle and link to the open source files on github? https://raw.githubusercontent.com/AtomicStryker/atomicstrykers-minecraft-mods/master/DynamicLights/src/main/java/atomicstryker/dynamiclights/client/IDynamicLightSource.java
