### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by alexbobp** [AtomicStryker/atomicstrykers-minecraft-mods#160]
Hi, am trying to put together an all-open-source modpack.  It says on your about.php page that all your work is open source.  However without specifying a license or a public domain dedication, it's still technically all-rights-reserved.  This means that someone wanting to make a derivative work could potentially be in legal hot water even if you have the best of intentions.

Obviously I'm here because I love your work, especially Multi Mine which is an unparalleled quality of life improvement and I've come to include it in every normal modpack I make and get grumpy when I don't have it.  I would love to be able to include it in an all-open-source modpack as well.  For me to be able to do so it has to have a free license.

There are a lot of licenses to choose from but the main choice is probably permissive vs share-alike.  If you use a license like those in the GPL family, you can require any work based on your mod to be open source and retain the license, which seems to be in keeping with your goals to prevent other people from just monetizing your work.  There are also some super short and simple options like the MIT license or simply a public domain dedication.

If you want to make sure you have the right to use any license you want in the future, but force other people to adhere to a share-alike licence like the GPL, you can start asking people to agree to a contributor's agreement that reserves that right for yourself, before you accept their pull requests into your codebase.

Sorry for being long-winded.  I think the modding community is finally approaching a point where we could have fantastic full-featured modpacks made from just open source mods, and your work could definitely help it get there.  Note that I am not asking for any kind of personal permissions.  I want this pack to showcase mods that *anybody* can fork and play with freely.

**Comment by AtomicStryker** [comment]
Oh? I thought that text constitutes a license. Nobody complained the last years. "Specifying a license" is for people who didn't write anything on the subject, but i have. Is something SPECIFIC missing from my license?

**Comment by alexbobp** [comment]
The main thing I would like to see clarified is if people have permission to make derivative works (like forks of your mod, or using your code in other mods).  Also it would be helpful if the license were included in a file in the github repository.  Thank you very much for a quick response, and sorry if my request is annoying, but adding a bit of clarity will help people like me!

(In case it wasn't obvious, I'm very much hoping you'll say that you are fine with derivative works)

**Comment by AtomicStryker** [comment]
"You are allowed to read and use the provided Sourcecode in order to make interacting mods so long the resulting mods still require my originals to function. You are allowed to integrate ideas or techniques from my Sourcecode into your Mods. "

So, a fork would not be allowed to be distributed (as it would not require my original to function), but you can take parts.

The license file is in the repo root:
license atomicstryker.txt

**Comment by alexbobp** [comment]
My mistake, I looked for that file, but I see it now.  Okay then, my advice would be to update about.php and remove the part where you say "All my work is open source," since that is not an open source license.  It is, of course, your right to license your awesome work however you want, but open source licenses do allow redistribution of modified works.  Keep in mind that this is still a developer *community*.  Just because people can fork something doesn't mean they will... people will prefer to contribute patches to your upstream version of the project as long as you are actively maintaining it and reviewing PRs.  A proper open source license would mean the community doesn't have to have as much fear of what will happen if you move on from minecraft modding, because someone else could take up the mantle.

**Comment by asiekierka** [comment]
@AtomicStryker 

Your existing license effectively has a loophole: for most of your mods, taking the ideas and techniques is sufficient to create a mod that doesn't actually duplicate the content 1:1 but contains sufficiently similar functionality. That means, while a direct fork cannot be done, one can use your code to reimplement a mod which is a fork in spirit, but not in law. Is that intended?

Now, there are many definitions of "open source". @alexbobp seems to follow something more akin to [the Open Source Definition](https://opensource.org/osd-annotated), which is one of the definitions, a fairly commonly accepted one, but "open source" can mean anything from "visible source" to that; this is why I prefer the term "free software" as understood by the FSF instead.

Your license as it currently exists is not open source as per the OSD nor is it free software as per the FSF; however, the source code is visible and allowed to be studied.

At this point, I think you might benefit from a copyleft license such as the LGPL/GPL: first of all, it's actually tested by lawyers, so you can be sure the license will hold up; second of all, your protections against ripping your work are irrelevant in practice, unless you do genuinely only care about direct forks not existing and are okay with nearly identical mods being developed...

**Comment by AtomicStryker** [comment]
We're all aware that if someone WANTS to "steal" the mods, they can, irregardless of what i write in a license. In fact my jar files have always been "pirated" by the plentiful mod portals and put behind their pay4click engines. I don't intend to persecute any of this as that's pointless.

So, my license doesn't have to be lawyer tested or approved.
The actual usecase, so to say, is to stop honest developers from just forking the mods, keeping the name or slightly altering it, and basically saying it is their mod now. That would .. displease me.

Also if someone less than honest did it i could probably get the ripoff banned off curse atleast. Eh.

**Comment by asiekierka** [comment]
Right. Fair. I guess this issue can be closed now. (For whatever it's worth, this is why I avoided studying their source code previously - as I might be looking into similar fields of functionality for my own mods, and I enjoy keeping in line with free software principles for them - but that's just a personal comment.)

EDIT: As a side-note, almost every license requires attribution - even the MIT License requires you to keep the original copyright notice, including the author's name!

**Comment by alexbobp** [comment]
Well I don't want to drag this on too much.  I respect your work regardless of your choice here.

I do want to point out that how you license your code has nothing to do with your branding.  You can use an open source license and you still have full rights to your mod's name and branding, and you can very reasonably expect honest developers to come up with their own name and brand if they want to re-use your work.  I don't think anyone even wants to try to mess with your brand, because the community benefits greatly from keeping modders like you happy and motivated.  It's the code itself that I'd like to see open.  Also as asie mentions, under many open source licenses, derivate works would still have to explicitly credit you as the original author.  I hope this makes you willing to reconsider... but anyways I'll stop bothering you, rock on man.
