### ISSUE TITLE
Ninja enchantment still 'ninjas' mobs underground, causing them to choke and die

### ISSUE THREAD

**Issue by DBotThePony** [AtomicStryker/atomicstrykers-minecraft-mods#161]
This issue appeared on minecraft `1.10` or even earlier.

The most interesting - `ender` enchantment has no flaws in it.

**Comment by AtomicStryker** [comment]
Does 1.12 still have the bug? I think i remember fixing it, mostly by copying the minecraft teleport code again (they refactored it at some point).

**Comment by DBotThePony** [comment]
Im on 1.12.2

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/353ef6ed5b8d94552affdfcae2510d6ed6251e45 should fix it. See if it does, please.

**Comment by DBotThePony** [comment]
Code seems good, will check when i wake up

**Comment by DBotThePony** [comment]
Fix seems to work

**Comment by Angular-Angel** [comment]
This still happens on 1.17.

**Comment by AtomicStryker** [comment]
It was a copy of the 1.16 vanilla teleport code. It's possible they changed it again for 1.17 - i will have look ... EVENTUALLY
