### ISSUE TITLE
Enchanted mobs sometimes trigger attack at player even if mob is not targeting anyone

### ISSUE THREAD

**Issue by DBotThePony** [AtomicStryker/atomicstrykers-minecraft-mods#163]
e.g. A Pigman with Fireball enchantment will cast fireballs at player even if pigman is neutral.

Same goes to targeting - Enchantments with auto trigger *(choke/alchemist/fireball/blastoff/...)* should target only prey of mob, not *any* player within sight of mob

Same goes to spiders at daytime (even from mods), etc.

I know it was reported earlier, but looks like it bugs differently in multiplayer.

**Comment by AtomicStryker** [comment]
This is actually a minecraft bug of sorts - the mobs constantly target the player and drop the targeting immediatly, which unfortunately is enough to set off Infernal Mobs effects.

I think i fixed this for the current version of 1.12 (a target has to be targeteted uninterrupted for several ticks before a modifier triggers).
