### ISSUE TITLE
Infernal Mobs conflicts with some entities

### ISSUE THREAD

**Issue by DBotThePony** [AtomicStryker/atomicstrykers-minecraft-mods#164]
Causing spam like ![spam](https://i.dbot.serealia.ca/2017/12/eda3a738b8_cmd_2017-12-10_12-06-17.png) appear both on clientside and serverside.

This doesn't crash game, however, this causes **major** FPS lag (only if console is open) and entities which are incompatible with `Infernal Mobs` are not appearing on client.

Example - Mekanism's Flamethrower flame (great for reproduction and debugging).

**Comment by AtomicStryker** [comment]
Uhhh Infernal Mobs should only trigger for EntityLiving(Base?), why would a flamethrower flame use that?

If this happens for whatever reason, i suppose it is the users responsibility to set the Entity as blacklisted in Infernal Mobs config

**Comment by DBotThePony** [comment]
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/entity/EntityFlame.java#L33 🤔

**Comment by AtomicStryker** [comment]
Are you sure that problem is even related to infernal mobs? https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.12.2/InfernalMobs/src/main/java/atomicstryker/infernalmobs/common/EntityEventHandler.java#L58
I mean, looking at that stack nothing jumps at me

**Comment by DBotThePony** [comment]
Will investigate futher
