### ISSUE TITLE
[Suggestion] Battle Tower Building Material

### ISSUE THREAD

**Issue by MasterEnderman** [AtomicStryker/atomicstrykers-minecraft-mods#166]
Could you add a config option to specifiy which blocks should be used, when a tower is generated, because the towers out of stone look a bit missplaced in the nether and the end.

**Comment by AtomicStryker** [comment]
Then your next request would be to "map" tower types to specific terrain. I'm not saying "no" to the idea, i'm saying "no" to me implementing this. But thank you for the suggestion.
