### ISSUE TITLE
Option to disable spawn of infernal mobs for some days since world creation.

### ISSUE THREAD

**Issue by NightKosh** [AtomicStryker/atomicstrykers-minecraft-mods#167]
It is incredibly hard to fight with them in first days without any appropriate armor, weapon or escape it in shelter.

**Comment by AtomicStryker** [comment]
There's problems with that - first, i don't know if i can actually "count" the days passed in a minecraft world. Is it a value written somewhere ingame?

Second, MC generates mobs very far in advance, usually. It would then just load these pre-generated mobs (and their weak Infernal types) as the player explored caves and whatnot. They would be unlikely to meet anything but the "day 0" mobs and the "maximum" mobs, when they finally set out much later.

Third, assume you are on a server with multiple players. One joined much later than the others. Should the mobs be nerfed? How will that be calculated?

I agree that high level Infernals can basically only be fought with top tier gear. However, situations in MC where you can't simpy run (or wall off) are rare. IMO.

**Comment by NightKosh** [comment]
Yes, I fully agreed with you. This is just an optional suggestion.

As for days - it can be counted by passed time.
