### ISSUE TITLE
Multimine causing hiccuping lag spikes - 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AtomicStryker/atomicstrykers-minecraft-mods#169]
Okay so I loved Multimine 1.7.10 it was perfect with 1.12.2 it keeps causing lag spikes even if I just stand still ... I don't have a crashlog because its not crashing and I am not going to die if you don't fix it but its just something I wanted to bring to your attention @AtomicStryker

**Comment by AtomicStryker** [comment]
"It" causes lag spikes? That isn't enough information to go on. Just loading the mod does that? Do you have to partialbreak some blocks for it to happen? Does it stop once there are no partial broken blocks?

**Comment by P3rf3ctXZer0** [comment]
It just has to be in the modpack. I am sure its due to the way recent forge versions changed the way ticks are handled. I will actually investigate more after I get further along in my modpack.

**Comment by AtomicStryker** [comment]
I doubt very much it is Multi Mine. The server side interaction of the mod with the world is very limited in scope, and there are no complex calculations being made. There is a hard limit on affected blocks, too. If you do manage to reproduce a Multi Mine issue, you may reopen this.

**Comment by P3rf3ctXZer0** [comment]
Will do.

**Comment by ThaDaVos** [comment]
I ran into the same and got some more info:
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/291
