### ISSUE TITLE
java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Tsyklop** [AtomicStryker/atomicstrykers-minecraft-mods#17]
http://pastebin.com/3gZKiUWJ

https://github.com/tterrag1098/WAILAPlugins/issues/43

**Comment by AtomicStryker** [comment]
Hmm mcinstance is null, ergo FMLInitializationEvent was never passed to the module or FMLClientHandler.instance().getClient() failed to return a Minecraft reference. I't not sure what i can do about this, its an outside failure.

**Comment by Tsyklop** [comment]
So what to do?
I removed the normal mode and the client started.

**Comment by Tsyklop** [comment]
I deleted ttCore and no crash.

**Comment by AtomicStryker** [comment]
Try re-adding it and see if it works now now (delete your configs, do 
you have outdated ones maybe)

**Comment by Tsyklop** [comment]
@AtomicStryker I put ttCore-MC1.7.10-0.1.1-78, deleted and removed config configuration DynamicLights - same crash

**Comment by AtomicStryker** [comment]
Ive glanced at ttcore source and can find nothing extreme being done there, maybe ask the author perhaps he knows something.
