### ISSUE TITLE
[PetBats] Bat flutes can be tossed client-side

### ISSUE THREAD

**Issue by Tora-B** [AtomicStryker/atomicstrykers-minecraft-mods#173]
When on a server, it's possible to throw bat flutes, and they will disappear from your inventory until you disconnect and reconnect, presumably because the ItemTossEvent is only cancelled server-side.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/c47f14b08f6d99456fffa0725622e452a02c6b17
Thanks for reporting
