### ISSUE TITLE
[Multi-mine] Dupes every Thermal Expansion machine

### ISSUE THREAD

**Issue by Aphyxia** [AtomicStryker/atomicstrykers-minecraft-mods#175]
Steps to reproduce:
1) Install Multimine, Thermal Expansion and all it's prerequisites.
2) place any machine block, for example Steam dynamo
3) break it with a pickaxe
4) You get 2!

Forge 2587
Minecraft 1.12.2
Latest Thermal and Multi-mine, as of this time.

**Comment by AtomicStryker** [comment]
An unfortunate interaction of the highly customized Thermal Machine block code (the way they "drop" does not match how MC does it) and Multi Mine. My recommended solution is to put such Blocks on the Multi Mine blacklist.

**Comment by Aphyxia** [comment]
Thanks for the clarification. Do they all have to be manually added?
Currently there seems to be a row in banned items AND blocks in the list like this: B:"thermalexpansion:dynamo-0"=false
Guessing setting it as true will block it but..

Is there some kind of shorter version available like thermalexpansion:* to block all thermal expansion blocks? I guess I could also place all the blocks and destroy them once, that seems to add them to the list. (there's like thousands of rows of actuallyadditions:obsidian_paxel in my server side block list for some reason though...) 

Also, do I have to block both the item and block and what is the difference of a block and item in the block list?

**Comment by AtomicStryker** [comment]
Blacklisting a block prevents Multimine from affecting the block (placed in world). Blacklisting an item prevents Multimine from working when the player is holding it (to break blocks with).

The config does not currently support wildcards or anything similar.

**Comment by notfood** [comment]
I got bitten by this. Very annoying. There should be a way to blacklist mods, or at least the block with all the metadata. Right now the list grows large when in reality it's just 5 blocks with different metadata.

Here is the list if anyone needs it:
```
    B:"thermalexpansion:cell-0"=true
    B:"thermalexpansion:device-0"=true
    B:"thermalexpansion:device-1"=true
    B:"thermalexpansion:device-2"=true
    B:"thermalexpansion:device-3"=true
    B:"thermalexpansion:device-4"=true
    B:"thermalexpansion:device-5"=true
    B:"thermalexpansion:device-6"=true
    B:"thermalexpansion:device-7"=true
    B:"thermalexpansion:device-8"=true
    B:"thermalexpansion:device-9"=true
    B:"thermalexpansion:dynamo-0"=true
    B:"thermalexpansion:dynamo-1"=true
    B:"thermalexpansion:dynamo-2"=true
    B:"thermalexpansion:dynamo-3"=true
    B:"thermalexpansion:dynamo-4"=true
    B:"thermalexpansion:dynamo-5"=true
    B:"thermalexpansion:machine-0"=true
    B:"thermalexpansion:machine-1"=true
    B:"thermalexpansion:machine-2"=true
    B:"thermalexpansion:machine-3"=true
    B:"thermalexpansion:machine-4"=true
    B:"thermalexpansion:machine-5"=true
    B:"thermalexpansion:machine-6"=true
    B:"thermalexpansion:machine-7"=true
    B:"thermalexpansion:machine-8"=true
    B:"thermalexpansion:machine-9"=true
    B:"thermalexpansion:machine-10"=true
    B:"thermalexpansion:machine-11"=true
    B:"thermalexpansion:machine-12"=true
    B:"thermalexpansion:machine-13"=true
    B:"thermalexpansion:machine-14"=true
    B:"thermalexpansion:machine-15"=true
    B:"thermalexpansion:strongbox-0"=true
    B:"thermalexpansion:tank-0"=true
```

**Comment by Draskh** [comment]
I had the same severe issue. https://github.com/CoFH/Feedback/issues/1133

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/40f9c2818ec43c6b691aa331ae09b79cf8ab91d4

Multi Mine 1.6.0 adds regex support to blacklist entries. Put in ^thermalexpansion and be happy
