### ISSUE TITLE
Door Code Issues? MC 1.12.2 and forge 1.12.2 - 14.23.1.2589

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AtomicStryker/atomicstrykers-minecraft-mods#177]
https://gist.github.com/P3rf3ctXZer0/af5bbc7838e74a61aecfb95b7709f033

Multimine 1.12.2 - v1.5.7 
https://minecraft.curseforge.com/projects/multi-mine/files/2468185

**Comment by AtomicStryker** [comment]
Huh, that actually looks like a bug in minecraft (or maybe forge caused??) which triggers when Multi Mine tells a door block to "be removed". I am currently away on business. Will check this out once i am back assuming i didn't forget about it in the meantime.

**Comment by P3rf3ctXZer0** [comment]
Tis fine Major I just thought you would like it brought to your attention. (I love that avatar)

**Comment by AtomicStryker** [comment]
Thanks for reporting it, the MC code with door is indeed strange. https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/fcc8a6a60de956f4db39e21c965083bd737dce1c
I tested it myself and i could break doors multi mining no problem, please check also
