### ISSUE TITLE
Dynamic Lights FPS drop when toggling dynamic lights.

### ISSUE THREAD

**Issue by ProsperCraft** [AtomicStryker/atomicstrykers-minecraft-mods#180]
1.12.2

When I toggle dynamic lights off my FPS tanks hard.  It stays this way until I restart the client.
- DynamicLights-1.12.1
- forge-1.12.2-14.23.1.2601-universal

**Comment by AtomicStryker** [comment]
Cannot reproduce on forge 2600. Cannot reproduce on forge 2619. Cannot think of a reason why disabling Dynamic Lights (which only LESSENS the amount of code run) would do this.
