### ISSUE TITLE
Battle Towers CTD with Everlasting Abilities is installed 1.11.2

### ISSUE THREAD

**Issue by DatrixTHLK** [AtomicStryker/atomicstrykers-minecraft-mods#186]
Hi AtomicStryker,

I left this issue on Everlasting Abilities [github page](https://github.com/CyclopsMC/EverlastingAbilities/issues/78) because I thought it was due to one of the abilities within the mod, it turns out that when I took out your mod the game is no longer crashing on me within the first few minutes after traveling in the overworld.

Minecraft 1.11.2
Forge: 13.20.1.2588
Battle Towers: 1.11.2

**Comment by AtomicStryker** [comment]
The problem is on the Ability mods side, sorry.
