### ISSUE TITLE
Infernal Mobs Crash

### ISSUE THREAD

**Issue by ReportBot9009** [AtomicStryker/atomicstrykers-minecraft-mods#19]
Hello AtomicStryker,

Let me preface with my setup and what happened prior to the crash.

I had dug a small pit with Ineffable Glass from ExU so that mobs would fall through. I had fans from OpenBlocks blowing one direction, where at the end, I had setup Diamond Spikes (ExU) enchanted with Looting. The mobs would fall, get blown into the spikes, which were up against a wall of Ineffable Glass, where they would die and on the other side an Item Collector (Random Things) would collect loot.

An infernal mob fell into the pit, got blown into the spikes and was whittled down. As soon as the mob hit 0 health, the game crashed with this log: http://pastebin.com/BSSsVf8g

It looked as though the Infernal Mob kept lagging through the glass, spikes and floor. I thought at first something was a little wrong, since normal mobs were not behaving this way.

Also, this crash has ExU and your mob near the top, so I thought submitting to you first because normal mobs didn't behave this way... I'll gladly send it over to RWTema if you don't think this is you.

Anyhow, I hope that's enough information.

Take care.

**Comment by AtomicStryker** [comment]
Since Infernal Mobs is not even mentioned in the crash trace, and in fact this crash explicitly calls it a tile entity collision issue, i would take this to the ExU dev first.

**Comment by ReportBot9009** [comment]
Very well. Sorry to bother then. I'll send it over there.

Thanks AtomicStryker!

P.S. I love your mods! Thank you :)
