### ISSUE TITLE
[Feature Request] [Battle Towers]

### ISSUE THREAD

**Issue by psymin** [AtomicStryker/atomicstrykers-minecraft-mods#190]
I'd love to have the option to have towers only spawn in the Overworld.

I know that this is technically possible from an end-user perspective by getting a list of every biome and setting it to "false" in the config, but it would be a lot more user friendly if one of the two following options were available:

A dimension whitelist or blacklist, to expressly state which dimensions towers were allowed or disallowed in.

A biome whitelist that expressly forbade any biomes not in the list from generating towers.

**Comment by AtomicStryker** [comment]
Sorry i didn't comment earlier but i was avoiding this. More user friendly, yes i guess, but i don't feel like coding that myself. If you would like to code it, sure, add a pull request and i would merge it.
