### ISSUE TITLE
[Ruins] Structures spawn in midair

### ISSUE THREAD

**Issue by Insane96** [AtomicStryker/atomicstrykers-minecraft-mods#192]
Ignore the webcam u.u
![image4](https://user-images.githubusercontent.com/7185104/39172126-2266b8a0-47a1-11e8-801d-bf3c2c688f15.png)
![immagine](https://user-images.githubusercontent.com/7185104/39172420-f9c4a8c0-47a1-11e8-936f-a75c3d3400ef.png)
![immagine2](https://user-images.githubusercontent.com/7185104/39172419-f98f10f2-47a1-11e8-9028-732c5efc1402.png)

**Comment by AtomicStryker** [comment]
Misconfigured template. Ruins can "flatten" terrain and also "embed" structures into it. See the MCF thread for tips and examples.

**Comment by Insane96** [comment]
But I'm using default templates

**Comment by AtomicStryker** [comment]
That doesn't make them any less misconfigured, friend :)
EDIT: I am taking fixes as pull requests yes please

**Comment by Insane96** [comment]
Sure would do but I can't find any useful information in MCF thread about the fields in a .tml file.

**Comment by Insane96** [comment]
Found it! https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.12.2/Ruins/src/main/resources/examplesAndDocs/template_rules.txt
