### ISSUE TITLE
[Feature Request] ESC out of Minion menu.

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#196]
Most in-game GUIs can be easily dismissed with the Escape key.  Your Minions menu cannot -- it requires a button press in the GUI.  This makes the menu an interface "pothole" -- if a player accidentally invokes it, it interrupts the flow of the game as they need to remember "oh, it's this one" and hunt for the button.

This should be easy enough to fix, and would make your GUI fit in with the others.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/ce3bd0d72faeae9aad49fcc0e516e9acc70a9440

Thank you, i've fixed it. I will update the downloadable files without pushing a new version (aka hotfixing it) as the change is trivial.
