### ISSUE TITLE
[Dynamic Lights] Stuck at joining server screen

### ISSUE THREAD

**Issue by Kylebartaous** [AtomicStryker/atomicstrykers-minecraft-mods#200]
Mine craft: 1.12.2
Forge build: 14.23.3.2698
Dynamic lights build: ...

Gotten stuck at joining server screen so i disabled each mod and tested one by one. found this mod was the problem so i tried a new profile on the twitch launcher w/ only this mod & the problem is still happening, here's the logs and stuff to try to figure out what it the cause. It doesn't gen a crash log so may have limited info to give.

//note the log keeps repeating after the first error cause message so i had removed dup  lines till the end part

https://pastebin.com/iLwcA79K

**Comment by AtomicStryker** [comment]
Dynamic Lights is a clientside only mod. Attempting to run it on server has the coremod part break the World, which is what your log shows.

**Comment by AtomicStryker** [comment]
Uh sorry i didn't properly read. You are not referring to a standalone server. The issue remains, for some reason the coremod part of Dynamic Lights fails, which means there is another coremod also altering the same classes.

Does it work if you use just Minecraft, Forge and Dynamic Lights?

**Comment by Kylebartaous** [comment]
For a bit more info, then i use the vanilla mc w/ the vanilla launcher and connect to a server or a make and or go into a sp world it works, then i use my full mod pack connecting to server / going in to sp w/ out dyn lights it works all fine, then using mod pack + dyn lights connecting to server is a no go , and sp world crashes me (see crash log below), connecting to a server w/ just mc,forge, dyn light and or going in to a sp it crashes and logging into a server is a no go still. Doing some testing each time i tested w/ my full profile load out &  w/  the mod by it self, each time i ran the test and after i cleared out the logs,crash logs, sp save worlds, & dyn  light config to try hope-ing that resetting configs may fix it.


Test 1: running w/ ever thing i use with dyn lights

Logs:

[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018816/latest.log)

[betterfoliage.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018820/betterfoliage.log)


Crash Logs: ( was going to make a sp world so i could use the key bind f3+c to force the game to crash and give me a crash file log but seems then i tried making and joining a single player world to test something and got a crash via then that)

[crash-2018-05-18_17.53.38-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018850/crash-2018-05-18_17.53.38-server.txt)

[crash-2018-05-18_17.56.35-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018851/crash-2018-05-18_17.56.35-server.txt)



Test 2: running Everthing i use with out dyn lights

Logs;  


[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018883/latest.log)


[betterfoliage.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018884/betterfoliage.log)


[hs_err_pid10660.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018885/hs_err_pid10660.log)


Crash logs: None




Test 3: forge/ dyn lights own running profile


logs:


[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018887/latest.log)



Crash logs: 


[crash-2018-05-18_18.27.11-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2018889/crash-2018-05-18_18.27.11-server.txt)



SS of what i see trying to login http://prntscr.com/jjqk0m

SS of native mc launcher after it crashes from trying to create and go int o a sp world w/ only dyn lights in it own profile http://prntscr.com/jjqvc3

**Comment by AtomicStryker** [comment]
Ok i can reproduce, forge updates broke something in the coremod part. For the time being using an older forge should fix it, last version i ran was 2624

**Comment by Kylebartaous** [comment]
Yeah figures forge would be the cause , same thing happened  before  with  a different  mod. Figures  I update forge to the newest  then even I see it pop up. Thank you for the help.

**Comment by Kylebartaous** [comment]
Yeah figures forge would be the cause , same thing happened  before  with  a different  mod. Figures  I update forge to the newest  then even I see it pop up. Thank you for the help.

**Comment by AtomicStryker** [comment]
No thank YOU for properly reporting the bug with logs and information.

Do you know what proper reporting yields? UPDATES!!!

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/a7570e76b273128fb3194e32aec8b8df7b40f61c
