### ISSUE TITLE
Crash With Malisis Doors

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#205]
[crash-2018-05-25_17.50.58-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2039804/crash-2018-05-25_17.50.58-server.txt)
just reporting both sides, hope somebody helps for a fix for this issue. looks easy

**Comment by AtomicStryker** [comment]
net.malisis.doors.block.Door crashes when public void harvestBlock(World worldIn, EntityPlayer player, BlockPos pos, IBlockState state, @Nullable TileEntity te, ItemStack stack) is called on it by Multi Mine. That should be a valid call. Problem is with Malisis Door mod.
