### ISSUE TITLE
[Infernal Mobs] Released Mod File with source code

### ISSUE THREAD

**Issue by Mrkwtkr** [AtomicStryker/atomicstrykers-minecraft-mods#207]
![image](https://user-images.githubusercontent.com/6889122/41398842-3af285bc-6feb-11e8-9aa4-e549b35fabb3.png)
Found src.atomicstryker.infernalmobs in released file (InfernalMobs-1.12.2.jar) from [Curseforge](https://minecraft.curseforge.com/projects/atomicstrykers-infernal-mobs)
A mistake?

**Comment by AtomicStryker** [comment]
No, i package the source with the distribution. As history has shown already, code repositories do disappear (Google Code).
