### ISSUE TITLE
[feature request] Version number after mc_version

### ISSUE THREAD

**Issue by DanTheColoradan** [AtomicStryker/atomicstrykers-minecraft-mods#21]
We use PetBat mod 1.8. I'm never entirely sure that I have the latest version of your code though. Could you put a version number after 1.8? So perhaps 1.8-0.1.1, or something like that? Thanks :) We love the pet bat mod.

**Comment by AtomicStryker** [comment]
This would be too much of a hassle for my github binary repo and the hard links to the files - i basically rely on the filenames to not change across a single mc version.
