### ISSUE TITLE
Minions causing duplication with mined blocks

### ISSUE THREAD

**Issue by CloWnicide** [AtomicStryker/atomicstrykers-minecraft-mods#211]
Have tried two versions, the latest and the one right before that, and both are causing an issue with mined blocks randomly duplicating when they go to drop them.

[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/2152695/latest.log)

**Comment by AtomicStryker** [comment]
Mod blocks, right? There is an unfortunate interaction with those if they have custom drop behaviours. I would advise to add those blocks to the blacklist, only to realize Minions does not have one.

**Comment by CloWnicide** [comment]
It has the capability to do this to any block, vanilla or modded, that they mine up. It seems to fix itself as they pick up the drops off the floor themselves, but can cause massive fps drop and CTD.

**Comment by AtomicStryker** [comment]
... blocks they mine should never drop to ground, unless their inventories are full

**Comment by CloWnicide** [comment]
I'm literally watching them and when they mine blocks, theres a random chance of a block dropping, to which sometimes they pick up, other times I have to pick it up. They have a chest to store things in, that I clear out every few minutes, and they continue on until the job is done.

**Comment by CloWnicide** [comment]
https://imgur.com/ktQLv9M
