### ISSUE TITLE
[Simply Hax] Fall damage and outdated description (Missing Features?)

### ISSUE THREAD

**Issue by S0llux** [AtomicStryker/atomicstrykers-minecraft-mods#225]
You still take fall damage, any server, single player and not.

The description for the mod says there is a cave finder, but there's neither a config for it (description says there is one) and the default keybind I doesn't work either, so I'm asking if the features were removed or if they are just broken.

**Comment by AtomicStryker** [comment]
Description is outdated, yes. The render hack hasn't been in for several versions. But you do not specify a version of MC either.

**Comment by S0llux** [comment]
Oh sorry, my bad on that one. I'm using the latest version on CurseForge for 1.12.2

https://minecraft.curseforge.com/projects/simply-hax/files/2444017

Re-downloaded and single player nofall works now, will test later on servers. Sorry for posting an issue  without basic troubleshooting first.

**Comment by AtomicStryker** [comment]
Note the current implementation just tells the local player it has creative powers. It cannot override a remote server (you will be kicked when flying is disabled).
