### ISSUE TITLE
Possible inter-compat issue with ruins and possibly JEID

### ISSUE THREAD

**Issue by Sunconure11** [AtomicStryker/atomicstrykers-minecraft-mods#230]
https://paste.dimdev.org/dexoxotuqa.mccrash

Pinging some devs for more info on the crash.

@ZombieHDGaming @Robijnvogel @DShadowWolf

**Comment by dshadowwolf** [comment]
This crash points to an internal data structure apparently becoming null or having something such as net.minecraft.init.Blocks.AIR in it, though the point where the NPE happens is at access and not in generating the BlockState being asked for.

I have a fix in the MMD OreSpawn -dev builds that should, hopefully, fix this but I'm still not sure what is actually causing it.

**Comment by AtomicStryker** [comment]
Ruins just happens to be in this log and is very unlikely to have anything to do with it, please do an issue in the appropriate repo

**Comment by Robijnvogel** [comment]
@AtomicStryker The question is, can your mobs load/generate new chunks and is this exceptional behaviour or can basically all mobs do this?

**Comment by AtomicStryker** [comment]
Mobs? Ruins does not add any entities. It creates structures - which, in getting and setting world blocks across a template area, yes, do cause "cascading" worldgen.

**Comment by Robijnvogel** [comment]
Oh wait... This is an event you are subscribed to.
`atomicstryker.ruins.common.RuinsMod.onEntityEnteringChunk(RuinsMod.java:141)`

That changes the question:
Does Minecraft always load a new chunk when an entity enters a new chunk or does it only do so because ruins needs a Chunk object to handle certain stuff whenever this happens?

**Comment by AtomicStryker** [comment]
How is an entity supposed to enter a chunk that isn't loaded? If i had to guess this was some kind of teleport causing chunk-entering and worldgen. Chunks should generate LONG before a player gets near them.
