### ISSUE TITLE
ChestAttackedPacket modifies entity from Netty handler thread

### ISSUE THREAD

**Issue by Aaron1011** [AtomicStryker/atomicstrykers-minecraft-mods#235]
The [ChestAttackedPacket handler](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/601047ac669f4d94a4b7bca13d4a49b094303615/BattleTowers/src/main/java/atomicstryker/battletowers/common/network/ChestAttackedPacket.java#L47-L56) in BattleTowers interacts with entities from the Netty handler thread. Since none of the core Minecraft game objects are thread-safe, this could should be run on the main thread (via `MinecraftServer#addScheduledTask`).

**Comment by AtomicStryker** [comment]
Today i learned. Thanks for pointing that out https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/df08b0fe06b1d92fbff03c7a69ad222dd606d519
