### ISSUE TITLE
Submit a zh_CN translation

### ISSUE THREAD

**Issue by BreakshadowCN** [AtomicStryker/atomicstrykers-minecraft-mods#236]
Hi AtomicStryker, I'm doing a small translation of your Infernal Mobs (for 1.12.2 version) in Simplified Chinese (zh_CN).
(prefix and suffix are soooo hard to properly translated to Chinese so leave it as-is for now)

translation.infernalmobs:rareClass=稀有级
translation.infernalmobs:infernalClass=地狱级
translation.infernalmobs:ultraClass=超级

translation.infernalmobs:prefix.recurring= recurring 
translation.infernalmobs:prefix.undying= undying 
translation.infernalmobs:prefix.twinlived= twinlived 
translation.infernalmobs:prefix.witchkin= witchkin 
translation.infernalmobs:prefix.brewing= brewing 
translation.infernalmobs:prefix.singed= singed 
translation.infernalmobs:prefix.reckless= reckless 
translation.infernalmobs:prefix.raging= raging 
translation.infernalmobs:prefix.smashing= smashing 
translation.infernalmobs:prefix.thumping= thumping 
translation.infernalmobs:prefix.trolling= trolling 
translation.infernalmobs:prefix.byebye= byebye 
translation.infernalmobs:prefix.turtling= turtling 
translation.infernalmobs:prefix.defensive= defensive 
translation.infernalmobs:prefix.armoured= armoured 
translation.infernalmobs:prefix.stalking= stalking 
translation.infernalmobs:prefix.unseen= unseen 
translation.infernalmobs:prefix.hunting= hunting 
translation.infernalmobs:prefix.dark= dark 
translation.infernalmobs:prefix.shadowkin= shadowkin 
translation.infernalmobs:prefix.eclipsed= eclipsed 
translation.infernalmobs:prefix.enderborn= enderborn 
translation.infernalmobs:prefix.tricky= tricky 
translation.infernalmobs:prefix.exhausting= exhausting 
translation.infernalmobs:prefix.draining= draining 
translation.infernalmobs:prefix.burning= burning 
translation.infernalmobs:prefix.toasting= toasting 
translation.infernalmobs:prefix.bombing= bombing 
translation.infernalmobs:prefix.fireballsy= fireballsy 
translation.infernalmobs:prefix.repulsing= repulsing 
translation.infernalmobs:prefix.sproing= sproing 
translation.infernalmobs:prefix.vampiric= vampiric 
translation.infernalmobs:prefix.transfusing= transfusing 
translation.infernalmobs:prefix.bloodsucking= bloodsucking 
translation.infernalmobs:prefix.totallyzen= totally zen 
translation.infernalmobs:prefix.innerlypeaceful= innerly peaceful 
translation.infernalmobs:prefix.Ronin= Ronin 
translation.infernalmobs:prefix.poisonous= poisonous 
translation.infernalmobs:prefix.stinging= stinging 
translation.infernalmobs:prefix.despoiling= despoiling 
translation.infernalmobs:prefix.slowing= slowing 
translation.infernalmobs:prefix.Quicksand= Quicksand 
translation.infernalmobs:prefix.regenerating= regenerating 
translation.infernalmobs:prefix.healing= healing 
translation.infernalmobs:prefix.nighunkillable= nigh unkillable 
translation.infernalmobs:prefix.rusting= rusting 
translation.infernalmobs:prefix.decaying= decaying 
translation.infernalmobs:prefix.hungering= hungering 
translation.infernalmobs:prefix.starving= starving 
translation.infernalmobs:prefix.sprinting= sprinting 
translation.infernalmobs:prefix.swift= swift 
translation.infernalmobs:prefix.charging= charging 
translation.infernalmobs:prefix.thieving= thieving 
translation.infernalmobs:prefix.snagging= snagging 
translation.infernalmobs:prefix.quickfingered= quick fingered 
translation.infernalmobs:prefix.striking= striking 
translation.infernalmobs:prefix.thundering= thundering 
translation.infernalmobs:prefix.electrified= electrified 
translation.infernalmobs:prefix.thorned= thorned 
translation.infernalmobs:prefix.thorny= thorny 
translation.infernalmobs:prefix.spiky= spiky 
translation.infernalmobs:prefix.apathetic= apathetic 
translation.infernalmobs:prefix.deceiving= deceiving 
translation.infernalmobs:prefix.ensnaring= ensnaring 
translation.infernalmobs:prefix.webbing= webbing 
translation.infernalmobs:prefix.withering= withering 
translation.infernalmobs:prefix.Sith Lord= Sith Lord 
translation.infernalmobs:prefix.Dark Lord= Dark Lord 
translation.infernalmobs:prefix.Darth= Darth 

translation.infernalmobs:suffix.ofRecurrence= of Recurrence
translation.infernalmobs:suffix.theUndying= the Undying
translation.infernalmobs:suffix.oftwinLives= of twin Lives
translation.infernalmobs:suffix.theWitchkin= the Witchkin
translation.infernalmobs:suffix.theBrewmaster= the Brewmaster
translation.infernalmobs:suffix.theSinged= the Singed
translation.infernalmobs:suffix.ofRecklessness= of Recklessness
translation.infernalmobs:suffix.theRaging= the Raging
translation.infernalmobs:suffix.ofSmashing= of Smashing
translation.infernalmobs:suffix.ofMissionControl= of Mission Control
translation.infernalmobs:suffix.theNASA= the NASA
translation.infernalmobs:suffix.ofWEE= of WEEEEE
translation.infernalmobs:suffix.ofTurtling= of Turtling
translation.infernalmobs:suffix.theDefender= the Defender
translation.infernalmobs:suffix.ofeffingArmor= of effing Armor
translation.infernalmobs:suffix.ofStalking= of Stalking
translation.infernalmobs:suffix.theUnseen= the Unseen
translation.infernalmobs:suffix.thePredator= the Predator
translation.infernalmobs:suffix.ofDarkness= of Darkness
translation.infernalmobs:suffix.theShadow= the Shadow
translation.infernalmobs:suffix.theEclipse= the Eclipse
translation.infernalmobs:suffix.theEnderborn= the EnderBorn
translation.infernalmobs:suffix.theTrickster= the Trickster
translation.infernalmobs:suffix.ofFatigue= of Fatigue
translation.infernalmobs:suffix.theDrainer= the Drainer
translation.infernalmobs:suffix.ofConflagration= of Conflagration
translation.infernalmobs:suffix.thePhoenix= the Phoenix
translation.infernalmobs:suffix.ofCrispyness= of Crispyness
translation.infernalmobs:suffix.OMFGFIREBALLS= OMFGFIREBALLS
translation.infernalmobs:suffix.theBomber= the Bomber
translation.infernalmobs:suffix.ofBallsofFire= of Balls of Fire
translation.infernalmobs:suffix.ofRepulsion= of Repulsion
translation.infernalmobs:suffix.theFlipper= the Flipper
translation.infernalmobs:suffix.theVampire= the Vampire
translation.infernalmobs:suffix.ofTransfusion= of Transfusion
translation.infernalmobs:suffix.theBloodsucker= the Bloodsucker
translation.infernalmobs:suffix.theZenMaster= the Zen Master
translation.infernalmobs:suffix.ofEquilibrium= of Equilibrium
translation.infernalmobs:suffix.ofInnerPeace= of Inner Peace
translation.infernalmobs:suffix.ofVenom= of Venom
translation.infernalmobs:suffix.thedeadlyChalice= the Deadly Chalice
translation.infernalmobs:suffix.ofYouCantRun= of You-Cant-Run
translation.infernalmobs:suffix.theSlowingB= the slowing B****
translation.infernalmobs:suffix.ofWTFIMBA= of WTF Imba
translation.infernalmobs:suffix.theCancerous= the Cancerous
translation.infernalmobs:suffix.ofFirstAid= of First Aid
translation.infernalmobs:suffix.ofDecay= of Decay
translation.infernalmobs:suffix.theEquipmentHaunter= the Equipment Haunter
translation.infernalmobs:suffix.ofHunger= of Hunger
translation.infernalmobs:suffix.thePaleRider= the Pale Rider
translation.infernalmobs:suffix.ofBolting= of Bolting
translation.infernalmobs:suffix.theSwiftOne= the Swift One
translation.infernalmobs:suffix.ofbeinginyourFace= of being in your Face
translation.infernalmobs:suffix.ofSnagging= of Snagging
translation.infernalmobs:suffix.theQuickFingered= the Quick Fingered
translation.infernalmobs:suffix.ofPettyTheft= of Petty Theft
translation.infernalmobs:suffix.yoink= .. YOINK
translation.infernalmobs:suffix.ofLightning= of Lightning
translation.infernalmobs:suffix.theRaiden= the Raiden
translation.infernalmobs:suffix.ofRetribution= of Retribution
translation.infernalmobs:suffix.theThorned= the Thorned
translation.infernalmobs:suffix.ofStrikingBack= of Striking Back
translation.infernalmobs:suffix.ofStriking= of Striking
translation.infernalmobs:suffix.ofApathy= of Apathy
translation.infernalmobs:suffix.theDeceiver= the Deceiver
translation.infernalmobs:suffix.ofTraps= of Traps
translation.infernalmobs:suffix.theMutated= the Mutated
translation.infernalmobs:suffix.theSpider= the Spider
translation.infernalmobs:suffix.ofDarkSkulls= of Dark Skulls
translation.infernalmobs:suffix.Doomskull= Doomskull
translation.infernalmobs:suffix.ofBreathlessness= of Breathlessness
translation.infernalmobs:suffix.theAnaerobic= the Anaerobic
translation.infernalmobs:suffix.ofDeprivation= of Deprivation

translation.infernalmobs:mod.1UP=重生
translation.infernalmobs:mod.Alchemist=炼金
translation.infernalmobs:mod.Berserk=狂暴
translation.infernalmobs:mod.Blastoff=升空
translation.infernalmobs:mod.Bulwark=绝对防御
translation.infernalmobs:mod.Choke=窒息
translation.infernalmobs:mod.Cloaking=隐身
translation.infernalmobs:mod.Darkness=失明
translation.infernalmobs:mod.Ender=瞬移
translation.infernalmobs:mod.Exhaust=空虚
translation.infernalmobs:mod.Fiery=灼热
translation.infernalmobs:mod.Ghastly=火球
translation.infernalmobs:mod.Gravity=重力
translation.infernalmobs:mod.LifeSteal=吸血
translation.infernalmobs:mod.Ninja=忍者
translation.infernalmobs:mod.Poisonous=有毒
translation.infernalmobs:mod.Quicksand=流沙
translation.infernalmobs:mod.Regen=再生
translation.infernalmobs:mod.Rust=生锈
translation.infernalmobs:mod.Sapper=摄元
translation.infernalmobs:mod.Sprint=冲锋
translation.infernalmobs:mod.Sticky=粘性
translation.infernalmobs:mod.Storm=风暴
translation.infernalmobs:mod.Vengeance=复仇
translation.infernalmobs:mod.Weakness=虚弱
translation.infernalmobs:mod.Webber=织网
translation.infernalmobs:mod.Wither=凋零

translation.infernalmobs:entity.Creeper=爬行者
translation.infernalmobs:entity.Zombie=僵尸
translation.infernalmobs:entity.Skeleton=骷髅
translation.infernalmobs:entity.Spider=蜘蛛
translation.infernalmobs:entity.Enderman=末影人

**Comment by MentalMouse** [comment]
For the prefixes and suffixes, I'd say you can reasonably give up on exact translations, and just pick "Chinese names" for them that give the right flavor, and/or seem to "go with" that ability/power.

**Comment by AtomicStryker** [comment]
Figuring out how to get this copy pasted without breaking encoding was fun
not
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/05bec35706a68e99715c302b62f01c51898a2ed7
