### ISSUE TITLE
I'm Sorry :\

### ISSUE THREAD

**Issue by DrZed** [AtomicStryker/atomicstrykers-minecraft-mods#24]
http://puu.sh/kiS1l.txt
http://bt.industrial-craft.net/view.php?id=1726
I wish I could report friendly, but this was just the essence of pure stupidity bottled up into 2 lines of code... Could you be as so kind as to tell me why you have this here? Or was this on a whim?

ModAdvancedMachines.java:106-107
Recipes.macerator.addRecipe(new IdentRecipe(new ItemStack(Blocks.netherrack)), new NBTTagCompound(), new ItemStack(Blocks.netherrack));
Recipes.macerator.addRecipe(new IdentRecipe(new ItemStack(Blocks.quartz_ore)), new NBTTagCompound(), new ItemStack(Blocks.quartz_ore));

I know I could PR, or ASM remove it, or remove from the recipe list (I did in latest version of my mod) but still... Don't do this again without a valid reason...

https://github.com/HxCKDMS/HxCWorldGen/blob/master/src/main/java/HxCKDMS/HxCWorldGen/ModSupport/IC2Support.java#L37

:P

~DrZed
    Provoking people since 2015

I'm Sorry :\

**Comment by Chocohead** [comment]
Maybe something to do with this as a guess? https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.7.10/AdvancedMachinesAS/src/main/java/atomicstryker/ic2/advancedmachines/TileEntityAdvancedMacerator.java#L189-L202

**Comment by AtomicStryker** [comment]
For the record, i still haven't figured out what IC2 means by ambiguous recipe. These ItemStacks describe one item and one item only

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/7eb52de056a07a29a4dc959b87a6eca713281d9c

HAHAHAHAHAHAAHAH

**Comment by DrZed** [comment]
Fine you have a legit-ish reason to have it... Why not have a seperate list for your recipes meant for your block? Read from 2 lists, I know it's inefficient but it seems better imo?
Sorry for provoking you...

**Comment by AtomicStryker** [comment]
Then i'd have to reimplement and support something IC2 code can do for me. I choose letting others do work for me.

**Comment by DrZed** [comment]
Stryker here's a thought, How about netherrack -> NetherDust 
NetherDust > washer > sulfur/stonedust/glowstone?
Since the nether is slightly bright it can make a little sense.
Low chance for glowstone or tiny piles of glowstone?

**Comment by AtomicStryker** [comment]
Trash to valuables is never a good recipe

**Comment by DrZed** [comment]
k... Then what's with your recipe redstone + netherrack = glowstone in the macerator?
