### ISSUE TITLE
[Feature request] [Ruins] ForceSpawn on top of the Nether

### ISSUE THREAD

**Issue by drakray** [AtomicStryker/atomicstrykers-minecraft-mods#241]
As stated in title, could it be possible to have a way to spawn Ruins on top of bedrock with commands? because as of now, using /testruin "sink" the ruin in the bedrock, and I'd love to be able to spawn some over-the-nether ruins
Please pretty please :D
(it might also just not be possible since Nether is "128 block high", even though we CAN build over it :/ )

**Comment by AtomicStryker** [comment]
Dealt with as part of the referenced pull request, i hope
