### ISSUE TITLE
[Question][Ruins] AutoGen at coord on WorldGen

### ISSUE THREAD

**Issue by drakray** [AtomicStryker/atomicstrykers-minecraft-mods#245]
Is there a way to forceSpawn a Ruins on world/dimension gen, for every world?

For exemple, I made a "Spawn" ruin, and I'd like it to autoGen on every world I create at 0,63,0 without command, or a "Space Station" to gen in DIM1 at 0,63,-512 - would that be possible?

Thanks

**Comment by QuarterAnimal** [comment]
Within Ruins, no. I'm not even sure that'd be desirable in general, given there's no way to know a priori what the altitude, terrain, or biome is at those coordinates.

If you really need that capability and don't want to place ruins manually, you could make a datapack function that **/testruin**s particular templates at particular coordinates on the first tick of the game, then deactivates itself. That's probably the best way to have specific, predefined, one-time ruins. You may also want to **/setworldspawn** in that function, too, to make sure folks start there.

I _could_ see general utility in allowing a template to be designated as unique (i.e., only spawned once per world) or limiting the number of occurrences. I can also see restricting a template to certain dimensions (though that might be problematic, as the association between dimension IDs and what they represent isn't guaranteed). But fixed locations...while it's certainly possible to code, unless AtomicStryker gives the go-ahead on such a feature, I can't recommend adding it to Ruins. My advice is to use a datapack.

**Comment by drakray** [comment]
That is in fact a simple yet probably effective way to do what I want, thanks! :D
Now, I just need to find how to do that XD

**Comment by drakray** [comment]
Well, I just checked, and DataPack are only for 1.13 and up, and I wanted that for 1.12.2(Ruins version), so back to starting point :(

**Comment by QuarterAnimal** [comment]
...except I've been spending some time in Minecraft 1.13 for a while lately, and I forgot datapacks aren't available in 1.12. Okay, then--same deal, but **/gamerule gameLoopFunction** for 1.12.
