### ISSUE TITLE
FoxGuard block break issue

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#246]
Hello!
I use the newest version of MultiMine and FoxGuard protection plugin (for SpongeForge server).

When I setup protection to deny block breaking it works only in creative (when MultiMine isn't used).
Players with gamemode 0 can destroy protected spawn blocks because Multimine (i think) overrides block-break event or something.

I know that this is more FoxGuard bug but because it is related to MultiMine I want to report it here first.

Thanks for any help and of course for maintaining this project (My friends like this mod). 
PS. Sorry if my English is bad.

**Comment by AtomicStryker** [comment]
It's a FoxGuard bug in that it likely does not use the Forge event API  for block breaking permissions. Multimine is a Forge Mod and uses the Forge "BlockEvent.BreakEvent" to give other mods the opportunity to tell it "no". FoxGuard needs to use that API to make MultiMine respect its authority.

**Comment by ghost** [comment]
Ok thanks for detailed info - I will report this bug to FoxGuard developer.
