### ISSUE TITLE
Ruins Mod only generating features when chunk load initiated by player

### ISSUE THREAD

**Issue by Slind14** [AtomicStryker/atomicstrykers-minecraft-mods#25]
Hey,

I have been trying to pre-generate a world. Using a mod that loads one chunk after another until a defined area is completed. (AdminCommandToolBox, Wireless Turtle, CommandBlock) All chunks generated by those techniques are missing the ruins world gen features which chunks generated by a player have.
When using cofh for worldgen features it works just fine. 

I would appreciate it if this could be looked into and hopefully solved, as modpacks with a lot of world gen features have super slow world generation, where your game is literally freezing when you walk into undiscovered areas.

**Comment by AtomicStryker** [comment]
Ruins uses the FML worldgen API. If your chunkwise approach isn't triggering the forwards, i would suggest you fix your approach.

**Comment by Slind14** [comment]
Do you have any idea why this might be happening. I mean it's reproduce-able with a vanilla command block.

**Comment by AtomicStryker** [comment]
Again, ask FML, not me. I am sitting at the end of the pipeline. Any pipeline queries are to be directed elsewhere

**Comment by GunArm** [comment]
Slind14 if you happen to be using linux to run your server you could pregen your world with this script I wrote https://github.com/GunArm/MC-AutoGen/blob/master/autogen.sh

I wrote/use it for exploring lots of land to balance the weightings and spacing of ruins.

**Comment by Slind14** [comment]
nice thanks @GunArm
