### ISSUE TITLE
No needles show up in the compass

### ISSUE THREAD

**Issue by Gabirel** [AtomicStryker/atomicstrykers-minecraft-mods#250]
Minecraft version: `1.7.10`
FML version: `v7.10.99.99`
Forge version: `10.13.4.1614`

-------
As you can see it from the pic.
![image](https://user-images.githubusercontent.com/12933851/51541736-8e208600-1e94-11e9-89de-d7dcd905b00d.png)

So~~ How can I solve it by myself? Can I do that? If not, could it be fixed?

**Comment by AtomicStryker** [comment]
I don't know. Finder Compass, in that version, overwrites the compass item renderer. Mind you, the same class does inventory- and inhand-rendering, so why one would work but not the other...

The only assumption i can offer is that you have some other mod which maybe overrides the entire GUI and/or handheld items.

**Comment by Gabirel** [comment]
Yes, I do have a texture pack which overrides the entire GUI. 

But I really like the current texture pack I'm using. Is there a way to set the priority of compass rendering from the mod over the texture pack's rendering?

**Comment by AtomicStryker** [comment]
Texture packs would not cause this phenomenon. It really would have to be another mod doing its own rendering. For instance, the minimap mod visible.

**Comment by Gabirel** [comment]
I disabled the minimap mod. But it still doesn't show up. I really couldn't know which one is causing the issue. So, if I can't set the rendering priority, I  will close this issue first.
