### ISSUE TITLE
BattleTowers Loot Table limit.

### ISSUE THREAD

**Issue by SlayerTheChikken** [AtomicStryker/atomicstrykers-minecraft-mods#253]
Anything past 16 items for one floor doesn't register, as in even if you make the first 16 items 0 percent, and the 17th 100 percent it still doesn't spawn the item or any item after 16. I'm doing this test in my modpack Tekxit 3 in-case you want a test environment, I did try different items as well.

Edit: I'm going to keep seeing different ways to maybe get it work, and check the logs soon as well..

**Comment by SlayerTheChikken** [comment]
Okay so changing S:"Item Generations per Floor"= to 99 allows up to 24 items to spawn in chests at once (so the max amount of items has increased from 16 to 24 INSIDE THE CHEST at one), it also allows items to spawn past item 16 so for example item number 17 can spawn now..

I'm still almost certain this is a bug, unless that setting was meant to limit the max amount of items you can have on the loot table.

**Comment by AtomicStryker** [comment]
No, it's poor implementation on my part, where floor count and item index are linked. Thanks for pointing it out. TowerStageItemManager needs to be rewritten. I'd argue you can avoid the issue for now by not stuffing your config files so much?
There won't be an ETA for a fix. What little time i put into mc coding goes towards the 1.13 update, which is exhaustive to say the least.

**Comment by SlayerTheChikken** [comment]
Changing it to 99 made it work well enough for my use, TKX is a big modpack so a small loot table wouldn't have worked :P 

Thank you for the quick response! May your 1.13 migration go smooth and your headaches be small.

**Comment by Shivaxi** [comment]
Ah I was just about to report this myself.  What does the ItemGenerationsPerFloor actually do?  is it safe setting that to 99?  Or is that gonna throw the delicate balance of my loot all over the place?  What about going higher than 99?

**Comment by Shivaxi** [comment]
so i set     S:"Item Generations per Floor"=999   and i can spawn more than 24 items haha, i guess that'll work for now :P  I just need to re-adjust all my chances

**Comment by AtomicStryker** [comment]
If you'd like to try something still, i have this version here with code changes https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/273#issuecomment-510553458

It contains a Item manager rewrite, which i did not test

**Comment by SlayerTheChikken** [comment]
@AtomicStryker Ill give this a shot soon-ish.. Thank you for the update..

Hopefully the listings werent re-written TOO much, or I'll have to redo the thousands of items added to battletowers ;P That's not on you though obviously haha
