### ISSUE TITLE
Dynamic Lights [1.13.2]

### ISSUE THREAD

**Issue by ThexXTURBOXx** [AtomicStryker/atomicstrykers-minecraft-mods#255]
https://hastebin.com/sizimukani.coffeescript
Minecraft crashes when jumping into water (I don't know the exact circumstances for this crash unfortunately)

**Comment by AtomicStryker** [comment]
Thanks for reporting it. Unfortunately i cant build and release a fixed version because the RiftMod for 1.13s authors site, which the compilation depends on, is a shit heap and offline more often than not.

**Comment by ThexXTURBOXx** [comment]
Okay, thank you for trying though!
Do you mean jitpack.io as the website, that is offline so often? If yes, you can change that by depending a specific version of Rift and not on the master-SNAPSHOT e.g.

**Comment by AtomicStryker** [comment]
Yes. But it's way worse than offline - if it was offline the gradle build would just use the cached version on my PC. It reports as online but fails when trying to download the jitpack dependency.

It managed to build now:
https://minecraft.curseforge.com/projects/dynamic-lights/files/2692407

**Comment by ThexXTURBOXx** [comment]
Perfect, thank you for fixing it!
Yeah, jitpack is a huge pain in the ass...
