### ISSUE TITLE
Ruins not generating in Dimension 10

### ISSUE THREAD

**Issue by MokahTGS** [AtomicStryker/atomicstrykers-minecraft-mods#256]
I need help.  I'm trying to get a structure I made with the parser to spawn in the Beneath dimension and it is not working.  Anyone else have any success getting structures to spawn in a particular dimension?

This is the file the parser made: https://pastebin.com/Djs0gPkL

I have the dimension listed in that file and it is in the Beneath folder in the ruins config folder.  Not sure what is wrong.

**Comment by AtomicStryker** [comment]
Please ask in the thread, i am not a support hotline.
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1282339-1-13-2-ruins-structure-spawning-system

From a glance, you have mistakenly edited the "dimensions" entry to "10", believing it to be "dimensionsToSpawnIn". It is not.

**Comment by MokahTGS** [comment]
What should I believe it to be?  dimensionsToSpawnIn=10 doesn't seem to work either.

**Comment by CalaMariGold** [comment]
Would just like to say that Ruins spawning in the Beneath still don't work and it would be great if there was a fix for it. The problem is that Ruins spawn anywhere, even inside of walls and completely replace entire sections of stone.
