### ISSUE TITLE
template not rotating

### ISSUE THREAD

**Issue by icecloud80** [AtomicStryker/atomicstrykers-minecraft-mods#258]
on 1.13.2 version, I have a template that no matter how i testruin it, it is facing the same direction.. I tried to change the setting and it didnt work

**Comment by AtomicStryker** [comment]
testruin does not rotate templates by itself randomly. If you want to test rotation, you need to put it in the call parameters... 

/testruin template x y z rotation
example:
/testruin templateparser/test 20 _ 40 1

_ for y means it will auto-adjust height to terrain, and rotation 1 is EAST, eg one quarter rotation clockwise.

**Comment by icecloud80** [comment]
thanks it works
