### ISSUE TITLE
Annoying Bubbles Stay Forever (even if i die) 1.12.2

### ISSUE THREAD

**Issue by KenyMylankca** [AtomicStryker/atomicstrykers-minecraft-mods#260]
![ass](https://user-images.githubusercontent.com/41585837/57164676-8d857d00-6dfd-11e9-843d-7db5be3aa2d8.PNG)
please help this. thanks.
what happened:
just an infernal mob attacked to me, i killed it, but those bubbles stay forever. even after i die, they still there. i removed player dat files from my save files (worth of losing my items) THEN they gone. 
so at least make a cooldown or something for them... they shouldn't stay forever

**Comment by KenyMylankca** [comment]
using latest forge

**Comment by katubug** [comment]
This is also happening to one of my players.

**Comment by AtomicStryker** [comment]
Pushed bugfix https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/7aad1c0897d4f14389455807e7864f5f4ca956d4

**Comment by AtomicStryker** [comment]
Bugfixed version is now on curse and on my website.

**Comment by KenyMylankca** [comment]
the file named InfernalMobs-1.12.1 btw
