### ISSUE TITLE
[Infernal Mobs] Crash upon killing an Infernal Zombie

### ISSUE THREAD

**Issue by katubug** [AtomicStryker/atomicstrykers-minecraft-mods#264]
An Infernal Zombie spawned inside a Roguelike Dungeon, and one of my players killed it. As soon as it died, the entire server crashed.

Here's the report: https://pastebin.com/AS20ihJF

InfernalMobs Version: 1.7.6 according to changelog
Forge Version: forge-1.12.2-14.23.5.2838-universal

**Comment by AtomicStryker** [comment]
The crash is not related to Infernal Mobs in a way that i could see. From what i can trace, for some reason this EntityZombie registers as "EntityTameable" (this is not vanilla and must be the work of a different mod, a coremod even) which makes vanilla code run into the above error.

More technically:
In EntityAIHurtByTarget#alertOthers
the expression
"!entitycreature.isOnSameTeam(this.taskOwner.getRevengeTarget())"
with entitycreature being a different EntityZombie (which for some reason is an EntityTameable) and taskOwner being the attacked EntityZombie. Now, the implementation of Entity.isOnSameTeam relies on the parameter to not be null, however EntityZombie always returns null for getRevengeTarget()

**Comment by katubug** [comment]
Thank you very much for laying that all out for me. I'll look into my
modlist and see if there's anything that tames hostile mobs, that might be
the culprit.

Thanks!
