### ISSUE TITLE
The torch on head goes out sometimes

### ISSUE THREAD

**Issue by EfficiencyVI** [AtomicStryker/atomicstrykers-minecraft-mods#27]
Hi,

we have one smaller problem with the Dynamic Lights mod. Every few seconds the light turns out. You can see this a few times here http://www.twitch.tv/fate78/v/18223719?t=30m0s.

Is there any way to make it more accurate or do you have an idea why this happens?

We use the latest version of dynamic lights and OptiFine_1.7.10_HD_C1.jar

// To reproduce this error, create a new world, go to creative, get a torch, dig a few blocks down and place a block above your head so it is dark, then just dig down. The lights will go out on every second block.

**Comment by AtomicStryker** [comment]
Likely Optifine interaction. Have you checked without

**Comment by EfficiencyVI** [comment]
I tried it without and it is exactly the same. I also tried it with just the torch in my hand and I tried to deactivate the hardcore darkness option in RandomThings. Still the same. :-(

**Comment by AtomicStryker** [comment]
Ok ive glanced at the video and it looks very much likey another mod is interfering.

**Comment by EfficiencyVI** [comment]
So I removed all the mods and added them one by one again. The problem is fastcraft (http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820). When I remove the mod the blackouts stop.

Fastcraft has only two options to change and non of them affects the behaviour. Any suggestions?

**Comment by AtomicStryker** [comment]
Ask fastcraft's dev, i dont have the first idea of what it does

**Comment by Player3324** [comment]
The base edit is simply incompatible, I'll have to detect and integrate it.

**Comment by EfficiencyVI** [comment]
Thank you @sfPlayer1. Bug report was added to http://forum.industrial-craft.net/index.php?page=Thread&postID=194040#post194040 (FYI)

**Comment by Player3324** [comment]
Any chance you could split

```
int getLightValue(IBlockAccess world, Block block, int x, int y, int z)
```

into 2 methods with the second being

```
int getLightValue(IBlockAccess world, Block block, int x, int y, int z, int vanillaValue)
```

with the getLightValue query isolated to the first? I'm talking about the 1.7 branch of course. I'd prefer to do the "raw" light value lookup myself as I can do it faster.

**Comment by AtomicStryker** [comment]
I would prefer you asm transform the first line in DynamicLights.getLightValue which currently is int vanillaValue = block.getLightValue(world, x, y, z); into whatever you desire.

**Comment by EfficiencyVI** [comment]
Hm, how is the problem fixed? :-)

**Comment by AtomicStryker** [comment]
By virtue of not being my problem
