### ISSUE TITLE
[1.14.3] Suggestion: Add support for more structures for Finder Compass

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#274]
Hey, I found some more structures that can be used with `findNearestStructure` (see https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/22fc6e7/FinderCompass/src/main/java/atomicstryker/findercompass/common/network/StrongholdPacket.java#L68)

Here's an enum class that lists all of the possible structures (AFAIK):

```java
public enum StructureType {
    PILLAGER_OUTPOST("Pillager_Outpost"),
    MINESHAFT("Mineshaft"),
    MANSION("Mansion"),
    JUNGLE_PYRAMID("Jungle_Pyramid"),
    DESERT_PYRAMID("Desert_Pyramid"),
    IGLOO("Igloo"),
    SHIPWRECK("Shipwreck"),
    SWAMP_HUT("Swamp_Hut"),
    STRONGHOLD("Stronghold"),
    MONUMENT("Monument"),
    OCEAN_RUIN("Ocean_Ruin"),
    FORTRESS("Fortress"),
    ENDCITY("EndCity"),
    BURIED_TREASURE("Buried_Treasure"),
    VILLAGE("Village");

    private final String name;

    StructureType(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
```

PS: I found these on 1.14.3, but I'm guessing they're _probably_ also on 1.13.

PPS: I wrote the class, it's not a vanilla class. (I think) So feel free to paste it into Finder Compass.

**Comment by AtomicStryker** [comment]
I could arguably implement a generic system instead of the Stronghold needle that accepts this ID as input instead. Question is, is searching for those structures going to be costly?

**Comment by ghost** [comment]
Good question. My guess is that the cost will be the same if the same radius (i.e. `STRONGHOLD_SEARCH_RADIUS`) is used.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/1f8421602a3b9fce7dc78c3ed3443f2a86829e12 Your wish has been granted. Best delete or move your config and let it generate once, so you can see the new feature needles (one per setting).

**Comment by AtomicStryker** [comment]
This build was pushed to curse

**Comment by AtomicStryker** [comment]
Did not forget you asked for 1.14.3: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/f83f4badb14148ce15943a09948791b4b095a6f6

**Comment by ghost** [comment]
Thank you so much!
