### ISSUE TITLE
[FinderCompass][1.14.3] Config file is not created in Linux

### ISSUE THREAD

**Issue by kuzmas** [AtomicStryker/atomicstrykers-minecraft-mods#275]
In https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.14.3/FinderCompass/src/main/java/atomicstryker/findercompass/common/FinderCompassMod.java, function `public void preInit(FMLCommonSetupEvent evt)`, line 62:

The string containing path to the config file contains hardcoded "\\" which does not work on Linux.

Possible solution: replace `"\\config\\findercompass.cfg"` with `File.separator + "config" + File.separator + "findercompass.cfg"`

**Comment by AtomicStryker** [comment]
Done. Thanks for reporting
