### ISSUE TITLE
[1.14.3] Finders compass sidedness issue on dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [AtomicStryker/atomicstrykers-minecraft-mods#276]
https://gist.github.com/ProsperCraft/08862dc93b12c3b8df19e951fe523546

**Comment by AtomicStryker** [comment]
Fixed in https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/ac20267fcad02292da07aac92ca5653b31bf0473, also pushed to curse
