### ISSUE TITLE
[1.14.3] Ruins crash - IllegalStateException: TickNextTick list out of synch

### ISSUE THREAD

**Issue by ProsperCraft** [AtomicStryker/atomicstrykers-minecraft-mods#277]
We are having this quite a bit now that we have added templates which are found in my The Adventures of halk pack -
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

Reproduced with only ruins and forge-
https://gist.github.com/ProsperCraft/6ade5a1c2b97533ef837117a3e2463bb

Log -
https://gist.github.com/ProsperCraft/2799326e6256620509a2d28b650c5a3b

server crash with full pack - 
https://paste.fedoraproject.org/paste/ayx9xiz3HDsTE2TYj8kC~w

**Comment by AtomicStryker** [comment]
OK. It's probably because chunk generation is async now, and Ruins altering the world at an unexpected point in time ... i do have something i could try to fix it.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/bb1afbfc2deea63a8fc5cc5dff108929da5af50e in a short test on a dedicated server with the templates you linked, it spawned a couple of them and didn't crash.

**Comment by ProsperCraft** [comment]
Seems to have cleared it up :)
