### ISSUE TITLE
Problems versioning on the Twitch launcher due to lack of file name version numbers.

### ISSUE THREAD

**Issue by ProsperCraft** [AtomicStryker/atomicstrykers-minecraft-mods#278]
I suspect to fix the versions in the twitch launcher it will require putting version numbers in the file number I suspect.

They all show up like this-

![c50e1e9b9b1794ed10ff72f027ddbacf](https://user-images.githubusercontent.com/4427684/61549221-bc7aba80-aa0c-11e9-8530-7291b0f7e4f7.png)

The problem is, you can't tell which one you have installed, or if there is an update to the one you have.

A changelog would be a blessing as well :)

**Comment by ProsperCraft** [comment]
This is what it should look like -
![b2a2647cf66269d49116d058bd8ec19b](https://user-images.githubusercontent.com/4427684/61549411-2abf7d00-aa0d-11e9-8cb0-1c5106f3e74d.png)

**Comment by AtomicStryker** [comment]
I will consider it. But as this requires effort on my part, i hesitate.

**Comment by AtomicStryker** [comment]
1.14. files have versioning now
