### ISSUE TITLE
Dynmapic lights: Add custom entities light source via IMC

### ISSUE THREAD

**Issue by liach** [AtomicStryker/atomicstrykers-minecraft-mods#28]
Currently there's no way to add new entity or armor light sources. It will be helpful if you could add some imc hooks which allow other mods to register some entity/armor light sources by entity name or item id. If you do not want to implement this I can make a pr for you.

**Comment by AtomicStryker** [comment]
What exactly are you asking for? Armor can be added to the PlayerSelfLight module, which also support FMLInterModComms commands to turn the player light on and off. EntityClassLightSource allows to make entire entity classes shine light, configurable by config.

**Comment by liach** [comment]
I want to add default entity light source in mods. It may not be such a good idea to override the config directly, I think.

**Comment by AtomicStryker** [comment]
That is exactly what configs are for. I still do not understand.

**Comment by liach** [comment]
Sorry. I mean I want to add default light source from my mod, which do not need users to change configuration to add. It might be applicable to change the configuration just by the mod if you insist to ask me to do this.

**Comment by AtomicStryker** [comment]
If you want custom light sources through dynamic lights, it is almost trivial to copy one of dynamic lights modules and just use my mod as library.

**Comment by liach** [comment]
Good idea. Thanks.
