### ISSUE TITLE
log spam with battle towers (FlushCurrentPosListToFile:427)

### ISSUE THREAD

**Issue by mattrix444** [AtomicStryker/atomicstrykers-minecraft-mods#280]
hi my worlds keep getting to the stage after about 20 mins of playing where my client will start to freeze every 5-10 seconds and my log is full with [atomicstryker.battletowers.common.WorldGenHandler:flushCurrentPosListToFile:427]
java.io.FileNotFoundException: C:\Users\matty5ps\Documents\Curse\Minecraft\Instances\mattpack444\saves\holking\BattletowerPositionsFile.txt (The system cannot find the path specified) etc etc

**Comment by mattrix444** [comment]
upon further inspection it would seem that the spam starts when ive died in a hardcore world ( i only play in hardcore so not sure about normal) and i delete the world and make a new one it starts crying about the file not existing.

**Comment by AtomicStryker** [comment]
Can you try creating the file by hand? Is there anything that would block the java process from creating the file?
