### ISSUE TITLE
Some modifiers cause server to crash when interacting with the spiky trait from TiCon

### ISSUE THREAD

**Issue by Bleggman** [AtomicStryker/atomicstrykers-minecraft-mods#281]
i had thought i fixed the issue myself before by disabling the vengeance trait, which was causing it the first time i encountered this, though it happened again after i disabled that trait. not sure which modifier might be causing the issue this time. maybe i dont even know what is causing the issue and it is something different, though it mentions your mod and the spiky trait from ticon, so here is the crash log
[crash-2019-07-28_00.31.42-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/3439770/crash-2019-07-28_00.31.42-server.txt)

**Comment by AtomicStryker** [comment]
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:89)
	at slimeknights.tconstruct.library.modifiers.Modifier.attackEntitySecondary(Modifier.java:280)

Barking up the wrong tree, bring this to ... slime knights?

**Comment by Bleggman** [comment]
alright. i saw in another thread the vengeance mod was indeed causing issues with the spiky trait, though i think i found the scenario that triggers my crash, and it seems to be on the tinkers construct end. reflecting a tipped arrow with a cactus battlesign in my offhand causes it. will take the issue to slimeknights, thanks. i think the reason it was referencing your mod is because some infernal skeleton is the one shooting tipped arrows

**Comment by SlayerTheChikken** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/3781
