### ISSUE TITLE
[1.14.4] no structures are spawning

### ISSUE THREAD

**Issue by matt225022** [AtomicStryker/atomicstrykers-minecraft-mods#283]
When I generated a ruins world in 1.14.4 no structures spawned

**Comment by AtomicStryker** [comment]
The Ruins mod does currently not contain any templates by default.

**Comment by LlubNek** [comment]
ruins-1.14.4.1.jar, distributed through curseforge, contains the ruins_config folder, which has templates in it.  However, it is never moved into place automatically.  "Where to put this.txt" suggests placing the ruins_config folder in .minecraft/config/ though, and previous versions of the mod placed it in the mods folder.

Issue #284 might be preventing structures spawning as well, since preserveBlock is rather common.

**Comment by LlubNek** [comment]
readme.txt also suggests putting templates in biome named subfolders of mods/resources/ruins...

**Comment by AtomicStryker** [comment]
Oh, those files being included is a bug. I neglected to delete them from the repository and the build script bundled them ... but they are not valid for Minecraft 1.13 or 1.14

**Comment by IchigoGames** [comment]
is there a fix for this ?

**Comment by AtomicStryker** [comment]
Yes. Create your own templates for 1.14 or obtain some from somewhere.

**Comment by IchigoGames** [comment]
ya i dont think ill be making my own but found one for 1.12 and try putting it in but no luck is there any for 1.14 or some info out there.

**Comment by katubug** [comment]
> Oh, those files being included is a bug. I neglected to delete them from the repository and the build script bundled them ... but they are not valid for Minecraft 1.13 or 1.14

Does this mean some are meant to be included with the 1.12.2 version? All the biome folders I've found in ruins_config are empty. If there's not meant to be any templates, that's fine, I don't mind making my own things. I was simply curious if there were some that I was missing. :)

**Comment by AtomicStryker** [comment]
Prior to 1.13 there was a default set of templates, yes. It is only copied to your "templates" folder if it doesnt exist.

**Comment by IchigoGames** [comment]
tho if you try that with templates from 1.12 it will give you invite templates on all of them
