### ISSUE TITLE
[Ruins 1.14.4] Templates containing the rule 'preserveBlock' will not spawn.

### ISSUE THREAD

**Issue by ssloan302** [AtomicStryker/atomicstrykers-minecraft-mods#284]
In the newest Ruins version (1.14.4.1) Templates that contain the rule 'preserveBlock' will not spawn correctly. 

Attempting to spawn these templates with the /testruin command results in the chat message "EventRuinTemplateSpawn returned as canceled, not building that."

![2019-08-26_18 27 08](https://user-images.githubusercontent.com/53919323/63734074-afcd5b80-c82f-11e9-90cb-d62ae6b8c719.png)

If the template is generated naturally it will result in large air pockets where the structure should be.

![2019-08-26_18 29 24](https://user-images.githubusercontent.com/53919323/63734042-8dd3d900-c82f-11e9-91b1-b448910f570a.png)

I tested this issue on templates made by well-known creators like Gillymoth & Jordan_Peacock and the issue still shows up. Templates without this rule generate fine

**Comment by IchigoGames** [comment]
yes even with downloaded templates this still does not  work

**Comment by AtomicStryker** [comment]
I doubt the templates you were trying to use were compatible with 1.13/1.14. The format has changed. You need to re-parse older structures if you want them as templates.

**Comment by oneshotaccount** [comment]
@AtomicStryker 
For those wondering how to do so, how does one re-parse the old structures?

**Comment by AtomicStryker** [comment]
Basically spawn them in a compatible version of MC/Ruins, load the savegame in current MC/Ruins, place baseplate of blocks (see template parser tutorial), parse, edit template file to taste.
