### ISSUE TITLE
[1.12.2] [InfernalMobs 1.7.6] Mob gains 4 HP on every save load

### ISSUE THREAD

**Issue by scearcrovv** [AtomicStryker/atomicstrykers-minecraft-mods#285]
### Description
Every time the save game is loaded, a mob gains 4 max HP.

The specific one is a Baby Zombie with now 61 HP and the following modifiers:
1UP, Berserk, Bulwark, Fiery, Regen, Rust, Sprint, Sticky, Strom, Vengeance, Webber

### Versions
minecraft@1.12.2, FML@8.0.99.99, forge@14.23.5.2836, mcp@9.42, infernalmobs@1.7.6, waila@1.8.26, jei@4.15.0.289

InfernalMobs was compiled from an up-to-date (d5b4d541) fork of the source.

**Comment by AtomicStryker** [comment]
Likely a side effect of MC changes. The code for the "max health hack" stems from a time when max health was not persisted per-entity, but MC might do that now. So every time Infernal Mobs "hacks" a newly loaded or spawned entity, the max health extension happens again.

**Comment by scearcrovv** [comment]
That's interesting. Is there anything we can do? I mean, it's a really small bug that I only noticed because I reloaded this particular savegame so many times.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/2de37e82ed68d3cc0ba72b66ef145d65c38038ec

Its fixed in the current version atleast
