### ISSUE TITLE
No more Magic Yarn?

### ISSUE THREAD

**Issue by fuzzyweapon** [AtomicStryker/atomicstrykers-minecraft-mods#287]
Apologies for using issues to ask this question, but the forums and curse forge boards are ghost towns.

Was Magic Yarn abandoned for newer versions?  Just picked up Minecraft again after a long hiatus and this was one of my favorite mods.  Is there any possibility of bringing it back?

**Comment by AtomicStryker** [comment]
Probobly no. Porting mods between versions of forge and MC is a lot of work and i've reduced my effort to keeping my most popular (and easiest to maintain) mods alive. Magic Yarn isn't either of those things.

**Comment by fuzzyweapon** [comment]
Yeah, it definitely is.  I saw you had a ton of mods back then and figured
paring down was the reason.  I'm not in a position to right now, but if
someone wanted to carry the torch for one of your less popular mods like
that, would you be open to that?  (Likely pulling it to a separate repo and
crediting back to you because I wouldn't want to get in your way in your
own repo and inundate you with pull requests you'd have to manage).

**Comment by AtomicStryker** [comment]
I'm open to both pull requests and people taking over mods i have not kept updated. If, for example, someone were to fork the repo, keep just Magic Yarn, and port it to 1.14 and continue from there, i would wish them the best.
