### ISSUE TITLE
[1.14.4] Infernal Mobs Error on Start Up

### ISSUE THREAD

**Issue by KronoTrigger** [AtomicStryker/atomicstrykers-minecraft-mods#288]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 9/14/19 1:05 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at atomicstryker.infernalmobs.common.InfernalMobsCore.onTick(InfernalMobsCore.java:647) ~[?:1.14.4.3] {}
	at net.minecraftforge.eventbus.ASMEventHandler_145_InfernalMobsCore_onTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:94) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:826) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 679214376 bytes (647 MB) / 1458569216 bytes (1391 MB) up to 3008888832 bytes (2869 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3228m -Xms256m -XX:PermSize=256m
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.1.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.1.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.1
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 CREATE_REGISTRIES}
		AmbientSounds_v3.0.9_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 CREATE_REGISTRIES}
		angermanagement-1.14.4-0.1.0.jar Anger Management Mod {angermanagement@1.14.4-0.1.0 CREATE_REGISTRIES}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 CREATE_REGISTRIES}
		BasicNetherOres-1.14.4-3.2.1.jar Basic Nether Ores {bno@3.2.1 CREATE_REGISTRIES}
		BetterAdvancements-1.14.4-0.1.0.87.jar Better Advancements {betteradvancements@0.1.0.87 CREATE_REGISTRIES}
		betteranimalsplus-1.14.4-7.1.1.jar Better Animals Plus {betteranimalsplus@7.1.1 CREATE_REGISTRIES}
		BetterAnimationsCollection2-v1.1b4-1.14.4.jar Better Animations Collection 2 {betteranimationscollection2@1.1b4 CREATE_REGISTRIES}
		BetterSprinting-1.14.4-v3.0.1a.jar Better Sprinting {bettersprinting@3.0.1a CREATE_REGISTRIES}
		BetterThanMending-1.3.2.jar BetterThanMending {betterthanmending@1.3.2 CREATE_REGISTRIES}
		BiomesOPlenty-1.14.4-9.0.0.252-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.252 CREATE_REGISTRIES}
		caelus-FORGE-1.14.4-0.11.jar Caelus API {caelus@FORGE-1.14.4-0.11 CREATE_REGISTRIES}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 CREATE_REGISTRIES}
		colytra-FORGE-1.14.4-2.0-beta5.jar Colytra {colytra@FORGE-1.14.4-2.0-beta5 CREATE_REGISTRIES}
		ConsoleHUD-v1.4.3-1.14.4.jar Console HUD {consolehud@1.4.3 CREATE_REGISTRIES}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 CREATE_REGISTRIES}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		CraftingTweaks_1.14.4-10.1.3.jar Crafting Tweaks {craftingtweaks@10.1.3 DONE}
		create-mc1.14.4_v0.0.5.jar Create {create@0.0.5 CREATE_REGISTRIES}
		DungeonCrawl-1.14.4-1.3.0.jar Dungeon Crawl {dungeoncrawl@1.3.0 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.14.4-1.3.3.jar EnchantmentDescriptions {enchdesc@1.3.3 DONE}
		exp_ore-1.2.jar Exp Ore Block Mod {exp_ore@1.2 DONE}
		extcaves-1.1.jar Extended Caves {extcaves@1.1 DONE}
		extraanvils-2.1a.jar Extra Anvils {extraanvils@2.1a DONE}
		FastFurnace-1.14.4-2.2.0.jar FastFurnace {fastfurnace@2.2.0 CREATE_REGISTRIES}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 CREATE_REGISTRIES}
		FastWorkbench-1.14.4-2.1.0.jar FastWorkbench {fastbench@2.1.0 CREATE_REGISTRIES}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version CREATE_REGISTRIES}
		FpsReducer-mc1.14.4-1.13.jar FPS Reducer {fpsreducer@mc1.14.4-1.13 CREATE_REGISTRIES}
		gravestone-1.15.0.jar Gravestone Mod {gravestone@1.15.0 CREATE_REGISTRIES}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version CREATE_REGISTRIES}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version CREATE_REGISTRIES}
		infernalmobs-1.14.4.3.jar Infernal Mobs {infernalmobs@1.14.4.3 CREATE_REGISTRIES}
		InventorySpam-1.14.4-1.2.1.jar Inventory Spam {inventoryspam@version CREATE_REGISTRIES}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 CREATE_REGISTRIES}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 CREATE_REGISTRIES}
		JRFTL [1.14.4]-1.1.jar JRFTL {jrftl@1.1 CREATE_REGISTRIES}
		mightyarchitect-mc1.14.4_v0.4.6.jar The Mighty Architect {mightyarchitect@0.4.6 CREATE_REGISTRIES}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 CREATE_REGISTRIES}
		morecharcoal-1.14.4-1.0.3.jar More Charcoal {morecharcoal@1.14.4-1.0.3 CREATE_REGISTRIES}
		overloadedarmorbar-3.0.0.jar Example Mod {overloadedarmorbar@3.0.0 DONE}
		Placebo-1.14.4-2.2.0.jar Placebo {placebo@2.2.0 DONE}
		ProgressiveBosses-2.1.1.jar Progressive Bosses {progressivebosses@2.1.1 DONE}
		randomenchants-2.1.0.jar Random Enchants {randomenchants@2.1.0 CONSTRUCT}
		randompatches-1.14.4-1.18.1.1.jar RandomPatches {randompatches@1.14.4-1.18.1.1 CREATE_REGISTRIES}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 CREATE_REGISTRIES}
		ScalingHealth-1.14.4-2.3.2+22.jar Scaling Health {scalinghealth@2.3.2+22 CREATE_REGISTRIES}
		shulkerbox-1.7.0.jar Advanced Shulkerboxes {shulkerbox@1.7.0 CREATE_REGISTRIES}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 CREATE_REGISTRIES}
		simpleores-1.14.4-2.0.6.0.jar Simple Ores {simpleores@1.14.4-2.0.6.0 CREATE_REGISTRIES}
		simplytea-2.0.3.jar Simply Tea {simplytea@2.0.3 CREATE_REGISTRIES}
		speedyladders-1.14.4-1.0.3.jar Speedy Ladders {speedyladders@1.14.4-1.0.3 CREATE_REGISTRIES}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		toughnessbar-4.0.jar Toughness Bar {toughnessbar@4.0 DONE}
		TrashSlot_1.14.4-10.4.7.jar TrashSlot {trashslot@10.4.7 CREATE_REGISTRIES}
		TreeChoppin-1.14.4-1.2.0.jar TreeChoppin {treechoppin@1.2.0 DONE}
		Upgrade Aquatic Wave Three v5 - Beta v1.0.7.jar Upgrade Aquatic {upgrade_aquatic@1.0.6 CREATE_REGISTRIES}
		Waddles-1.14.4-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 CREATE_REGISTRIES}
		wildnature-2.0.0 ALPHA.jar WildNature Mod {wildnature@1.3 CREATE_REGISTRIES}
		WitherSkeletonTweaks-1.14.4-3.1.0.jar Wither Skeleton Tweaks {wstweaks@3.1.0 CONSTRUCT}
		YAMDA-4.0.1.jar YAMDA {yamda@4.0.1 CONSTRUCT}
		forge-1.14.4-28.1.1-universal.jar Forge {forge@28.1.1 CONSTRUCT}
		forge-1.14.4-28.1.1-client.jar Minecraft {minecraft@1.14.4 CONSTRUCT}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:yamda, mod:wstweaks, mod:wildnature, mod:waila, mod:waddles, mod:upgrade_aquatic, mod:treechoppin, mod:trashslot, mod:toughnessbar, mod:toastcontrol, mod:swingthroughgrass, mod:speedyladders, mod:simplytea, mod:simpleores, mod:silentlib, mod:shulkerbox, mod:scalinghealth, mod:randomthings, mod:randompatches, mod:randomenchants, mod:progressivebosses, mod:placebo, mod:overloadedarmorbar, mod:morecharcoal, mod:modnametooltip, mod:mightyarchitect, mod:jrftl (incompatible), mod:jei, mod:ironchest, mod:inventoryspam, mod:infernalmobs, mod:harvest, mod:gravestone, mod:fpsreducer, mod:forge, mod:fencejumper, mod:fastleafdecay, mod:fastfurnace, mod:fastbench, mod:extraanvils, mod:extcaves, mod:exp_ore, mod:enchdesc, mod:dungeoncrawl, mod:create, mod:craftingtweaks, mod:cosmeticarmorreworked, mod:controlling, mod:consolehud, mod:colytra, mod:clumps, mod:caelus, mod:bno, mod:biomesoplenty, mod:betterthanmending, mod:bettersprinting, mod:betteranimationscollection2, mod:betteranimalsplus, mod:betteradvancements (incompatible), mod:appleskin, mod:angermanagement, mod:ambientsounds, mod:aiimprovements
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by AtomicStryker** [comment]
Thanks for report, i think this fixes it https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/2bb6329a3aa6701c8a5d6eaaddc62546cb8a37ff
