### ISSUE TITLE
Don't crash from broken Ruins templates

### ISSUE THREAD

**Issue by GunArm** [AtomicStryker/atomicstrykers-minecraft-mods#29]
I was getting some crashes due to a couple of bad templates.  The crash is an IndexOutOfBoundsException in RuinsTemplate.doBuild (line 412 of the 1.7.10 branch).  I know, I know, bad templates are bad.  But would it be reasonable to just catch any exception in doBuild, log the template name and in-world X-Z coords, and move on; rather than letting bad templates crash the server?

Here's my crashtrace btw:  http://pastebin.com/E7c4zfVf

**Comment by AtomicStryker** [comment]
Well the idea was that people would test their templates using the commands which do have exception catching. But i can see your point. I'll make this change

**Comment by AtomicStryker** [comment]
Done.

**Comment by GunArm** [comment]
Much appreciated!
