### ISSUE TITLE
[1.14.4] [Pet Bats] Sometimes use flute dont work

### ISSUE THREAD

**Issue by j4p4n4s4** [AtomicStryker/atomicstrykers-minecraft-mods#290]
With only one pet bat/flute in inventory dont have any problem for now, but with 2+ flutes in inventory one work properly but the other dont recall pet bat to the inventory.

**Comment by AtomicStryker** [comment]
I don't understand. You can only have one flute in your hand to use it? Using them from inventory was never possible? What are the exact steps to produce a problem.

**Comment by j4p4n4s4** [comment]
sometime use flute dont work (don.t recall bat, do nothing) if i have another pet bat or flaute in inventory. if i put the extra bat to another inventory and only left in my inventory the faulty flute work again.

another issue is when pet bat is hanging in some block, if i press right click for staying put, gives and cancel the order with the same click. In chat: 

Name: Staying put.
Name: Dont staying put.

**Comment by AtomicStryker** [comment]
I cant reproduce a problem with the flutes, they work fine for me. I would need instruction on how to reproduce this every time.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/d45f747bbfa7b53a1fcfe39cec8623d46f9b7009

This should fix your double toggle problem.
