### ISSUE TITLE
[1.14.4] Ruins java.lang.NullPointerException: Exception generating new chunk

### ISSUE THREAD

**Issue by raziel23x** [AtomicStryker/atomicstrykers-minecraft-mods#292]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/3/19 8:47 PM
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at atomicstryker.ruins.common.RuinsMod.decorateChunkHook(RuinsMod.java:93) ~[?:1.14.4.1] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:112) ~[?:?] {re:classloading,xf:fml:ruins:Ruins chunk decoration Hook}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:73) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1493/986147545.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$3203/1227541141.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$3188/2101092903.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$3201/1792727646.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at atomicstryker.ruins.common.RuinsMod.decorateChunkHook(RuinsMod.java:93)
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:112)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:73)
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1493/986147545.doWork(Unknown Source)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196)

-- Chunk to be generated --
Details:
	Location: 0,0
	Position hash: 0
	Generator: net.minecraft.world.gen.OverworldChunkGenerator@534a62bd
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509)
	at net.minecraft.world.server.ChunkManager$$Lambda$3203/1227541141.apply(Unknown Source)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507)
	at net.minecraft.world.server.ChunkManager$$Lambda$3188/2101092903.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$3201/1792727646.run(Unknown Source)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 529
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Raziel23x World
	Level seed: 5443734919732763164
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:380)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:76)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2441392592 bytes (2328 MB) / 3701997568 bytes (3530 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.31.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.31
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotori_scala@2.13.1
	Mod List: 
		[1.14.2-1.14.4]TorchBowMod_v1.5.jar TorchBowMod {torchbowmod@1.5 NONE}
		A Block of Charcoal-1.2.jar A Block of Charcoal {charcoalblock@1.2 NONE}
		A Block of Flint-1.0.jar A Block of Flint {flintblock@1.0 NONE}
		alchemistry-1.14.4-5.jar Alchemistry {alchemistry@1.14.4-5 NONE}
		alib-1.14.4-5.jar A Lib {alib@1.14.4-5 NONE}
		angelring-1.14.4-1.0.1.jar Angel Ring {angelring@1.0.1 NONE}
		Apotheosis-1.14.4-2.4.0.jar Apotheosis {apotheosis@2.4.0 NONE}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 NONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 NONE}
		bambooeverything-1.14-1.4.0.jar Bamboo Everything {bambooeverything@1.14-1.4.0 NONE}
		bambooladders-1.14-1.0.0.jar Bamboo Ladders {bambooladders@1.14-1.0.0 NONE}
		buildinggadgets-3.0.5.jar Building Gadgets {buildinggadgets@3.0.5 NONE}
		caelus-FORGE-1.14.4-1.0.jar Caelus API {caelus@FORGE-1.14.4-1.0 NONE}
		campfiretorches-1.14.4-1.0.3.jar Campfire Torches {campfiretorches@1.14.4-1.0.3 NONE}
		CarryOn MC1.14.4 v1.12.3.jar Carry On {carryon@1.12.3 NONE}
		ceilingtorch-1.14.4-v1.2.2.jar Ceiling Torch {ceilingtorch@v1.2.2 NONE}
		chemlib-1.14.4-6.jar Chem Lib {chemlib@1.14.4-6 NONE}
		chesthopper-2.1.1.jar ChestHopper {chesthopper@v2.1.1 NONE}
		ChickenDropFeathers-2.0.jar Chicken Drop Feathers {chickendropfeathersmod@2.0 NONE}
		citadel-1.0.0.jar Citadel {citadel@1.0.0 NONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 NONE}
		colytra-FORGE-1.14.4-2.0.jar Colytra {colytra@FORGE-1.14.4-2.0 NONE}
		compact-2.6a.jar Compressed {compressed@2.6a NONE}
		ComPatchedStorage-1.14.4-2.1.4.jar ComPatchedStorage {compatchedstorage@2.1.4 NONE}
		Compressium-1.0.7.jar Compressium {compressium@1.14-1.0.3 NONE}
		container-1.14.4-1.0.0.jar Container {container@1.14.4-1.0.0 NONE}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 NONE}
		corail_woodcutter-1.0.6-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.0.6 NONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a NONE}
		craftingstation-2.0.5.jar Crafting Station {craftingstation@2.0.5 NONE}
		CraftingTweaks_1.14.4-10.1.3.jar Crafting Tweaks {craftingtweaks@10.1.3 NONE}
		create-mc1.14.4_v0.1.1.jar Create {create@0.1.1 NONE}
		Cucumber-1.14.4-2.0.3.jar Cucumber Library {cucumber@2.0.3 NONE}
		cursedearth-1.3a.jar Cursed Earth {cursedearth@1.3a NONE}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 NONE}
		CyclopsCore-1.14.4-1.5.3.jar Cyclops Core {cyclopscore@1.5.3 NONE}
		dankstorage-1.4b.jar Dank Storage {dankstorage@1.4b NONE}
		dcintegration-1.0.12-1.14.jar Discord Integration {dcintegration@1.0.12-1.14 NONE}
		DefaultOptions_1.14.4-10.2.6.jar Default Options {defaultoptions@10.2.6 NONE}
		DefaultSettings-1.14.x-1.3.5.jar DefaultSettings {defaultsettings@1.3.5 NONE}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 NONE}
		DungeonCrawl-1.14.4-1.4.0.jar Dungeon Crawl {dungeoncrawl@1.4.0 NONE}
		EasySteel-1.14.4-1.0.39.jar Easy Steel & More {easy_steel@1.0.39 NONE}
		EditSign-1.14.4-1.0.1+4.jar Edit Sign {edit_sign@1.0.1+4 NONE}
		elevatorid-1.14.4-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 NONE}
		EnchantmentDescriptions-1.14.4-1.3.6.jar EnchantmentDescriptions {enchdesc@1.3.6 NONE}
		enchxchg-1.14.4-5.0.0.jar Enchantments Exchanger {enchxchg@1.14.4-5.0.0 NONE}
		EnergeticSheep-1.14.4-1.1.5.jar EnergeticSheep {energeticsheep@1.1.5 NONE}
		enviromats-2.0.0.9.jar Environmental Materials {enviromats@2.0.0.9 NONE}
		es_1.14-1.0.jar Edible Sugar {es@1.0 NONE}
		essentials-1.14.4-2.5.3.jar Essentials {essentials@1.14.4-2.5.3 NONE}
		EverlastingAbilities-1.14.4-1.5.5.jar EverlastingAbilities {everlastingabilities@1.5.5 NONE}
		extcaves-1.2.jar Extended Caves {extcaves@1.2 NONE}
		f2l-0.1.8_forge.jar Flesh 2 Leather {f2l@0.1.8_forge NONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 NONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 NONE}
		FastWorkbench-1.14.4-2.1.1.jar FastWorkbench {fastbench@2.1.1 NONE}
		firstaid-1.7.8.jar First Aid {firstaid@1.7.8 NONE}
		forbidden_arcanus-1.14.4-1.3.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.3 NONE}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 NONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 NONE}
		GemsPlusPlus-Forge-1.14.4-V1.3.2.jar GemsPlusPlus {gemsplusplus@V1.3.2 NONE}
		globaldatapack-1.14.4-1.2.1.jar Dark Roleplay - Global Datapacks {globaldatapack@1.14.4-1.2 NONE}
		Gobber2-1.14.4-2.1.97.jar Gobber 2 {gobber2@2.1.97 NONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version NONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version NONE}
		inventorysorter-1.14.4-16.1.0.jar Simple Inventory Sorter {inventorysorter@16.1.0 NONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 NONE}
		IronJetpacks-1.14.4-2.0.2.jar Iron Jetpacks {ironjetpacks@2.0.2 NONE}
		ironshulkerboxes-1.14.4-3.1.12.jar Iron Shulker Boxes {ironshulkerbox@1.14.4-3.1.12 NONE}
		jei-1.14.4-6.0.0.13.jar Just Enough Items {jei@6.0.0.13 NONE}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 NONE}
		LargeFluidTank-14.8.2.jar FluidTank {fluidtank@14.8.2 NONE}
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 NONE}
		lycanitesmobs-1.14.4-2.1.0.2.jar Lycanites Mobs {lycanitesmobs@1.0 NONE}
		mcjtylib-1.14-3.5.7-alpha.jar McJtyLib {mcjtylib@NONE NONE}
		metalbarrels-1.3c.jar Metal Barrels {metalbarrels@1.3c NONE}
		minecolonies-0.10.415-ALPHA-universal.jar Minecolonies {minecolonies@0.10.415-ALPHA NONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 NONE}
		moreprog-1.14.4-0.4.2.jar MoreProgression {moreprogression@0.4.2 NONE}
		MouseTweaks-2.11-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.11 NONE}
		OreExcavation-1.6.141.jar Ore Excavation {oreexcavation@1.6.141 NONE}
		OresAllEasy-1.14.4-1.2.1.jar OresAllEasy {oresalleasy@1.2.1 NONE}
		Overloaded-1.14.4-0.0.76.jar Overloaded {overloaded@1.14.4-0.0.76 NONE}
		ParticleFixes-v1.1-1.14.4.jar Particle Fixes {particlefixes@1.1 NONE}
		peanutmod-1.0.2.jar Peanut Mod {peanutmod@1.0.2 NONE}
		PickleTweaks-1.14.4-3.0.6.jar Pickle Tweaks {pickletweaks@3.0.6 NONE}
		Placebo-1.14.4-2.3.0.jar Placebo {placebo@2.3.0 NONE}
		portality-1.14.4-2.0.0-5f9c6a1.jar Portality {portality@NONE NONE}
		PowderPower-1.14.4-3.0.33.jar Powder Power {powder_power@3.0.33 NONE}
		quickhomes-1.14.4-1.2.4.2.jar QuickHomes {quickhomes@1.2.4.2 NONE}
		quickteleports-1.14.4-1.1.0.jar QuickTeleports {quickteleports@1.1.0 NONE}
		randompatches-1.14.4-1.18.2.1.jar RandomPatches {randompatches@1.14.4-1.18.2.1 NONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 NONE}
		reap-1.10.1.jar Reap Mod {reap@1.10.1 NONE}
		rftoolsbase-1.14-0.0.4-alpha.jar RFToolsBase {rftoolsbase@NONE NONE}
		rftoolspower-1.14-1.2.4-alpha.jar RFToolsPower {rftoolspower@NONE NONE}
		RingOfAttraction-1.14.4-1.0.15.jar Ring of Attraction {ring_of_attraction@1.0.15 NONE}
		RingOfBlink-1.14.4-1.0.18.jar Ring of Blink {ring_of_blink@1.0.18 NONE}
		RingOfEnderchest-1.14.4-1.0.16.jar Ring of Enderchest {ring_of_enderchest@1.0.16 NONE}
		RingOfGrowth-1.14.4-1.0.16.jar Ring of Growth {ring_of_growth@1.0.16 NONE}
		RingOfMiner-1.14.4-1.0.13.jar Ring of Miner {ring_of_miner@1.0.13 NONE}
		RingOfRepair-1.14.4-1.0.16.jar Ring of Repair {ring_of_repair@1.0.16 NONE}
		RingOfTeleport-1.14.4-1.0.14.jar Ring of Teleport {ring_of_teleport@1.0.14 NONE}
		ruins-1.14.4.1.jar Ruins {ruins@1.14.3.3 NONE}
		SBM-WoodenShears-1.14.4-1.0.0.jar SBM-Wooden Shears {woodenshears@1.0.0 NONE}
		SilentGear-1.14.4-1.4.3+68.jar Silent Gear {silentgear@1.4.3+68 NONE}
		SilentGems-1.14.4-3.4.4+77.jar Silent's Gems 3 {silentgems@3.4.4+77 NONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 NONE}
		SilentMechanisms-1.14.4-0.6.2+33.jar Silent's Mechanisms {silents_mechanisms@0.6.2+33 NONE}
		SimpleDivingGear-3.0.2 mc 1.14.4.jar Simple Diving Gear {simpledivegear@3.0.2 mc 1.14.4 NONE}
		simplefarming-1.14.4-1.1.9.jar Simple Farming {simplefarming@1.14.4-1.1.9 NONE}
		SimpleStorageNetwork-1.14.4-0.0.13.jar Simple Storage Network {storagenetwork@1.14.4-0.0.13 NONE}
		simplylight-0.9.0.jar Simply Light {simplylight@0.9.0 NONE}
		SolarGeneration-1.14.4-1.0.1b.jar Solar Generation {solargeneration@1.0.1 NONE}
		StoneChest-1.14.4-1.0.1.jar Stone Chest {stonechest@1.0.1 NONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 NONE}
		structurize-0.10.175-ALPHA.jar Structurize {structurize@0.10.175-ALPHA NONE}
		TheVeggieWay-1.14.4-2.0.20.jar The Veggie Way {veggie_way@2.0.20 NONE}
		titanium-1.14.4-2.2.0-d9775a7.jar Titanium {titanium@1.14.4-2.2.0-d9775a7 NONE}
		tombstone-4.1.4-1.14.4.jar Corail Tombstone {tombstone@4.1.4 NONE}
		ToolBelt-1.14.4-1.12.1.jar Tool Belt {toolbelt@1.12.1 NONE}
		TorchBandolier-1.14.4-1.3.1+6.jar Torch Bandolier {torchbandolier@1.3.1+6 NONE}
		torchmaster-2.0.0.7-rc0.jar Torchmaster {torchmaster@2.0.0.7-rc0 NONE}
		torchoptimizer-1.14.4-2.1.6.jar Torch Optimizer {torchoptimizer@1.14.4-2.1.6 NONE}
		tramplestopper-1.14.4-2.0.0.24-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.24-universal NONE}
		travellersboots-1.14.4-1.2.2.jar Traveller's Boots {travellersboots@1.2.2 NONE}
		tubesreloaded-1.14.4-1.1.0b.jar Tubes Reloaded {tubesreloaded@1.14.4-1.1.0b NONE}
		u_team_core-1.14.4-2.7.3.132.jar U Team Core {uteamcore@2.7.3.132 NONE}
		Upgrade Aquatic Wave Three v6 - Beta 1.0.8.jar Upgrade Aquatic {upgrade_aquatic@1.0.7 NONE}
		Uppers-0.1.10.jar Uppers {uppers@0.1.10 NONE}
		upsizer-mc1.14.4-5.0b2.jar Upsizer {upsizer@5.0.0b2 NONE}
		useful_backpacks-1.14.4-1.7.1.36.jar Useful Backpacks {usefulbackpacks@1.7.1.36 NONE}
		valkyrielib-3.0.0.8.jar ValkyrieLib {valkyrielib@3.0.0.8 NONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 NONE}
		weapon_craftery-1.14.4-1.0-Beta-4.jar Weapon Craftery {weapon_craftery@1.14.4-1.0-Beta-4 NONE}
		WoolToString-1.14.2-1.0.0.jar WoolToString {wooltostring@1.0.0 NONE}
		Wyrmroost-1.14.4-1.0.2.jar Wyrmroost {wyrmroost@1.0.2 NONE}
		XL-Food-Mod-1.14.4-2.1.0.jar XL Food Mod {xlfoodmod@2.1.0 NONE}
		YAMDA-4.0.1.jar YAMDA {yamda@4.0.1 NONE}
		forge-1.14.4-28.1.31-universal.jar Forge {forge@28.1.31 NONE}
		forge-1.14.4-28.1.31-client.jar Minecraft {minecraft@1.14.4 NONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:yamda, mod:xlfoodmod, mod:wyrmroost, mod:wooltostring, mod:woodenshears, mod:weapon_craftery, mod:waterstrainer, mod:waila, mod:voxelmap, mod:veggie_way, mod:valkyrielib, mod:uteamcore, mod:usefulbackpacks, mod:upsizer, mod:uppers, mod:upgrade_aquatic, mod:tubesreloaded, mod:travellersboots, mod:tramplestopper, mod:torchoptimizer, mod:torchmaster, mod:torchbowmod, mod:torchbandolier, mod:toolbelt, mod:tombstone, mod:titanium (incompatible), mod:structurize, mod:storagenetwork, mod:storagedrawers, mod:stonechest, mod:solargeneration, mod:simplylight, mod:simplefarming, mod:simpledivegear, mod:silents_mechanisms, mod:silentlib, mod:silentgems, mod:silentgear, mod:ruins, mod:ring_of_teleport, mod:ring_of_repair, mod:ring_of_miner, mod:ring_of_growth, mod:ring_of_enderchest, mod:ring_of_blink, mod:ring_of_attraction, mod:rftoolspower, mod:rftoolsbase, mod:reap, mod:randomthings, mod:randompatches, mod:quickteleports, mod:quickhomes, mod:powder_power, mod:portality (incompatible), mod:placebo, mod:pickletweaks, mod:peanutmod, mod:particlefixes, mod:overloaded, mod:oresalleasy, mod:oreexcavation, mod:mousetweaks, mod:moreprogression, mod:modnametooltip, mod:minecolonies (incompatible), mod:metalbarrels, mod:mcjtylib, mod:lycanitesmobs, mod:llor, mod:kleeslabs, mod:jei, mod:ironshulkerbox, mod:ironjetpacks, mod:ironchest, mod:inventorysorter, mod:harvest, mod:gobber2, mod:globaldatapack, mod:gemsplusplus, mod:ftbbackups, mod:forge, mod:forbidden_arcanus, mod:fluidtank, mod:flintblock, mod:firstaid, mod:fastleafdecay, mod:fastfurnace, mod:fastbench, mod:f2l, mod:extcaves, mod:everlastingabilities, mod:essentials, mod:es, mod:enviromats, mod:energeticsheep, mod:enchxchg, mod:enchdesc, mod:elevatorid, mod:edit_sign, mod:easy_steel, mod:dungeoncrawl, mod:defaultsettings, mod:defaultoptions, mod:dcintegration, mod:dankstorage, mod:d2p, mod:cyclopscore, mod:cyclic, mod:cursedearth, mod:cucumber, mod:create, mod:craftingtweaks, mod:craftingstation, mod:cosmeticarmorreworked, mod:corail_woodcutter, mod:controlling, mod:container, mod:compressium, mod:compressed, mod:compatchedstorage, mod:colytra, mod:clumps, mod:citadel, mod:chickendropfeathersmod, mod:chesthopper, mod:chemlib, mod:charcoalblock, mod:ceilingtorch, mod:carryon, mod:campfiretorches, mod:caelus, mod:buildinggadgets, mod:bambooladders, mod:bambooeverything, mod:attributefix, mod:appleskin, mod:apotheosis, mod:angelring, mod:alib, mod:alchemistry
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by AtomicStryker** [comment]
Hmm. The hack into worldgen triggers before Forge has instantiated the mod. Neat. I'll fix it later today

**Comment by AtomicStryker** [comment]
Should be fixed with https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/c0dc6bc12b36c5e38ed4686f925724909c9fbe24
