### ISSUE TITLE
Ruins mod [1.14.4]

### ISSUE THREAD

**Issue by Maciek2109** [AtomicStryker/atomicstrykers-minecraft-mods#293]
![2019-10-05_23 27 51](https://user-images.githubusercontent.com/56206982/66261121-36c70980-e7c8-11e9-8b6b-696a41eea3f8.png)
Hey, after downloading the mod nothing happens. if I unpack it and copy ruins_cofing to minecraft/config it starts to work. After generating new world i dont see structures, but only some strange free spaces in the world. Am I doing something wrong? Can I fix it?

**Comment by AtomicStryker** [comment]
Ruins 1.13 and 1.14 do not have any templates included, because i didn't port the included templateset. And nobody has pull requested a working set, either.

**Comment by AtomicStryker** [comment]
As for "fixing", create a few templates and they will start spawning.
