### ISSUE TITLE
Battle Towers, reverse towers exploding? [feature request]

### ISSUE THREAD

**Issue by Shivaxi** [AtomicStryker/atomicstrykers-minecraft-mods#295]
I always thought this was supposed to happen, but learned recently it does not.  Would love to have the reverse battle towers also blow up, from the bottom up haha, would be awesome.

**Comment by AtomicStryker** [comment]
That would leave a player stranded in a very deep hole

**Comment by Shivaxi** [comment]
Exactly, mwahahaha.  (it would be optional of course, probably disabled by default =P )
