### ISSUE TITLE
[1.12.2][BattleTowers 1.6.5] BattletowerPositionsFile writes to wrong save folder

### ISSUE THREAD

**Issue by Charles445** [AtomicStryker/atomicstrykers-minecraft-mods#300]
Create or load a save (World A)
Save and quit to title
Create or load a different save (World B)
World B's tower positions will now be writing to World A's folder instead of World B's folder.

If I understand correctly, this will mess with the spawning of the battle towers in some capacity.
I don't think servers will run into this bug, but single player definitely does.

**Comment by AtomicStryker** [comment]
I will keep this in mind should i update the mod to 1.14, but i won't do any fixing for 1.12. The workaround is to not hotswap saves without restarting MC.

Thank you for reporting it.

**Comment by xxlio109** [comment]
pls 1.12 FIX~~
