### ISSUE TITLE
[Ruins] 1.14.4 - parseruin doesn't save inventories/item frames/sign-text/...

### ISSUE THREAD

**Issue by Tiscan76** [AtomicStryker/atomicstrykers-minecraft-mods#304]
Im currently using version 1.14.4.3 and tried to create a template using the /parseruin command. My test-build had a sign, some item-frames, a chest with some items, etc. in it.

After saving it, i spawned it using the /testruin-command and the item-frames were missing, the sign didn't have any text on it and the chest was empty.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/65a374cc5f344b20f2a2cbb488df3b1a91d637d4

Fixed in Ruins 1.14.4.4, thanks for reporting

**Comment by Tiscan76** [comment]
Thanks for fixing this so quickly!
