### ISSUE TITLE
battletowers crash with write to file access

### ISSUE THREAD

**Issue by Shivaxi** [AtomicStryker/atomicstrykers-minecraft-mods#306]
![image](https://user-images.githubusercontent.com/10459358/67968694-3ad72300-fbde-11e9-8c95-5dae39db2587.png)

this seems to happen randomly, just happened to me in a single player game

**Comment by Shivaxi** [comment]
even if this is some sort of windows issue with permissions, would it be possible to add in some sort of fail safe so it just fails to write to the file and tries again later?  instead of fully crashing the game?

**Comment by AtomicStryker** [comment]
Code a fallback mechanism of unknown complexity, for a nondescript random end user problem, for a minecraft version i don't support anymore? Truly, a spooky suggestion. I'm going to go with ... no.

**Comment by Shivaxi** [comment]
Tons of people have been getting this error though.  I don't even know why write permission would be denied, I'm administrator of my own computer obviously, and I even run Minecraft with admin, so it shouldn't have problems.  Ruins and Recurrent Complex also generate a text file in the world folder to write to and don't have this issue at all, so it's definitely battletowers that's the problem here.

**Comment by Shivaxi** [comment]
we even made a custom build of battletowers to fix it lol:


[BattleTowers-1.12.2_hotfix.zip](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/3796223/BattleTowers-1.12.2_hotfix.zip)


there, now u don't even have to do the work =P

**Comment by Shivaxi** [comment]
I'd also like to point out that 1.12 is still the most popular played version of Minecraft for mods...1.13 is dead and 1.14 is about to be dead with the 1.15 on our doorstep AND they're already talking about 1.16 with the nether update.  1.12 is/has become a hub for mods just as 1.7.10 did back in the day because 1.12 sat around long enough.  Now-a-days mojang is releasing updates too quickly, modders can't keep up with all the changes, i mean 1.13 along drastically changes the way modders have to code their mods, especially the bigger mods.  80% of mods right now don't even have a 1.14 version, and likely never will with the rate of updates coming out, meaning MOST modpacks will still be on 1.12 for...a long time.  Not supporting 1.12 is...well...just not smart honestly.  Just my 2 cents I guess but happy halloween i s'pose.

**Comment by AtomicStryker** [comment]
Out of curiosity i glanced in that "fixed" file you posted. There does not appear to be any apparent changes to the way the positions file is written. In fact it still crashes when denied write access to the file. If you want to claim you "fixed it for me", by all means submit a pull request on the repository. I do merge those.

**Comment by Charles445** [comment]
The only change I can spot is !file.delete() was changed to !file.canWrite()

It doesn't quite make sense that it's only been showing up in BattleTowers, though, as Ruins uses file delete as well.

@Shivaxi   Have you tried testing out the newest version of the mod? It should fix positions files writing to the wrong places. It could be that this error is being caused by a dimension trying to write to the file that another dimension was already writing to.

**Comment by Shivaxi** [comment]
I did yes.  I didn't make the fix, I was just told that supposedly it worked.  The bug is so rare it's very hard replicate and track down.  And ruins doesn't ever have this issue even though it writes the same way so I'm not sure.
