### ISSUE TITLE
Provide List of NBT Codes For Infernal Mobs

### ISSUE THREAD

**Issue by VinterNacht** [AtomicStryker/atomicstrykers-minecraft-mods#309]
I'm trying to build a custom spawn list that controls when certain tags are added.  I was wondering if a list of the NBT codes applied by Infernal Mobs could be provided somewhere?

**Comment by AtomicStryker** [comment]
Mod names can be gleaned from the translation files.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.12.2/InfernalMobs/src/main/resources/assets/infernalmobs/lang/en_US.lang

First one is translation.infernalmobs:mod.1UP=1UP, so "1UP".

**Comment by VinterNacht** [comment]
Thank you.  Quasi-related: Do you happen to know if applying these to Mobs via In Control is possible?  I know it can edit NBT codes, but I haven't had much success getting actual results.

**Comment by AtomicStryker** [comment]
Don't know what that is. Getting Infernal Mobs from "outside" the mod would involve saving and loading the map such that NBT tags are re-processed.

**Comment by VinterNacht** [comment]
That helps lend a little understanding.  So you can't slap an NBT value on a mob as it spawns and get Infernal effects?  That's an understandable shame.  I'll have to remove Infernal then.  Such a fun mod though!
