### ISSUE TITLE
[1.12.2][InfernalMobs] Mobs becoming infernal after reload?

### ISSUE THREAD

**Issue by Tiscan76** [AtomicStryker/atomicstrykers-minecraft-mods#310]
I'm currently using the latest version of InfernalMobs (released on 26.8.19) and I noticed something that's IMHO kinda odd.

I've got a little test-world with a bunch of named mobs from different mods. One of them is a Black Bear from the Better Anmials Plus mod. And that guy is randomly becoming a Rare mob upon loading the world. You load it, he is rare. You quit and load it again and he is a regular mob again. I've seen this happen 3-4 times so far.

Is this the intended behaviour or is Better Animals acting funny?

Personally I would have expected that the mod only decides upon spawning if a mob is infernal and if a mob already exists in the world it doesn't become infernal randomly on reload - imagine having a named pet-zombie who suddenly throws fireballs and potions at you ;-)

**Comment by AtomicStryker** [comment]
Probably an unintended consequence of custom mod entity load implementations.

Infernal Mobs re-registers rare mobs upon being loaded by looking at their nbt data. If the nbt data does not indicate an entity is already rare, it is eligible for becoming rare.

If the custom entities do not implement the expected way of conserving their nbt tags into a world savefile, this sort of behaviour can happen.

**Comment by Tiscan76** [comment]
This could be it as I also spawned in a ton of EmberRootZoo mobs and didn't see this happen to any of them. Thanks for clarifying! I'll close the issue.
