### ISSUE TITLE
1.14.4.4 crash when entity enters chunk

### ISSUE THREAD

**Issue by kreezxil** [AtomicStryker/atomicstrykers-minecraft-mods#312]
report name | paste
 ----------- | -----
crash-2019-11-20_02.50.46-server.txt | http://paste.ubuntu.com/p/3xCNxz2M3r/

The crash report calls it a server hang

**Comment by AtomicStryker** [comment]
Ruins 1.14.4.5 might help, if the problem is what i suspect it is.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/1c249a92207018ea5d13e99554485e1cdae797b7
