### ISSUE TITLE
[Ruins] Issues spawning structures in Shinoow's "Beneath" dimension (ID 10)

### ISSUE THREAD

**Issue by MolniyaWaltz** [AtomicStryker/atomicstrykers-minecraft-mods#313]
Spawning Ruins templates in the Beneath dimension (https://www.curseforge.com/minecraft/mc-mods/the-beneath) results in said ruins only spawning at the topmost possible point of the world. Attempts to mitigate this issue e.g. use of embed_into_distance property unsuccessful as they result in oddly placed ruins (floating, stuck in the middle of stone etc.), likely a  result of the offset not taking into account present surfaces.

A possible solution might be starting the search for a surface to place a ruin lower than the highest possible y-value as this may prevent ruins from getting lodged in the ceiling in the first place but, that may be difficult to do and after all I'm not a dev so, yeah. Would be great if this could get a fix though. Thanks! :)

**Comment by AtomicStryker** [comment]
Requires a completely different algorithm to find viable spawning points. I believe the old code just randomly picked a height and tried it... not a priority

**Comment by Ironnoob73** [comment]
Try adding bedrock to "unacceptable_target_blocks".
