### ISSUE TITLE
[1.14.4] Infernals Mobs have no Bossbar (healthbar) or particles on Servers.

### ISSUE THREAD

**Issue by Gbergz** [AtomicStryker/atomicstrykers-minecraft-mods#314]
As the title says, on servers the Infernal Mobs have no healthbar (bossbar showing their name) or particle effects on the mob.

Mod Version: 1.14.4.5
MC Version: 1.14.4
Forge Version: 28.1.107

Any fixes for this? :)

EDIT: They do show up in Singleplayer but not on Multiplayer Servers.

**Comment by AtomicStryker** [comment]
Thanks for the report. Version 1.14.4.6 should fix the problem
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/8b59aaf8d6fb1d7963b6efcca61d74604321e934

**Comment by AtomicStryker** [comment]
Pushed to curse
