### ISSUE TITLE
[Infernal Mobs][1.12.2]

### ISSUE THREAD

**Issue by Sereath** [AtomicStryker/atomicstrykers-minecraft-mods#316]
1.12.2
Using the latest release from Aug 26, 2019.

After disabling the **Webber**, **Alchemist** and **Darkness** modifiers I started getting this messages quite often over the server's console:
```
[Server thread/INFO] [STDERR]: [atomicstryker.infernalmobs.common.InfernalMobsCore:addEntityModifiersByString:607]: Infernal Mobs error, could not instantiate modifier Webber Alchemist Darkness
```
The thing is that I had already disabled other modifiers way before now, such as Sticky and Storm, on an already existing world as well and never had this happen.

Log from a quick session.

[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/3993177/latest.log)

One with way more of those messages.

[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/3993360/latest.log)

**Comment by AtomicStryker** [comment]
If Mobs exist that had those modifiers, and you disable them, those mobs will print those errors every time they (re-)enter the world. Avoid changing modifiers on worlds in use.

**Comment by Sereath** [comment]
Yeah I assumed that, I see then that it might be a mob that is not allowed to despawn such as the cyclops of *Ice and Fire*.
Fair enough, thanks.
