### ISSUE TITLE
[1.15.1] [Ruins] No Loot?

### ISSUE THREAD

**Issue by Adamjoko** [AtomicStryker/atomicstrykers-minecraft-mods#317]
I went into the _.jar_ file, read all the directions, and I have seen nothing that states how to acquire any loot from the spawning chests. Is this a bug? Am I doing something wrong? Let me know, please!

**Comment by Adamjoko** [comment]
Quick Update: Some of the structures don't have loot in them (ie: Ships) but some do.

**Comment by AtomicStryker** [comment]
It depends on the templates i guess. Only those which have chests configured for loot will have loot.

As for how to aquire: Press "use" on the chest (default e) and transfer inventory of choice.

**Comment by Adamjoko** [comment]
Thank You, I'll keep looking for any bugs.
