### ISSUE TITLE
[1.14.4] Log spam

### ISSUE THREAD

**Issue by Gbergz** [AtomicStryker/atomicstrykers-minecraft-mods#318]
Logs and debug log is being spammed by this, i have no idea why but it does. Any ideas?

Logs Spam: [https://gist.github.com/Gbergz/bb10d5a696959a835ec963faa88d7d48](https://gist.github.com/Gbergz/bb10d5a696959a835ec963faa88d7d48)

**MC-Version** 1.14.4
**Forge Version** 28.1.107
**Mod-Version:** ruins-1.14.4.4.jar

**Comment by QuarterAnimal** [comment]
I'll add a throttle on the deprecation warnings. Currently, the warning is emitted every time the "old" block entity specification (**ruinsTE**) is encountered in the template files. I suppose there's no point in seeing the message more than once, though, aside from letting you know how many lines should be edited. Note it's just a deprecation warning, so you can ignore it...for now.

There are some legit errors flagged in that log, however. At least 2 invalid rules appear in your set of templates. Multiple block entities for a single block? That's not a thing.
