### ISSUE TITLE
(1.14)error Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $

### ISSUE THREAD

**Issue by jonas939** [AtomicStryker/atomicstrykers-minecraft-mods#319]
[modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid infernalmobs
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $

**Comment by AtomicStryker** [comment]
Invalid config file syntax
