### ISSUE TITLE
[1.14.4] Ruins Crash on 1.14.4 Server

### ISSUE THREAD

**Issue by Gbergz** [AtomicStryker/atomicstrykers-minecraft-mods#321]
Forge Version: 28.1.107
MC-Version: 1.14.4
Ruins Mod Version: ruins-1.14.4.4 | This one: [https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system/files/2830120](https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system/files/2830120)

Crash-Report: [https://gist.github.com/Gbergz/982bb258efa63d1b7c004e46e713da02](https://gist.github.com/Gbergz/982bb258efa63d1b7c004e46e713da02)

**Comment by AtomicStryker** [comment]
While Ruins was in the process of spawning a template, it appears the actual lockup is in the code of the "farlanders" mod.

com.legacy.farlanders.world.FarlanderLootFeature.place(FarlanderLootFeature.java:89)

Are you using your own templates? Using large (spanning multiple chunks) templates can no longer be considered safe at all, as any worldgen triggered while placing templates will lock up minecraft.

I really dislike how they implemented that...

**Comment by Gbergz** [comment]
I'm using all templates found inside your Jar, should i not be using them? Because before adding them no "structures" were spawning.

**Comment by AtomicStryker** [comment]
I see. The next step would be to get the latest.log logfile from when the crash happened and hopefully have some information about which template exactly it was...
