### ISSUE TITLE
InfermalMobs does not let spawnear mobs another mod?

### ISSUE THREAD

**Issue by ChukiStrike** [AtomicStryker/atomicstrykers-minecraft-mods#323]
Could it be incompatible with EmberRootZoo?
Don't EmberRootZoo mobs spawn because it can be? Because there are too many mobs and they don't all fit?

**Comment by AtomicStryker** [comment]
Sorry? I don't understand your issue.

**Comment by ChukiStrike** [comment]
Sorry, I'll try to explain better.
I use your mod. Now I have installed this mod [EmberRootZoo](https://www.curseforge.com/minecraft/mc-mods/emberroot-zoo) that creates new mobs, but they don't appear in the game. Could it be because your mod is blocked? Or because if we add your mobs to theirs there are so many mobs that they don't create them all at once?

**Comment by AtomicStryker** [comment]
Do they appear if Infernal Mobs is not installed? Unless there is a crash in the "infernalization", it should never stop entities from appearing. Have you checked your logfiles/console output for errors?

**Comment by ChukiStrike** [comment]
I don't have any errors in the console I think.
That's what I meant, I put a block on spiders, skeletons and zombies and they keep showing up. Why? :(
You have discord server? Thanks.

**Comment by AtomicStryker** [comment]
I still do not understand what it is you are trying to convey. Are you trying to stop vanilla mobs from spawning? From becoming infernal? What exactly keeps showing up?

**Comment by ChukiStrike** [comment]
Yeah, I want to stop the vanilla mobs. To come out of another kind of mods.
because there are a lot of vanilla mobs and very few mods. (I want more mods and less vanilla mobs.

**Comment by AtomicStryker** [comment]
Infernal Mobs can't help you with that. You need some other mod to prevent vanilla mobs from spawning altogether.
