### ISSUE TITLE
Bugg arrows

### ISSUE THREAD

**Issue by ChukiStrike** [AtomicStryker/atomicstrykers-minecraft-mods#324]
Hello, does anyone have the error that the arrows stay on the server forever? You can build on top of them and whatever, but they're still there.
![Sin título](https://user-images.githubusercontent.com/38164175/72007573-497f2d80-3252-11ea-955e-2824e5ce0b06.jpg)

**Comment by AtomicStryker** [comment]
minecraftforum would be better for those kind of random questions
