### ISSUE TITLE
Conflict with U-team core mod

### ISSUE THREAD

**Issue by phiphila** [AtomicStryker/atomicstrykers-minecraft-mods#325]
When start minecraft (Forge 14....109) with mods: Ruins ruins-1.14.4.4, and u_team_core-1.14.4-2.8.0.139 then the chests in Ruins are empty
is I run minecraft just with Ruins ruins-1.14.4.4 all is ok.

Steps to reproduce:
U team core is here : https://www.curseforge.com/minecraft/mc-mods/u-team-core

I did several tests, deleting the installed mods (about twenty) step by step, one after the other, to find the one that was in conflict with Ruins, because in this mods the chests generated was empty. so, I ended up finding that U-Team-Core was in conflict with ruins, so I deleted all the mods, then start minecraft just with ruins, the chests (generated in the structures created by the ruins mod) are full, then replaced just U-Team-Core and ruins and restarted minecraft, the chests are then empty (the newly generated chests).
A strange thing, this conflict is only present from my minecraft server, in "local" (a solo game) there is no conflict ....
I play with minecraft in 1.14.4

run minecraft with these mods
find a chest of ruins structure, open it, it is empty 
I also sent the same issue to U team core modder

**Comment by AtomicStryker** [comment]
Ruins only "registers" the chest to have a certain loot seed. I think your problem lies in another mod.
