### ISSUE TITLE
Any ways to not let The Wither boss get infernal?

### ISSUE THREAD

**Issue by Gbergz** [AtomicStryker/atomicstrykers-minecraft-mods#326]
I've looked in the Config & could only find an entry to disable the Ender Dragon to not be infernal.

Is it;
    "WitherSkeletonEntity": true,
To false?

?
~ Gbergz

**Comment by AtomicStryker** [comment]
Yes. That should be the technical name of it. It most definitely is in the config list.

**Comment by Gbergz** [comment]
Alright I disabled it but it still spawns as an Infernal. I did the testing.
Not sure if there's an entry to disable The Wither as an Infernal.

**Comment by Gbergz** [comment]
Ignore this, i added this entry to the Config; "WitherEntity": false, & it's now solved they do not longer spawn as Infernals. This wasn't there from the beginning just letting you know.

EDIT: AGAIN after regenerating the config its there. Sorry lol

**Comment by AtomicStryker** [comment]
Entries are added to the config as they are first encountered.
