### ISSUE TITLE
NPCs are not deleted on the forge server 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [AtomicStryker/atomicstrykers-minecraft-mods#327]
Hello!
I love your mod! I love hardcore builds and your mod comes first!
There is one suggestion ...
I play on the forge server 1.12.2 and I have problems there. The fact is that NPCs created by mini-bosses will not heal over time. In particular, this applies to silverfish. And over time, the server begins to slow down from this.
Can you make them drop like other NPCs?

**Comment by AtomicStryker** [comment]
Are you trying to get them to regenerate, or stop them from regenerating? Your description is unclear.

Set SilverFish to never be Infernal? Otherwise you would have to use a different mod to kill them off periodically, i guess.
