### ISSUE TITLE
Cant get to main menu in 1.14 - java.lang.illegal.stateexception ... string at line 1 was column 3

### ISSUE THREAD

**Issue by Aceyfacey** [AtomicStryker/atomicstrykers-minecraft-mods#328]
Hello!
Firstly want to say your mod is one of the best mods Ive ever come accross and have been using it since 2013, so very much appreciate you continuing updating it.

I have an issue when running it on 1.14, every time I start up minecraft before the main menu loads I get this error. I removed all mods and only had infernal mobs and still the same message. 

![image](https://user-images.githubusercontent.com/31731949/72192978-e6cf9280-3407-11ea-9a59-13ac93b9e144.png)

[2020-01-11-3.log.gz](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/4048592/2020-01-11-3.log.gz)
[debug.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/4048593/debug.log)

**Comment by Jojordi99** [comment]
I have the same problem, i can't get to the main menu. Have you found any solution?

**Comment by AtomicStryker** [comment]
For posterity, this issue is caused by an old incompatible config file still present after a version update.

**Comment by Aceyfacey** [comment]
Thanks a lot!!!
