### ISSUE TITLE
[Multi Mine][1.12] Crash when mining Better than Mods windmill

### ISSUE THREAD

**Issue by ironrosabel** [AtomicStryker/atomicstrykers-minecraft-mods#329]
Attempting to mine a windmill block from Better than Mods results in a crash. Likely to do with the unusual size of the block as I have seens similar issues with this mod in the past.

A link to the crash follows:
https://pastebin.com/dRSrfLhb

Thanks.

**Comment by AtomicStryker** [comment]
Happens when mod blocks have very custom drop logic. Best to add the block to the multimine blacklist.
