### ISSUE TITLE
Console is spammed with biome errors

### ISSUE THREAD

**Issue by CalaMariGold** [AtomicStryker/atomicstrykers-minecraft-mods#335]
The console gets spammed with biomes from BOP, it seems.

`[19:46:09] [Thread-17/INFO] [STDOUT]: [atomicstryker.ruins.common.FileHandler:readPerWorldOptions:349]: Did not find Matching Biome for config string: [badlands]`

I tried removing the biomes from the config as well as removing the biome files, did not fix it.

**Comment by democat3457** [comment]
After removing the biomes from the config, you have to create a new world or replace the `ruins.txt`s that are stored in the save folder as well as each dimension folder.
