### ISSUE TITLE
1.8.8 DL link

### ISSUE THREAD

**Issue by JohnRohner** [AtomicStryker/atomicstrykers-minecraft-mods#34]
There is no download link for the 1.8.8 version of Battle Towers on the AtomicStryker.net web site.

It is available via Minecraftsix.com, however.

Thanks for the recent updates to the latest forge,   I particularly love infernal mobs.

**Comment by AtomicStryker** [comment]
Well either they built their own update to 188 or that link points to a virus or whatever. Regardless of them making money off my work (i presume?), there is no version for 188 i've uploaded anywhere because there is a major unresolved bug with the golem falling through the floor when hit.
