### ISSUE TITLE
[DynamicLights 1.12] Floodlights not working

### ISSUE THREAD

**Issue by AzureDoom** [AtomicStryker/atomicstrykers-minecraft-mods#346]
Version: 1.4.9 I'm guessing by the mod list
MC: 1.12.2
Forge: 14.23.5.2847

Issue: Floodlight on Ender Eye isn't working, all other light types are working (dropping torch, holding glowstone, etc.). Seems just Floodlight isn't working. 

Debug Log: https://gist.github.com/AzureDoom/e62d7d583b98467440b483b4bb5072d5
Latest Log: https://gist.github.com/AzureDoom/3b7ff3883210a474bef00b575834fbe7

**Comment by Doubleumc** [comment]
Minecraft: `1.12.2`
Forge: `14.23.5.2854`
Dynamic Lights: `1.4.9` via mod list

I am having an identical issue as above. Dropped items, held items, worn items etc work as expected, but anything defined as Floodlight fails to produce illumination.

This is on a vanilla Minecraft install, no mods save for Dynamic Lights.

Latest Log: [latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/4639659/latest.log)
