### ISSUE TITLE
[Ruins] Constantly generate "crash" logs while the server is running

### ISSUE THREAD

**Issue by Traktool** [AtomicStryker/atomicstrykers-minecraft-mods#348]
I'm using the last 1.15 version and the mod generate every 5 / 10 minutes this log :
`[mException in thread "Thread-1186" [32m[12:25:11] [Thread-1186/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: Ruins crashed trying to access file .\world\RuinsPositionsFile.txt_writing
[m[32m[12:25:11] [Thread-1186/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:  at atomicstryker.ruins.common.RuinGenerator$FlushThread.doFlush(RuinGenerator.java:369)
[m[32m[12:25:11] [Thread-1186/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:  at atomicstryker.ruins.common.RuinGenerator$FlushThread.run(RuinGenerator.java:322)
[mException in thread "Thread-1189" [32m[12:30:11] [Thread-1189/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: Ruins crashed trying to access file .\world\RuinsPositionsFile.txt_writing
[m[32m[12:30:11] [Thread-1189/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:  at atomicstryker.ruins.common.RuinGenerator$FlushThread.doFlush(RuinGenerator.java:369)
[m[32m[12:30:11] [Thread-1189/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:  at atomicstryker.ruins.common.RuinGenerator$FlushThread.run(RuinGenerator.java:322)
[mException in thread "Thread-1196" [32m[12:40:11] [Thread-1196/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: Ruins crashed trying to access file .\world\RuinsPositionsFile.txt_writing
[m[32m[12:40:11] [Thread-1196/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:  at atomicstryker.ruins.common.RuinGenerator$FlushThread.doFlush(RuinGenerator.java:332)
[m[32m[12:40:11] [Thread-1196/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:  at atomicstryker.ruins.common.RuinGenerator$FlushThread.run(RuinGenerator.java:322)`

I don't know why, but maybe something wrong in your generate code
Mod seems to work fine, so I don't know
The server doesn't crash, just generate this logs every 5 / 10 minutes
Hope it's helping

**Comment by QuarterAnimal** [comment]
I can't reproduce the problem, but I took a crack at fixing it. Are you able to test it? You'll have to either build it yourself or wait for the next 1.15 Ruins release.
