### ISSUE TITLE
Server Crash 1.8.9

### ISSUE THREAD

**Issue by cauliflower69** [AtomicStryker/atomicstrykers-minecraft-mods#35]
http://pastebin.com/pz5ivivN

**Comment by AtomicStryker** [comment]
The actual culprit is a coremod, specifically at net.ilexiconn.llibrary.common.asm.ASMHelper.createClassNode. Also, Necromancy isnt for 1.8.9????

**Comment by cauliflower69** [comment]
My apologies - It is this mod that caused the issue http://minecraft.curseforge.com/projects/necromancyplus/files
