### ISSUE TITLE
[MultiMine] - java.lang.ArrayIndexOutOfBoundsException: -10

### ISSUE THREAD

**Issue by 04Slash** [AtomicStryker/atomicstrykers-minecraft-mods#357]
Forge/Mods:
forge-1.12.2-14.23.5.2838.jar OR forge-1.12.2-14.23.5.2854.jar
MultiMine-1.12.2.jar - (Uploaded to CF on Sep 21, 2019, or "latest")
WearableBackpacks-1.12.2-3.1.4.jar

0. Alternatively to step 1-6 create the config file manually with the given pastebin in step 7.
1. Start Minecraft with the above 2 mods and load into a creative world.
2. Cheat in a backpack and a chestplate. Place the backpack and wear the chestplate.
3. Hold crouch
4. Start punching/mining the backpack - Don't stop
5. Uncrouch
6. Close the game.
7. Edit multimine.cfg and set `B:"wearablebackpacks:backpack-0"=true` under bannedblocks* Config - https://pastebin.com/5y5PiCyw
8. Repeat steps 3-5.
9. Crash
*I have replicated this crash without this setting however setting this from false to true seemed to cause a crash every single time as opposed to rarely.

Crash report - https://pastebin.com/XBtHg4D7

[I have reported this to the WB dev](https://github.com/copygirl/WearableBackpacks/issues/135) but they mentioned the mod may not receive any more updates. Hopefully you guys can do something on your end. If you need me to test anything for you or need anymore information from me let me know.

**Comment by AtomicStryker** [comment]
Oof. Some kind of rendering issue. I dont understand how banning the block for Multi Mine could possibly make it worse... unless most of the issue is on WBs end ... will look into it later today, at home, where i can check the MC source stack
