### ISSUE TITLE
Ninja/Ender mobs do not respect teleport suppression

### ISSUE THREAD

**Issue by gmoff01** [AtomicStryker/atomicstrykers-minecraft-mods#358]
Mod items that suppress enderman teleportation (the RF tools environmental controller or the dark utilities ender tether, etc) do not work on Ninja / Ender mobs from this mod.  I gather there is an event that should be fired when teleporting happens for this to work?

**Comment by AtomicStryker** [comment]
Added this forge event hook in commit e3c2337 and pushed Infernal Mobs 1.15.2.1 to curse

**Comment by gmoff01** [comment]
Thank you!

**Comment by Ryonez** [comment]
@AtomicStryker 

Having this same issue with EnderIO's Inhibitor Obelisk. We're running Minecraft 1.12.2, with an Infernal Version that was made after this commit went out.

**Comment by AtomicStryker** [comment]
Sorry, i don't support such old versions.

**Comment by Ryonez** [comment]
Sorry to hear that. Thank you for the response though.
