### ISSUE TITLE
(Feature Request)  Prevent certain combinations of attributes

### ISSUE THREAD

**Issue by Catlord-3** [AtomicStryker/atomicstrykers-minecraft-mods#368]
I was just wanting to ask to allow you to blacklist a certain combination of attributes. I am requesting this because Sticky and Storm are super unfair together. what happens is they strike you with lightning, knocking the item out of your hand, and it instantly gets deleted. This really seems unbalanced and like it should not be a thing, maybe add also a "protection" for items that are dropped by sticky for like 5 seconds, like a nether star, so they cannot be destroyed by things like that. Thank you for reading this and i hope you consider it.

**Comment by AtomicStryker** [comment]
Infernal Mobs request - for which MC version are you asking?
There is actually code for this, but i don't think i actually implemented this for any modifiers.
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/aebf7a633a412a31f9098aa5a384cbfd70cfc346/InfernalMobs/src/main/java/atomicstryker/infernalmobs/common/MobModifier.java#L338

EDIT:
No, Webber does in fact not mix with Gravity or Blastoff. I can make Sticky not mix with Storm, sure.

**Comment by AtomicStryker** [comment]
Implemented for 1.16.2 as of commit https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/3b65428ffdbeafb4637cc56036722ece4b999eca, i have pushed 1.16.2.1 of Infernal Mobs to curse
