### ISSUE TITLE
[1.12.2] Tower Golems Not Spawning

### ISSUE THREAD

**Issue by vizthex123** [AtomicStryker/atomicstrykers-minecraft-mods#370]
Title. It seems to only be triggered when the Floor 9 chest i opened, but I personally don't open chests. I just break them.

Could you add a trigger on the staircase or something? That way the boss still spawns so I don't have to manually destroy the tower?

**Comment by AtomicStryker** [comment]
Nah, sorry. Keeping track on whether or not the golem spawned, is there, or should spawn now would be a can of worms ill happily avoid. They spawn with the tower, this can fail, i am fine with that.
