### ISSUE TITLE
Update and Fix your old Stalker Creepers mod...

### ISSUE THREAD

**Issue by MagmaSlime123** [AtomicStryker/atomicstrykers-minecraft-mods#375]
The mod does not load as if its not even in my mods folder. However it IS in my mods folder. Using 1.12.2, Forge 2854.

**Comment by AtomicStryker** [comment]
Stalker Creepers is a coremod only, which means you won't necessarily see it in the loaded mods list. Check your FML/Forge log files, specifically the startup section, and you will see how it loads or fails. I no longer support 1.12.2
