### ISSUE TITLE
MultiMine and Better with mods crashing.

### ISSUE THREAD

**Issue by Nyctoniac** [AtomicStryker/atomicstrykers-minecraft-mods#376]
Turns out if you have multi mine and you break a windmill or something of the sort in BWM.
You crash the game. I'm currently making a modpack and I love both mods, and I'd hate to remove either one.

**Comment by AtomicStryker** [comment]
Multi Mine has a block blacklist to deal with such problems?

**Comment by Nyctoniac** [comment]
I tried that but it didn't work. Either that or I did it wrong.

**Comment by DoctorNutmeg** [comment]
Just popping in to confirm that the blacklist doesn't seem to resolve this issue, I play a modpack that used to have Multi Mine but removed it specifically because of this bug.
