### ISSUE TITLE
[Infernal Mobs] Completely removing mod does not stop mob spawning (1.16.1)

### ISSUE THREAD

**Issue by jmmd2000** [AtomicStryker/atomicstrykers-minecraft-mods#377]
Minecraft 1.16.1
Forge Version 32.0.108

I decided to remove this mod from my modpack as I did not like the way it was interfering with mob farms and after closing the game, completely removing the jar from the mods folder and restarting the game, mobs with these attributes still spawn in my world. I checked and doublechecked that it was removed and it is gone, but these mobs still spawn

**Comment by AtomicStryker** [comment]
Infernal Mobs stores the modifiers permanently in the entity data, where they persist even if the mod is removed. However, without the mod, none of the Abilities can trigger or actually do anything. If you are still seeing abilities, you did not remove the mod successfully.

**Comment by jmmd2000** [comment]
> Infernal Mobs stores the modifiers permanently in the entity data, where they persist even if the mod is removed. However, without the mod, none of the Abilities can trigger or actually do anything. If you are still seeing abilities, you did not remove the mod successfully.

I removed the jar from the mods folder and removed the config file, I was testing an enderman farm when I decided to remove it and after removing I haven't noticed any particular abilities except for the poison one. Is there something else I should be removing or another way to remove it? 
Also in the main menu the number of mods dropped from 134 to 133 after removal so the game doesn't seem to be detecting it
