### ISSUE TITLE
[1.16.1] [Infernal Mobs] Server crash upon startup.

### ISSUE THREAD

**Issue by SwanX1** [AtomicStryker/atomicstrykers-minecraft-mods#378]
Server log:
```
10.11 15:51:53 [Server] Startup [minecraft/DedicatedServer]: Done (11.817s)! For help, type "help"
10.11 15:51:53 [Server] Server thread/INFO [co.da.we.WeaponThrow/]: HELLO from server starting
10.11 15:51:53 [Server] Server thread/ERROR [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $
```
Full crash report:
[crash-2020-11-10_15.51.53-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/5518519/crash-2020-11-10_15.51.53-server.txt)

**Comment by AtomicStryker** [comment]
GsonConfig.loadConfigWithDefault -> Expected BEGIN_OBJECT but was STRING at line 3 column 1 path

Your config is invalid. Try deleting it and letting it regenerate.
