### ISSUE TITLE
BATTLE TOWER 1.12.2

### ISSUE THREAD

**Issue by damionbbbb** [AtomicStryker/atomicstrykers-minecraft-mods#379]
hey so irecently made a server formy friends and I to play on and I wanted to put modded loot in the towers and this happened

---- Minecraft Crash Report -------- Minecraft Crash Report ----
WARNING: coremods are present:  ForgelinPlugin (Forgelin-1.8.3.jar)  llibrary (llibrary-core-1.0.11-1.12.2.jar)  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)  LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)Contact their authors BEFORE contacting forge
// Why did you do that?
Time: 11/12/20 6:00 PMDescription: Exception in server tick loop
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Battle Towers (battletowers)Caused by: java.lang.NumberFormatException: For input string: "" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.lang.Integer.parseInt(Integer.java:592) at java.lang.Integer.parseInt(Integer.java:615) at atomicstryker.battletowers.common.TowerStageItemManager.<init>(TowerStageItemManager.java:58) at atomicstryker.battletowers.common.AS_BattleTowersCore.modsLoaded(AS_BattleTowersCore.java:184) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754) at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- System Details --Details: Minecraft Version: 1.12.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_201, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 6558647336 bytes (6254 MB) / 8130134016 bytes (7753 MB) up to 8130134016 bytes (7753 MB) JVM Flags: 2 total; -Xms8000M -Xmx8000M IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP 9.42 Powered by Forge 14.23.5.2854 43 mods loaded, 43 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
| State | ID                  | Version                  | Source                                        | Signature                                | |:----- |:------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- | | LCHIJ | minecraft           | 1.12.2                   | minecraft.jar                                 | None                                     | | LCHIJ | mcp                 | 9.42                     | minecraft.jar                                 | None                                     | | LCHIJ | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 | | LCHIJ | forge               | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 | | LCHIJ | bspkrscore          | 7.6.0.1                  | [1.12]bspkrsCore-universal-7.6.0.1.jar        | None                                     | | LCHIJ | treecapitator       | 1.43.0                   | [1.12]TreeCapitator-client-1.43.0.jar         | None                                     | | LCHIJ | asr                 | 1.0                      | asgardshieldreloaded-1.12.2-1.0.jar           | None                                     | | LCHIE | battletowers        | 1.6.5                    | BattleTowers-1.12.2.jar                       | None                                     | | LCHI  | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     | | LCHI  | bookshelf           | 2.3.557                  | Bookshelf-1.12.2-2.3.557.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 | | LCHI  | jei                 | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     | | LCHI  | thaumcraft          | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     | | LCHI  | botania             | r1.10-361                | Botaniar1.12.2.jar                            | None                                     | | LCHI  | buildcraftlib       | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | buildcraftcore      | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | buildcraftbuilders  | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | buildcrafttransport | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | buildcraftsilicon   | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | ic2                 | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 | | LCHI  | buildcraftcompat    | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | buildcraftenergy    | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | buildcraftfactory   | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | buildcraftrobotics  | 7.99.24.7                | buildcraft-all-7.99.24.7.jar                  | None                                     | | LCHI  | damageindicatorsmod | 1.0                      | Damage-Indicators-Mod-1.12.2.jar              | None                                     | | LCHI  | eplus               | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 | | LCHI  | extrabows           | v1.12.2 b13              | extrabows-v1.12.2+b13.jar                     | None                                     | | LCHI  | forgelin            | 1.8.3                    | Forgelin-1.8.3.jar                            | None                                     | | LCHI  | librarianlib        | 4.22                     | librarianlib-1.12.2-4.22.jar                  | None                                     | | LCHI  | hooked              | %VERSION%                | hooked-1.0.3.jar                              | None                                     | | LCHI  | ichunutil           | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 | | LCHI  | infernalmobs        | 1.7.5                    | InfernalMobs-1.12.2.jar                       | None                                     | | LCHI  | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe | | LCHI  | journeymap          | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                   | None                                     | | LCHI  | mantle              | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     | | LCHI  | moarmors            | 1.0.0                    | Mo'Armors+V.1.6+[1.12.2].jar                  | None                                     | | LCHI  | natura              | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                    | None                                     | | LCHI  | portalgun           | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 | | LCHI  | llibrary            | 1.7.19                   | llibrary-1.7.19-1.12.2 (1).jar                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec | | LCHI  | dragonmounts        | 1.12.2-1.5.8             | Realm-of-The-Dragons-Mod-1.12.2.jar           | None                                     | | LCHI  | spartanshields      | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar               | None                                     | | LCHI  | travelersbackpack   | 1.0.34                   | TravelersBackpack-1.12.2-1.0.34.jar           | None                                     | | LCHI  | twilightforest      | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     | | LCHI  | librarianliblate    | 4.22                     | librarianlib-1.12.2-4.22.jar                  | None                                     |
Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.3.jar)  llibrary (llibrary-core-1.0.11-1.12.2.jar)  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcherInventory Tweaks Coremod (InventoryTweaks-1.63.jar)  invtweaks.forge.asm.ContainerTransformerLibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)  com.teamwizardry.librarianlib.asm.LibLibTransformer Pulsar/natura loaded Pulses:  - NaturaCommons (Enabled/Forced) - NaturaOverworld (Enabled/Not Forced) - NaturaNether (Enabled/Not Forced) - NaturaDecorative (Enabled/Not Forced) - NaturaTools (Enabled/Not Forced) - NaturaEntities (Enabled/Not Forced) - NaturaOredict (Enabled/Forced) - NaturaWorld (Enabled/Not Forced)
Profiler Position: N/A (disabled) Is Modded: Definitely; Server brand changed to 'fml,forge' Type: Dedicated Server (map_server.txt)

config file

# Configuration file

battletowerchestitems {
S:"Floor 1"=stick-0-75-5-6;wheat_seeds-0-75-3-5;planks-0-75-5-6;reeds-0-75-3-5;stone_pickaxe-0-50-1-1;stone_axe-0-50-1-1;torch-0-45-3-3;stone_button-0-50-2-2;moarmors:tinpickaxe-0-50-1-2;moarmors:tinaxe-0-50-1-2;spartanshields:shield_tower_tin-0-40-1-2;spartanshields:shield_basic_tin-0-40-1-2;spartanshields:shield_basic_copper-0-60-1-2;moarmors:copperpickaxe-0-60-1-2;moarmors:copperaxe-0-60-1-2;asr:stone_giant_sword-0-50-1-2;hooked:hook-0-30-1-2;string-0-50-3-6;fishing_rod-0-25-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-10-1-2;extrabows:stone_bow-0-40-1-2;ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32
S:"Floor 2"=stick-0-45-5-25;wheat_seeds-0-25-3-5;planks-0-35-5-64;reeds-0-15-3-5;torch-0-45-3-32;moarmors:tinpickaxe-0-20-1-2;moarmors:tinaxe-0-20-1-2;spartanshields:shield_tower_tin-0-30-1-2;spartanshields:shield_basic_tin-0-30-1-2;hooked:hook-0-30-1-2;fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-20-1-2;extrabows:stone_bow-0-40-1-2;ic2:ingot-0-30-1-32;ic2:ingot-0-30-1-32;bowl-0-25-2-4;coal-0-90-4-16;string-0-80-5-10;wool-0-55-2-2;iron_helmet-0-15-1-2;iron_chestplate--0-10-1-2;iron_leggings-0-10-1-2;iron_boots-0-15-1-2;spartanshields:shield_tower_iron-0-10-1-2;spartanshields:shield_basic_iron-0-10-1-2;
S:"Floor 3"=stick-0-45-5-25;torch-0-45-3-32;hooked:hook-0-30-1-2;fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-20-1-2;extrabows:stone_bow-0-30-1-2;coal-0-90-4-16;string-0-80-5-10;wool-0-55-2-2;iron_ingot-0-20-1-32;asr:iron_giant_sword-0-20-1-2;iron_helmet-0-30-1-2;iron_chestplate-0-20-1-2;iron_leggings-0-20-1-2;iron_boots-0-30-1-2;spartanshields:shield_tower_iron-0-20-1-2;spartanshields:shield_basic_iron-0-20-1-2;glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2;extrabows:iron_bow-0-25-1-2;extrabows:double_upgrade-0-10-1-1;extrabows:triple_upgrade-0-05-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-45-1-32;
S:"Floor 4"=brown_mushroom-0-75-2-2;red_mushroom-0-75-2-2;sapling-0-20-3-3;wheat-0-35-4-4;stick-0-45-5-25;torch-0-45-3-32;hooked:hook-0-30-1-2;fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-20-1-2;extrabows:stone_bow-0-50-1-2;coal-0-90-4-16;string-0-80-5-10;wool-0-55-2-2;iron_ingot-0-40-1-32;asr:iron_giant_sword-0-40-1-2;iron_helmet-0-40-1-2;iron_chestplate--0-30-1-2;iron_leggings-0-30-1-2;iron_boots-0-40-1-2;spartanshields:shield_tower_iron-0-40-1-2;spartanshields:shield_basic_iron-0-40-1-2;glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2;extrabows:iron_bow-0-30-1-2;extrabows:double_arrow_upgrade-0-20-1-1;extrabows:triple_arrow_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-45-1-32;
S:"Floor 5"=brown_mushroom-0-55-2-2;red_mushroom-0-55-2-2;sapling-0-10-3-3;wheat-0-15-4-4;sign-0-50-1-2;pumpkin_seeds-0-60-2-2;melon_seeds-0-60-3-3;stick-0-45-5-25;torch-0-45-3-32;hooked:hook-0-30-1-2;fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-25-1-2;extrabows:stone_bow-0-50-1-2;coal-0-90-4-16;string-0-80-5-10;wool-0-55-2-2;iron_ingot-0-50-1-32;asr:iron_giant_sword-0-50-1-2;iron_helmet-0-50-1-2;iron_chestplate--0-40-1-2;iron_leggings-0-50-1-2;iron_boots-0-50-1-2;spartanshields:shield_tower_iron-0-50-1-2;spartanshields:shield_basic_iron-0-50-1-2;glass-0-75-3-3;feather-0-75-4-4;bread-0-75-2-2;apple-0-75-2-2;extrabows:iron_bow-0-40-1-2;extrabows:double_arrow_upgrade-0-20-1-1;extrabows:triple_arrow_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-45-1-32;
S:"Floor 6"=pumpkin_seeds-0-60-2-2;melon_seeds-0-60-3-3;gunpowder-0-75-3-3;leather-0-75-4-4;fish-0-75-3-3;dye-0-60-1-2fishing_rod-0-15-1-2;carrot-0-50-8-12;travelersbackpack:travelers_backpack-0-30-1-2;extrabows:stone_bow-0-30-1-2;coal-0-20-4-16;string-0-40-5-10;wool-0-25-2-2;iron_ingot-0-10-1-32;asr-1.12.2-1.0:iron_giant_sword-0-20-1-2;iron_helmet-0-20-1-2;iron_chestplate--0-10-1-2;iron_leggings-0-20-1-2;iron_boots-0-10-1-2;extrabows:iron_bow-0-35-1-2;extrabows:double_upgrade-0-20-1-1;extrabows:triple_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-45-1-32;
S:"Floor 7"=gunpowder-0-45-3-3;leather-0-45-4-4;fish-0-15-3-3;dye-0-05-1-2;chainmail_helmet-0-20-1-1;chainmail_chestplate-0-10-1-1;chainmail_leggings-0-10-1-1;chainmail_boots-0-20-1-1;hooked:hook-0-25-1-2;travelersbackpack:travelers_backpack-0-30-1-2;extrabows:iron_bow-0-30-1-2;extrabows:double_upgrade-0-20-1-1;extrabows:triple_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows-:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge_upgrade-0-25-1-1;rubber-0-45-1-32;ChestGenHook:chests/simple_dungeon:3
S:"Floor 8"=chainmail_helmet-0-40-1-1;chainmail_chestplate-0-40-1-1;chainmail_leggings-0-40-1-1;chainmail_boots-0-40-1-1;travelersbackpack:travelers_backpack-0-30-1-2;extrabows:iron_bow-0-35-1-2;extrabows:double_upgrade-0-20-1-1;extrabows:triple_upgrade-0-10-1-1;extrabows:lightning_upgrade-0-05-1-1;extrabows:fire_upgrade-0-05-1-1;extrabows:ender_upgrade-0-05-1-1;extrabows:freeze_upgrade-0-15-1-1;extrabows:explosive_upgrade-0-05-1-1;extrabows:healing_from_damage_upgrade-0-10-1-1;extrabows:arrow_cost_upgrade-0-25-1-1;extrabows:water_upgrade-0-15-1-1;extrabows:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-05-1-1;extrabows:meteor_upgrade;extrabows:electric_upgrade-0-05-1-1;extrabows:bridge;upgrade-0-25-1-1;rubber-0-25-1-32;ChestGenHook:chests/simple_dungeon:3
S:"Floor 9"=travelersbackpack:travelers_backpack-0-30-1-2;extrabows:emerald_bow-0-40-1-2;moarmors:emeraldarmorhelmet-0-30-1-2;moarmors:emeraldarmorbody-0-15-1-2;moarmors:emeraldarmorlegs-0-15-1-2;moarmors:emeraldarmorboots-0-30-1-2;extrabows:iron_bow-0-40-1-2;extrabows:double_upgrade-0-30-1-1;extrabows:triple_upgrade-0-15-1-1;extrabows:lightning_upgrade-0-10-1-1;extrabows:fire_upgrade-0-10-1-1;extrabows:ender_upgrade-0-10-1-1;extrabows:freeze_upgrade-0-20-1-1;extrabows:explosive_upgrade-0-10-1-1;extrabows:healing_from_damage_upgrade-0-15-1-1;extrabows:arrow_cost_upgrade-0-30-1-1;extrabows:water_upgrade-0-20-1-1;extrabows:push_upgrade-0-15-1-1;extrabows:flying_upgrade-0-10-1-1;extrabows:meteor_upgrade-0-10-1-1;extrabows:electric_upgrade-0-10-1-1;extrabows:bridge;upgrade-0-35-1-1;rubber-0-35-1-32;ender_pearl-0-30-2-2;diamond-0-70-2-2;redstone-0-75-5-5;gold_ingot-0-50-8-8;ChestGenHook:chests/simple_dungeon:5
S:"Item Generations per Floor"=15
S:"Top Floor"=ender_pearl-0-50-2-2;diamond-0-70-2-5;redstone-0-75-5-20;gold_ingot-0-90-8-32;;travelersbackpack:travelers_backpack-0-40-1-2;extrabows:emerald_bow-0-30-1-2;moarmors:emeraldarmorhelmet-0-50-1-2;moarmors:emeraldarmorbody-0-40-1-2;moarmors:emeraldarmorlegs-0-50-1-2;moarmors:emeraldarmorboots-0-50-1-2;extrabows:double_upgrade-0-40-1-1;extrabows:triple_upgrade-0-20-1-1;extrabows:lightning_upgrade-0-10-1-1;extrabows:fire_upgrade-0-10-1-1;extrabows:ender_upgrade-0-10-1-1;extrabows:freeze_upgrade-0-25-1-1;extrabows:explosive_upgrade-0-10-1-1;extrabows:healing_from_damage_upgrade-0-20-1-1;extrabows:arrow_cost_upgrade-0-45-1-1;extrabows:water_upgrade-0-30-1-1;extrabows-:push_upgrade-0-10-1-1;extrabows:flying_upgrade-0-10-1-1;extrabows:meteor_upgrade-0-10-1-1;extrabows:electric_upgrade-0-10-1-1;extrabows:bridge_upgrade-0-45-1-1;rubber-0-45-1-32;ChestGenHook:chests/simple_dungeon:7
}

 

biomespawnallowed {
B:extreme_hills=true
B:river=true
B:roofed_forest=true
}

 

chunkproviderallowed {
B:ChunkProviderServer=true
}

 

mainoptions {
I:"Minimum Distance between 2 BattleTowers"=196
I:"Minimum Distance of Battletowers from Spawn"=96
I:"Tower Destroying Enabled"=1
I:chanceTowerIsUnderGround=15
B:noGolemExplosions=false

# Destroy all Mob Spawners in Tower Area upon Tower Fall?
B:towerFallDestroysMobSpawners=false
}

**Comment by AtomicStryker** [comment]
Your config file is missing a number somewhere. I suggest the binary approach - remove half, boot. If it works the error is in the other half. If you have the half with the error somewhere, halve it again. And so on until you pinpoint the problem, and then it should be obvious.

**Comment by D0CTOR-ZED** [comment]
ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32;ic2:ingot-0-50-1-32
S:"Floor 2"=stick-0-45-5-25;

I'm guessing a missing semicolon between the 32 and the S.

Don't mind me, just passing through.
