### ISSUE TITLE
Atomic Stryker, do you still have your mods for ≤ 1.5.2?

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#381]
Hello, sorry for using this repository, but this was the best way I found to contact you.
Do you still have your old mods stored for Minecraft b1.7.3, 1.0.0, 1.1, 1.2.5, 1.4.7 and 1.5.2? Some of the mods I'm after are:

Ropes+
Minions
Ruins
Battle Towers
Finder Compass
Dynamic Lights
Kenshiro
Multimine
Infernal Mobs
Pet Bat
Magic Yarn
Stalker Creepers
Simply Hax
Finder Compass

Some of these mods are in AMCO modpacks, but after 1.4.7, only a few modpacks ever included these mods. I can find a few Dropbox links scattered about, but most of them were in SugarSync (and Dropbox broke lots of links after 2015/2016. As far as I know, the files are still stored, but the sharing links have to be remade). 

There are also some 1.2.5 mods which you helped maintain, such as Minefactory Reloaded, Nether Ores and Power Converters, listed [here](https://web.archive.org/web/20120808001247/http://www.atomicstryker.net/maintainedmods.html).

Thank you either way.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/github.io/tree/master/files/archive

This is what i have from a decade ago. Enjoy
