### ISSUE TITLE
crashes on startup [1.15.2]

### ISSUE THREAD

**Issue by JawayWu** [AtomicStryker/atomicstrykers-minecraft-mods#382]
I added the in control! mod (mob spawning control)and it crashed the server on startup with this error, and after removing it the error persists. 
Is there any way to fix this?

[debug.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/5753751/debug.log)

**Comment by JawayWu** [comment]
*this is for Infernal Mobs

**Comment by AtomicStryker** [comment]
java.lang.NullPointerException
	at atomicstryker.infernalmobs.common.InfernalMobsCore.stringToMobModifiers(InfernalMobsCore.java:487)

That other mod apparently damaged or atleast changed the entity metadata Infernal Mobs uses to store infernal modifiers. The only way to "fix" the savefile would be to delete the Infernal Mobs metadata from the entities.

**Comment by JawayWu** [comment]
How would you delete the metadata from the entities? And I'm guessing that there would be no way to restore them? Would that break infernal mobs?

**Comment by AtomicStryker** [comment]
Try https://github.com/jaquadro/NBTExplorer

But i had another look at your crashlog and it doesnt actually look like it reached the save data at all. For some reason your entity loads before Infernal Mobs is initialized ... huh. I'll add some code to fix this and push a version...

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/eaf06d546310d3d7139a7458ce33d095218ec462

1.15.2.3 should show up in curse shortly
