### ISSUE TITLE
Prevent players to cheese

### ISSUE THREAD

**Issue by daalfa** [AtomicStryker/atomicstrykers-minecraft-mods#383]
I would suggest to move the spawners and the chest towards the center of the tower or put some obsidian in front of them.
It is quite easy to cheese early in game.

**Comment by AtomicStryker** [comment]
It sounds like you are commenting on a Ruins template? Or maybe Battletowers? Who knows? Not me :)
If you have balancing concerns with either, you can change the configs and/or templates to reduce the rewards player can cheese.
