### ISSUE TITLE
BUG: Mobs already existing in the world can become infernal upon reloading world

### ISSUE THREAD

**Issue by AzureMonument** [AtomicStryker/atomicstrykers-minecraft-mods#384]
So I've recently set up a villager breeder in my singleplayer world, and got a couple of zombies (non-infernal) to be permanently in the back. However, when I logged on this morning, both zombies were for some reason infernal? One had alchemist, cloaking, blastoff and ender, and the other had berserk, webbing, and sprint. Confused I exited and returned to main menu, then opened the configs to check if there was anything allowing that. Nothing popped up, so I logged back in. This time the zombies weren't infernal! 

I've since tried reloading the world several times, and while rare (as in it took me 30 reloads), I've managed to get one of the zombies to become infernal again. 

Actually, it looks like both of them became infernal again, and even got the exact same traits.
![2021-02-19_08 29 35](https://user-images.githubusercontent.com/43318292/108510624-c3267f00-728c-11eb-9b5b-7874a4e7ce9d.png)
![2021-02-19_08 29 45](https://user-images.githubusercontent.com/43318292/108510682-d0dc0480-728c-11eb-9b4d-caf0c0a5a02d.png)

Reloading again removed their infernal status.
![2021-02-19_08 31 59](https://user-images.githubusercontent.com/43318292/108510838-02ed6680-728d-11eb-8ad0-868926ac7882.png)
![2021-02-19_08 32 03](https://user-images.githubusercontent.com/43318292/108510843-04b72a00-728d-11eb-874b-b5407759a734.png)

**Comment by AtomicStryker** [comment]
Which version of MC is this? Which version of Infernal Mobs?
Also i note you clearly have other mods running, probably a whole lot of them, any one of which could be interfering.

I think the hook upon which Infernal Mobs tries to infernalize entities was meant to only be called on "natural" spawns and not on loading entities into the world - which appears to be happening here.

You also have the twin phenomenon that already-present infernal data (stored in an entities NBT tags) does not appear to load correctly - once an entity is infernal, it should stay infernal in any subsequent load of that savefile.

**Comment by AzureMonument** [comment]
1.16.5 is the MC version. 
The version of infernal mobs is 1.16.2.1

It could very well be a compat. Also, I noticed it mostly only happens whenever you load the world after starting the game. (full close and restart). If you just restart without quitting the game the infernal thing goes away.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/04991d47b320295e74b60fb16a00ee4110663b8f
So, after some unexpected effort (hours ._.) i think i have it fixed, and possibly introduced new bugs.

Would you mind playtesting this a little before i unleash it on curseforge: It is possible specific mod network exchanges could crash that were previously stable.

Its a .jar renamed to .zip

[infernalmobs-1.16.2.2.zip](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/6057891/infernalmobs-1.16.2.2.zip)
