### ISSUE TITLE
Question: How do I include ores with metadata - FinderCompass-1.12.1.jar

### ISSUE THREAD

**Issue by AbieTheFishman** [AtomicStryker/atomicstrykers-minecraft-mods#386]
I'm trying to add entries for Thermal Foundation ores.

The only one I can add is copper
-  thermalfoundation:ore

All others will not register, my guess is due to the :metadata  and not parsing correctly. 

Tin for example is:
- thermalfoundation:ore:1

I've tried a bunch of variations
- <thermalfoundation:ore:1>
- thermalfoundation:ore/1
- thermalfoundation:ore.1
- thermalfoundation:ore@1
- thermalfoundation:ore#1

Any guidance would be appreciated.

Thanks

**Comment by AtomicStryker** [comment]
The config file itself should contain the help regarding this. Post your entire line. Metadata is "damageDropped"

BlockID:R:G:B:ScanrangeHor:ScanrangeVer:MinBlockY:MaxBlockY:boolDelayed[:damageDropped]

If you are using thermalfoundation:ore as blockId i see a problem right away 🤣 

Looking at thermal foundation source the unlocalized name is "ore". Try that.

`ore:130:130:130:15:1:1:100:0:1`

**Comment by AbieTheFishman** [comment]
Yep that's it! Thanks.

```
// - copper
thermalfoundation:ore:255:178:55:15:1:1:100:0:0
//
// - tin
thermalfoundation:ore:119:183:242:15:1:1:100:0:1
//
// - silver
thermalfoundation:ore:187:240:240:15:1:1:100:0:2
//
// - lead
thermalfoundation:ore:152:151:232:15:1:1:100:0:3
//
// - nickel
thermalfoundation:ore:248:255:171:15:1:1:100:0:5
```

**Comment by AtomicStryker** [comment]
That works? Great, although i would honestly not have expected it to. The ":" in thermalfoundation:ore should cause problems with the Finder Compass config line format, but apparently it doesn't. It has been years since i made this, i dont remember.
