### ISSUE TITLE
[Ruins] How do I disable default structures?

### ISSUE THREAD

**Issue by Emmaker** [AtomicStryker/atomicstrykers-minecraft-mods#388]
The title says it all, really, but I'll explain anyways; I'm working on a Fallout modpack and want to use Ruins to spawn my own, custom Fallout structures, but I can't figure out how to prevent the default ones from spawning as well. Is there a config option or something I'm missing?

**Comment by AtomicStryker** [comment]
Remove the template files you don't want spawning from your Ruins config folders
