### ISSUE TITLE
Infernal Mob Stuck in Dying Animation (Is Invincible)

### ISSUE THREAD

**Issue by TrojanHorseForSale** [AtomicStryker/atomicstrykers-minecraft-mods#390]
Playing 1.12.2 MC with Infernal Mobs, I fought a Legendary zombie yet they seemed to be incapable of dying and stuck in the animation that colors their model red and lies horizontal on the ground. While stuck in this invulnerable state they are still able to move and attack like normal. I had to block off this glitched zombie in the photos below.

![2021-06-09_18 05 13](https://user-images.githubusercontent.com/78938350/121442968-3fcf8d00-c952-11eb-9448-ece883d34c74.png)
![2021-06-09_18 05 14](https://user-images.githubusercontent.com/78938350/121442975-41995080-c952-11eb-8929-2c586198b997.png)
![2021-06-09_18 00 52](https://user-images.githubusercontent.com/78938350/121442986-452cd780-c952-11eb-8cb5-307a47316be7.png)
![2021-06-09_18 04 15](https://user-images.githubusercontent.com/78938350/121443017-52e25d00-c952-11eb-8410-40c1de44dbc0.png)

**Comment by AtomicStryker** [comment]
Sorry, i don't support that version of MC anymore.
