### ISSUE TITLE
Multiplayer game interface error

### ISSUE THREAD

**Issue by Rcrafte22** [AtomicStryker/atomicstrykers-minecraft-mods#391]
Minecraft Version :1.16.5

Operating System :Windows 11

Logs : no logs

Steps to Reproduce :
1.Add Dynamic Lights to the client

Description of issue :The multiplayer interface will indicate that FML is not compatible, but it can still enter the server normally
![error](https://user-images.githubusercontent.com/39120466/126434364-eb7222c9-e0b5-4341-96af-80a91ddceb8e.png)

**Comment by AtomicStryker** [comment]
Hmmm i probably misconfigured something or other
