### ISSUE TITLE
How to use the mod?

### ISSUE THREAD

**Issue by xiguahaohaochio** [AtomicStryker/atomicstrykers-minecraft-mods#393]
i just buy the minecraft, and i'm completely a newbie.So I don't know how to use the mods, I already try 
to put the dymatmic lighting in the mods folder, but it doesn't work
 I use the HTML,and I also installed Forge.

**Comment by AtomicStryker** [comment]
You are running the java version, yes?
Get forge installer for your MC version from here https://files.minecraftforge.net/net/minecraftforge/forge/
Run it with java, have it install the forge client for you
copy the mod jar into the .minecraft/mods/ folder
In the MC launcher, select the Forge Minecraft version and launch it
In the MC ingame main menu, click mods and verify the mod shows up
