### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Coraline77447** [AtomicStryker/atomicstrykers-minecraft-mods#394]
The game crashed whilst exception in server tick loop
Error: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 3 column 1 path $

Minecraft: 1.17.1
Forge: 37.0.25
Infernal mobs: 1.17.1.1
Optifine Installed?: No, not compatible with forge 1.17 yet.
Crash Report: https://pastebin.com/LFeCJvrV
Log: [latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/6931480/latest.log)

**Comment by AtomicStryker** [comment]
Config file format changed slightly. Delete your old config file

... oh and old Infernal Mobs savefiles (old worlds with it) are not compatible, sorry

**Comment by Coraline77447** [comment]
Well I shouldn't have an old savefile of Infernal Mobs and world anymore cause I should have made a new world after experiencing issues with Infernal Mobs 1.17.1. 

Btw I remember when I tried Infernal Mobs for 1.14.4 and it didn't work which I wonder what was causing that issue to begin with since you've fixed that problem already. 

Anyways if I do have an old Infernal Mobs config/savefile then I'll delete it so that I can try Infernal Mobs 1.17.1 again when forge reaches stable since 37.0.34 literally "killed" 15 out of my 33 1.17 mods that I was playing with before that forge update which is/was mildly infuriating and disappointing..

**Comment by Coraline77447** [comment]
Hi, remember me? Well I may have some important info that you need to know with the 1.16.5 version of Infernal Mobs.
When I was loading into a preexisting world that the game crashed and what's causing it is the starting code which should be BEGIN_OBJECT instead of STRING.
During the firing event: java.lang.IllegalStateException that it was expecting BEGIN_OBJECT but was STRING instead at line 3 column 1 path $.
So to fix that all you need to do is to change STRING with BEGIN_OBJECT.

Btw I'm skipping 1.17 modded as a whole, so now I'm waiting for 1.18 and hopefully wouldn't run into any issues like how I had at the beginning of forge 1.17.
