### ISSUE TITLE
Add config option for Infernal Mobs number of modifiers

### ISSUE THREAD

**Issue by Angular-Angel** [AtomicStryker/atomicstrykers-minecraft-mods#395]
So I'm playing with Infernal Mobs on hard difficulty - and for the most part I want the effects of playing on hard difficulty, but the infernal mobs have too many modifiers, IMO. Every time I run into one, it has 6 to 8 effects, which is way too many. A config option for 'modifierNumberMultiplier' or the like that I can set to 0.5 or something would be very nice.

**Comment by AtomicStryker** [comment]
I'm putting this on my "nice-to-have" list. When i get super bored on a vacation i might tackle it.
