### ISSUE TITLE
Dynamic Lights Server Console messages suggestion

### ISSUE THREAD

**Issue by katur239** [AtomicStryker/atomicstrykers-minecraft-mods#396]
Can these messages be moved into DEBUG or disabled somehow? Server console is getting pretty spammed by the messages.

ie

`[14:58:09] [Server thread/INFO] [at.dy.se.DynamicLights/]: Calling addLightSource on entity ServerPlayerEntity['SheritoBandito'/89, l='ServerLevel[world]', x=-5287.16, y=103.00, z=2102.34], dimensionLocationPath overworld`

`[14:58:09] [Server thread/INFO] [at.dy.se.DynamicLights/]: Successfully registered DynamicLight on Entity: ServerPlayerEntity['SheritoBandito'/89, l='ServerLevel[world]', x=-5287.16, y=103.00, z=2102.34] in list []`

`[14:58:09] [Server thread/INFO] [at.dy.se.DynamicLights/]: Removing Dynamic Light attached to ServerPlayerEntity['SheritoBandito'/89, l='ServerLevel[world]', x=-5287.16, y=103.00, z=2102.34]`

**Comment by AtomicStryker** [comment]
I think you can put a standard logging.properties (found for example in javas home/jre/lib folder) in your server config folder and it will be used. Then you can configure that class silent like this:

at.dy.level = ERROR

**Comment by katur239** [comment]
Unfortunately I don't think that works. I tried putting a logging.properties in the config/ folder. I tried putting that string in the one in the /usr/lib folder you mentioned and I tried using this in the command line 
-Djava.util.logging.config.file=/opt/minecraft/config/logging.properties

**Comment by katur239** [comment]
So I figured it out. ERROR is not a valid level class in Java. There is WARNING or SEVERE so that is why it wasn't working. Also found out there is an OFF too and opted to use that one. so far so good. Thanks.

**Comment by AtomicStryker** [comment]
Haha, ran into that one because we use Log4j at work. Glad it worked for you.

**Comment by DesolateIntention** [comment]
> I think you can put a standard logging.properties (found for example in javas home/jre/lib folder) in your server config folder and it will be used. Then you can configure that class silent like this:
> 
> at.dy.level = ERROR

I have the same problem and don't quite understand how to do this. Any help?
