### ISSUE TITLE
Changelog for latest 1.12.2 Infernal Mobs update

### ISSUE THREAD

**Issue by xJon** [AtomicStryker/atomicstrykers-minecraft-mods#399]
Hi,
In August this year you published a new update for Infernal Mobs 1.12.2, yet I cannot find the changes anywhere, the changelog included inside the jar file is identical and I can't see any recent commits.
I'd love to know what was changed. Thank you!

**Comment by AtomicStryker** [comment]
I think people in the mod comments section on curse claimed i had never uploaded the latest version, or the upload was corrupted, or something thereabouts.

**Comment by xJon** [comment]
Oh I see, in this case the only difference would be [this](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/ef09387bf9207df3c0080cff89fa872932830c49) commit. Thanks!
