### ISSUE TITLE
Ropes+ 1.6.4 for MC 1.7.10: Zipline

### ISSUE THREAD

**Issue by Fokson** [AtomicStryker/atomicstrykers-minecraft-mods#40]
This is possibly one of my favorite things added in any mod I have, and the only thing I really use in Ropes+, but I've started to notice that once a zipline has been in the world for a long enough time it starts... I don't know, creating thousands of extra entities I think?  The F3 screen says E6123/6151 or something similar whenever I'm within proximity of an "old" zipline and the framerate drops to 2-5 fps until I leave the area or break the zipline.  If I place a new one in the same position, it's fine again for a while but the process repeats.  The only tell I've noticed is that the rope will have a bendy graphic as well as one that goes straight from point A to point B.

**Comment by AtomicStryker** [comment]
I don't support these ancient mc versions anymore, im afraid

**Comment by Fokson** [comment]
Ah, my apologies.  I didn't realize that the most recent version offered on most of the sites it's available on (including your own website?) was considered ancient. Best of luck =)

**Comment by AtomicStryker** [comment]
I'll freely admit i may as well announce i've dropped support for Ropes+. I actually have updated it for 1.8 atleast but never got the models to work with the new system, or tried very hard for that matter. Too much work, not enough time.

**Comment by Fokson** [comment]
Aw, well that's too bad but I completely understand. Thanks for the work you put into it and for having the source up.  If I can find some time myself maybe I'll buckle down and try to learn enough Java to make a 1.9 version down the line.
