### ISSUE TITLE
[Battle Towers/1.12] Golem glitched on server

### ISSUE THREAD

**Issue by xJon** [AtomicStryker/atomicstrykers-minecraft-mods#401]
Reported to the issue repository over https://github.com/xJon/Hexxit-II/issues/46 by multiple users.
Any idea what's causing this?
Thanks!

**Comment by AtomicStryker** [comment]
It is possible server is not properly syncing the animation state of the golem to clients. Sadly, i don't support 1.12 anymore, so any investigation into the matter would have to happen by someone else.

**Comment by xJon** [comment]
Hey @AtomicStryker, thank you for the response. It ended up to be a mod incompatibility which was resolved :)
