### ISSUE TITLE
Dynamic Lights not working at all on 1.12.2

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#402]
Currently building a modpack yeah.
Crafted a torch.
And no light.

There is absolutely nothing in the log either.
https://paste.ee/p/NNmPZ

I am so confused.
![2021-11-25_22 31 25](https://user-images.githubusercontent.com/48165318/143501439-12da599b-d0e7-4dd6-84d9-53f0464a26dc.png)

**Comment by AtomicStryker** [comment]
I do not support 1.12 anymore, let me point out however Dynamic Lights worked for many thousands of people on that version.

Glancing at your log, are you installing it serverside and not on the client?? That's the wrong way.

The log line starting with:
[22:20:45] [Netty Client IO #2/INFO] [FML]: Attempting connection with missing mods ....

Shows the Dynamic Lights components.

**Comment by ghost** [comment]
The log is a client log

Den lör 27 nov. 2021 kl 11:19 skrev AtomicStryker ***@***.***

**Comment by ghost** [comment]
On a singleplayer world

Den lör 27 nov. 2021 kl 11:19 skrev AtomicStryker ***@***.***
