### ISSUE TITLE
[Suggestion] Curios Support?

### ISSUE THREAD

**Issue by Darkosto** [AtomicStryker/atomicstrykers-minecraft-mods#403]
Hey AtomicStryker!

I'm putting together a modpack right now using Dynamic Lights and was hoping you would consider adding support for the Curios mod. I created a custom "torch" slot so you can wear the torch instead of carrying it. But, due to how the mod works dynamic lights isn't compatible: 
![image](https://user-images.githubusercontent.com/10309699/145469032-762200b1-5ee0-4dd5-a8b7-418615ce5ed3.png)

Thanks for everything you do, take care!
Darkosto

**Comment by AtomicStryker** [comment]
Hi, you are a modder? To implement Dynamic Light support you basically need your own module, which reads this curios mod slot and updates a "PlayerLightSourceContainer" accordingly. So a full copy of this class: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.18/DynamicLights/src/main/java/atomicstryker/dynamiclights/server/modules/PlayerSelfLightSource.java except the line "for (ItemStack armor : event.player.getInventory().armor)" should read this curios slot instead.

**Comment by Darkosto** [comment]
I'm not a modder, I work on modpacks only so I have a limited range of what I'm able to do via configs or datapacks. That slot is added by a datapack

**Comment by AtomicStryker** [comment]
Then your best bet is asking TheIllusiveC4 for a dynamic lights implementation: https://github.com/TheIllusiveC4/Curios

It's a "no thanks" from me.
