### ISSUE TITLE
[Finder Compass] [1.18] Does not work at y<=0

### ISSUE THREAD

**Issue by RtHiaHB** [AtomicStryker/atomicstrykers-minecraft-mods#404]
If you go below 0 in 1.18, the finder compass stops working.  

The y-coordinate in this screenshot is -59. There is an iron ore directly in front of me, and my compass is in my off-hand, and I confirmed that it was in Workman's Mineables mode.  The off-white needle isn't showing.

![2021-12-15_06 26 29](https://user-images.githubusercontent.com/4576650/146178976-707b0dca-4f2e-4d7a-977f-2ab6d2a6d1b6.png)
 
Here, the y-coordinate is 16; everything else in this setup is exactly the same, but I get a different result.

![2021-12-15_06 35 02](https://user-images.githubusercontent.com/4576650/146179650-0df3aabc-f870-4f24-b4d0-2f4e8ccaf8ad.png)

**Comment by AtomicStryker** [comment]
Yes, there is a hardcoded limit to y>0 in the implementation. I was not aware it is possible for world to exist lower than that. Is that modded?

**Comment by RtHiaHB** [comment]
1.18 gives vanilla worlds the ability to exist from -64 to (IIRC) 320, so the ability to be at y<0 is not modded but vanilla.

This \<F3\> screen is from a vanilla instance:

![2021-12-15_12 25 17](https://user-images.githubusercontent.com/4576650/146235403-4c66cd44-54f1-4fce-8068-0d686c3626c7.png)

**Comment by AtomicStryker** [comment]
I checked my code and i did not in fact hard code this, but it is in the default compass settings.
There is a DimensionDefaults that says Overworld goes to 384 now.

Example from findercompass.cfg:

        "{\"block\":\"minecraft:gold_ore\"}": [245,245,0,15,1,1,100,0],

values: color R, color G, color B, xz searchrange, y searchrange, min y, max y, searchEvery15SecOnly

So, min y and max y need to be adapted. Fixed example:

        "{\"block\":\"minecraft:gold_ore\"}": [245,245,0,15,1,-64,384,0],

I will change the config defaults in my code.

**Comment by RtHiaHB** [comment]
Awesome.  I will change my config file to match what you have here.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/6dd0acdbb8b7f5d04a9d0693628f1626765434db the adjusted defaults are commited, and a new version pushed to curse

**Comment by AtomicStryker** [comment]
Oops, used 320 in there. Ah it'll be fine. I doubt the overworld actually has ores in these lofty heights.

**Comment by RtHiaHB** [comment]
Aha!  I've figured it out.  All ores now have a deepslate variant: there is the iron_ore we all know and love, but there is now also "deepslate_iron_ore", too.  Below y=0, there are no legacy stone-type ores; all of them are the deepslate variant.  That means that every entry in the config file also needs to list a deepslate variant of the respective ore.  For example, the following lines would need to be added to the config file for Workman's Mineables:
```		
		"{\"block\":\"minecraft:deepslate_iron_ore\"}": [
		  112,
		  112,
		  112,
		  15,
		  1,
		  -63,
		  320,
		  0
		],
		"{\"block\":\"minecraft:deepslate_gold_ore\"}": [
		  245,
		  245,
		  0,
		  15,
		  1,
		  -63,
		  320,
		  0
		],
		"{\"block\":\"minecraft:deepslate_copper_ore\"}": [
		  141,
		  83,
		  46,
		  15,
		  1,
		  -63,
		  320,
		  0
		],
		"{\"block\":\"minecraft:deepslate_coal_ore\"}": [
                   51,
		  26,
		  0,
		  15,
		  1,
		  -63,
		  320,
		  0		  
		]
```
 This will solve the problem completely.  I have tested this and it works.

**Comment by AtomicStryker** [comment]
OK so here is a picture that actually shows where ores can occur now: https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e3/1-18-ore-distribution.jpg and ores found below y=0 are the deepslate variants.

Rather than keeping up with updates, i will change the config defaults to -64 to 0 for all deepslate ores and 0 to 384 for classic ores. Even knowing that diamond should not appear at y>16 .... because i really do not want to update this every patch.

OK, tested it myself and it works fine. Commited to curse... https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/82ecd859542468815890615b7c1ce5b81f54e7b1
