### ISSUE TITLE
[MultiMine/1.12.2] Tile entities

### ISSUE THREAD

**Issue by Cephelo** [AtomicStryker/atomicstrykers-minecraft-mods#408]
Multimine with certain tile entities sometimes give more than 1 item when they're not supposed to, and sometimes these tile entities do not show up in the config as an item that can have multiline disabled for it.  Therefore, I am requesting a config option that allows users to disable multimine for all tile entities, vanilla and modded.  Disabled by default, your call.  I think a lot of people would like this, especially people who love big modpacks with lots of tile entities.  What do you think?

**Comment by AtomicStryker** [comment]
The idea has merit, but i don't support 1.12 anymore

**Comment by Cephelo** [comment]
How unfortunate. Is it possible to manually add entries to the config then, or force the mod to do so? The tile entities causing problems for me haven't shown up yet.

**Comment by AtomicStryker** [comment]
I barely recall this, but i think Multi Mine "only" works on blocks. So you have to look for the blocks which are backing your tile entities. Of course, if a mod uses some kind of metablock with a hundred sub-ids, Multi Mines config format is exceptionally terrible for dealing with that.

Multi Mine puts everything "unknown" that someone partially mines into the config straight away. If you multi mined it, it has to be in there.

Yes you can edit the config to your liking at any point, but just mining the block ingame is far easier - getting the proper technical names for blocks can be tricky.

**Comment by Cephelo** [comment]
Alright, I think I've gotten the hang of getting MultiMine to generate block entries in the config.  Closing this issue.
