### ISSUE TITLE
[1.7.10][Pet Bat] Death of player and bat at same time results in lost bat

### ISSUE THREAD

**Issue by Corosauce** [AtomicStryker/atomicstrykers-minecraft-mods#41]
Mods involved: Pet bat, Gravestone

I died to a creeper, gravestone was made where all my items were placed into. My pet bat was in the radius of the creeper blast and died too.

Just before I went to hit respawn I noticed the bat was added to my inventory, the dead player inventory, upon hitting respawn the bat item was lost since that player entity is scrapped. This probably happened due to the bats death animation delaying his itemization.

I doubt it would be easy to add that dead bat into the grave, so I figure the best solution here is to check if the entity player is dead before attempting to itemize the bat, if it is, just drop it where it died as an item so there is hope to recover it.

This definately is some sort of bug, because I had the bats flute still, but no bat was recoverable, upon throwing the flute, it dissapeared.

Goodbye Mr. Tiddles, you will be missed forever.

**Comment by AtomicStryker** [comment]
Sounds reasonable. Pushed relevant change d0a4ce21958648377d109bbf63fd578ab432ef00
