### ISSUE TITLE
A way to disable infernal mobs from spawning in mob farms

### ISSUE THREAD

**Issue by itsdinkd** [AtomicStryker/atomicstrykers-minecraft-mods#410]
Without completely destroying mob farms in general with antiMobFarm, please add a way to make it so I can allow mob farms in my modpack, while also at the same time disable Infernal Mobs from spawning from spawners in 1.18.1 please

thanks!

**Comment by AtomicStryker** [comment]
The problem is that an entity spawnin in Minecraft does not "know" where it came from. There is nothing that distinguishes a spawner mob from a natural spawn. So Infernal Mobs cannot tell the difference either.

**Comment by itsdinkd** [comment]
What about if enabled, converting all minecraft spawners into your own version of spawners, that way you can create logic for if it spawns in your own spawner or not. would this work?

**Comment by AtomicStryker** [comment]
While possible in theory, it would change Infernal Mobs from a pure "addon" that doesnt corrupt saves to a mod containing its own blocks, which can corrupt saves. I dont want to do that to solve a fringe issue.
