### ISSUE TITLE
Server log if filled with unnecesary lines

### ISSUE THREAD

**Issue by hacheraw** [AtomicStryker/atomicstrykers-minecraft-mods#413]
Please disable debug logging or add an option to disable it. Thanks!!!

![image](https://user-images.githubusercontent.com/10481749/151858195-37f06882-1058-49f4-ac30-a4051dc871c2.png)

**Comment by AtomicStryker** [comment]
You can configure MC logging in detail: https://docs.spongepowered.org/stable/en-PT/server/spongineer/logs.html (the information in there applies to forge also).

But i agree that i should have reduced logging level after development.

Have 1.18.2, pushed it to curse also https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/e3d048d01d954a320f7ffb4d1502db0c2c2febc2

**Comment by hacheraw** [comment]
Thank you!
