### ISSUE TITLE
Lighting bug with "Dynamic Lights" (no light)

### ISSUE THREAD

**Issue by Finelarme9** [AtomicStryker/atomicstrykers-minecraft-mods#414]
Hey. Thank you for the mod "Dynamic Lights". Unfortunately, there is a recurrent (and pretty annoying lol) lighting bug. Indeed, the torch (or any other lighting sources in hand) is turned off for no concrete reason (the light works while I am on a block and when I fly some blocks above the light is turned off, same situation in gamemode survival, no matter the biome/weather). Also, another detail, the light is turned off when we walk through a minecraft:tall_grass.

- Screenshot = https://ibb.co/f9PXzYV
- Forge = 1.18.1-forge-39.0.64 (same problem with 1.18.1-forge-39.0.63 or 1.18.1-forge-39.0.14)
- Other mod = No other mod.

Thank you for your time.

**Comment by AtomicStryker** [comment]
The current iteration of Dynamic Lights works by constantly placing an invisible untouchable "glowstone" block where the shining item, in this case your player, is.

I also have a fake "full water" block so it works in full water.

Tall grass and snow can interfere with this, as they occupy the space the fake light block wants to occupy. The only solution would be to try and put the light in the nearest free block, but i think that would look goofy also (the light would jiggle around you).

**Comment by Finelarme9** [comment]
I see, I understand. Thank you for your answer. Interferences seems also possible when that glowstone block floats in the air so without snow/grass (like it works when I am under 78 of Z axis and doesn't work anymore when I am on 79+). It seems very complicate to solve this problem. Very huge challenge during games too lol. Like I am walking in a cave and suddently no more light.

**Comment by Finelarme9** [comment]
Same problem when we stick to a glass pane or in specator mode when we "move" into the minecraft:grass.

For a potential fix (i don't know ?), is there a way to put that glowstone block light source above the player, to be above all these snow/grasses conflict "blocks" ?

**Comment by AtomicStryker** [comment]
Yes, but that leaves us with the light jiggling and also me poor author with the responsibility to track and clean up these randomly-placed light blocks. I'll try, i guess, when next the fancy strikes me to tinker on the mod a bit.

**Comment by Finelarme9** [comment]
Ok, thank you!

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/21a46c6def0095d1332b2ac0ab14dc57512d65d1

your wish came true

**Comment by Finelarme9** [comment]
Thank you so much!
