### ISSUE TITLE
Anti mob farm

### ISSUE THREAD

**Issue by itsdinkd** [AtomicStryker/atomicstrykers-minecraft-mods#415]
On the 24th of January release for 1.18.1, did you change how antimobfarm works? When enabled before, if you placed a spawner, it would spawn pigs. Now with the latest update, If you enable it, it doesn't do anything. 

I'm trying to turn it on so people can't use spawners but still silk touch it so they can use the spawner in a recipe.

**Comment by AtomicStryker** [comment]
No, the Infernal Mobs anti mob farm feature has not been touched.

**Comment by itsdinkd** [comment]
Can you tell me what i'm doing wrong? because its no longer working. 

```
  "antiMobFarm": true,
  "mobFarmCheckIntervals": 10,
  "mobFarmDamageTrigger": 4.0,

**Comment by AtomicStryker** [comment]
Backup/rename your config, let it re-generate to make sure i didnt change it between versions.

Saving and loading works, Infernal Mobs remain infernal? This demonstrates that the LivingUpdateEvent hook works, which is also where the AntiMobFarm check code exists

Infernal Mods reacting to your attacks work? (example: Sticky yeets your weapon when you attack a mob) .. this is where the LivingHurtEvent hook shows, and this is where AntiMobFarm counting code executes

Check your logfile, does it contain "Infernal Mobs AntiMobFarm damage check, max detected chunk damage value" at any point? Hm i print to system ... :D

**Comment by AtomicStryker** [comment]
Other approach: I don't have the time to setup and debug this, but if you create a minimal savegame (void or flat world with only a working mobfarm present) that i could use to quickly recreate your circumstances, then i could probably invest a few minutes to debug it
