### ISSUE TITLE
[1.12.2] Stick config option not working?

### ISSUE THREAD

**Issue by Cephelo** [AtomicStryker/atomicstrykers-minecraft-mods#416]
The stick still displays block data about the block in the chat, even with the config option set to false.  I don't know if this is caused by a mod conflict or not.
MC v1.12.2
Mod version released on Curseforge on June 7th, 2019
![image](https://user-images.githubusercontent.com/79186646/153128401-b31cd1ca-02dd-49e9-a40d-e26c0de89507.png)
Any help is appreciated, and I am happy to assist in any way I can.

**Comment by AtomicStryker** [comment]
This is ruins.txt in the world save folder? There is one for each world. See if you can find the phrase "Loading options from: ..." in your logfile, it should include that folder. Otherwise search for "There was an error when loading the options file.  Defaults will be used instead"

**Comment by Cephelo** [comment]
I did not realize that each world had a config file, thank you for pointing that out to me!  Issue was resolved.
