### ISSUE TITLE
Causing crash with "The Abyss 2" ´s IceSkeleton entity

### ISSUE THREAD

**Issue by marcell123455** [AtomicStryker/atomicstrykers-minecraft-mods#417]
Minecraft 1.16.5 
Forge 1.16.5-36.2.23
infernalmobs-1.16.2.1
TheAbyss2+2.2.3-1+1.16.5
https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii
Server Crash Log: https://pastebin.com/gP4zpWVq

Only when installed on a server, infernal mobs is messing with the IceSkeleton entity of The Abyss 2 and crashing the server. It happens when a player enters the frost dimension of The Abyss 2 and IceSkeletons appear. It´s working fine in singleplayer. When uninstalling infernal mobs it is no longer crashing.

**Comment by AtomicStryker** [comment]
Just from the looks of it, this appears to be a problem with this abyss mod. Does that mod work in multiplayer without Infernal Mobs? The crash claims its entity class is not dedicated server compatible.

**Comment by marcell123455** [comment]
Yes. The Abyss 2 works without a problem in multiplayer when infernal mobs is not installed. This error/crash does not appear then.

**Comment by AtomicStryker** [comment]
Have you reached out to the dev of that mod? I feel they have clientside code in a server class, and i don't see how Infernal Mobs could fix this

EDIT: Just for understanding, what basically happens is that IceSkeleton is spawned into the world, Infernal Mobs asks "hey whats your name" and the abyss mod goes REEEEE I CRASH NOW

**Comment by marcell123455** [comment]
^^ Yes, I have talked to the dev before here:
https://github.com/Y3Z0N/theabyss/issues/36
