### ISSUE TITLE
Please update Dynamic lights minecraft version

### ISSUE THREAD

**Issue by hacheraw** [AtomicStryker/atomicstrykers-minecraft-mods#419]
It works fine on 1.18.1
That way we could use curseforge app to install the mod instead of doing it manualy.

Well maybe "fine" is not the word... I've found that it raises RAM consumption from 1,300M to 2,800M (+1.5G) but it works :D

Thanks.

**Comment by AtomicStryker** [comment]
You mean i should re-release it for 18.1 (and i guess now 18.2) despite the current release working there? So the curseforge app displays the mod for these versions? I wasn't aware they aren't smart enough to include compatible versions.

**Comment by hacheraw** [comment]
Yeah... I'm not expert but you can see other people saying the same on curse forge comments.
If you create a profile for "1.18.1" on curseforge app and try to find your mod it will not be there. You can add it manually but then when you try to export the "modpack" you get a warning about this.

This also happens, if I recall correctly, with Disenchantment Table mod.

I have not tried 1.18.2 since almost all mods I use are for 1.18.1 but yeah...

I think you have to implicit especify compatible versions when publishing it... Even the last number meaning a "hotfix" with no breaking changes...

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/21a46c6def0095d1332b2ac0ab14dc57512d65d1

I've made some other changes that were asked for, built the version 1.18.3 for all 3 relevant minecrafts (1.18, 1.18.1 and 1.18.2) and submitted them to curseforge.
