### ISSUE TITLE
[Multi Mine 1.16.5] Crash on Startup, Compiled for a more recent version of java

### ISSUE THREAD

**Issue by MaximumWoahverdrive** [AtomicStryker/atomicstrykers-minecraft-mods#423]
The Multimine 1.16.5 jar on curseforge was compiled with java 11 making it incompatible with java 8 which is still commonly used for Minecraft versions up to and including 1.16.5.
[latest.log showcasing crash](https://paste.ee/p/lFBtM)
it should be recompiled with java 8 for better compatibility, as jars compiled with java 8 can be run on java 11 but not the other way around

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/d8e2eb1007e5ac9d1e17ccaf6e8e0719080100a1
should fix it
