### ISSUE TITLE
Infernal mobs: How to edit "drop amount" or add NBT tags for item in loot tables? 

### ISSUE THREAD

**Issue by RabbltMan** [AtomicStryker/atomicstrykers-minecraft-mods#426]
Game Version 1.17.1
Infernal Mobs 1.17.1.1
Forge 37.1.1
My friends and I enjoyed the mod very much. :)

I tried to edit the loot tables ("`droppedItemIDs...`" in infernalmobs.cfg file) to make strengthened mobs drop more but failed...
Almost all online tutorials I've searched for are **out-of-date** (game version 1.7 or lower) for my demand :( 
And I accidentally found that a NBT tag was added to the item instead of "dropping 3 golden apples" when I edited like the example below:
```
"droppedItemIDsElite": [
    "{Count:3,nameId:\"minecraft:minecraft:enchanted_golden_apple\"}"
  ],
```
So, as I've mentioned in the title, how can I correctly edit the config file to meet my demand? Thanks.

**Comment by AtomicStryker** [comment]
This is actually a bug with how Infernal Mobs handles items from the config, and i have fixed it now: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/80e76acce44da15e51fb0248a1bd509cf2061fde

Sadly, you will have to delete/rename existing configs and let the new ones regenerate, the IDs are slightly different, but you will instantly spot your quantities (the "b" stands for byte, just ignore it)

I have pushed new versions for MC 1.17.1 and 1.18.2 with the bugfix

**Comment by RabbltMan** [comment]
Thanks for taking the time. 

When and where can I download the latest version? It seems hard for me to directly change the mod files.

**Comment by AtomicStryker** [comment]
Did i forget to push them to curse? ... huh apparently yes. https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-infernal-mobs/files/3736942
