### ISSUE TITLE
Finder Compass 1.18.1 crash

### ISSUE THREAD

**Issue by HeyItzGeo** [AtomicStryker/atomicstrykers-minecraft-mods#428]
Crash on game launch 1.18.1
cannot find config, config not generated
https://pastebin.com/HeUzLHya
https://pastebin.com/UCFKdY6f

**Comment by AtomicStryker** [comment]
Duplicate issue of https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/427 but for 1.18.1 not 1.18.2

I have built Finder Compass 1.18.5 for MC 1.18.1 and pushed it to curse for you

**Comment by HeyItzGeo** [comment]
Amazing! I'll try tonight
