### ISSUE TITLE
Minions Disappeared on MP Server

### ISSUE THREAD

**Issue by generalshear** [AtomicStryker/atomicstrykers-minecraft-mods#429]
Attack of the B Team - Minions mod MCv1.6.4. I summoned my Minions on an Attack of the B Team multiplayer server and set them to make a mineshaft in the Nether. I went to the Overworld to get a chest for them to fill. But when I tried to go back to them in the Nether, they were gone. Any time I try to unsummon them, it crashes my game. I tried this in and out of the Nether, but to no avail. I have asked the server owner to reset my playerdata but this did not fix the issue. It could be an issue with how the server loads chunks, but I have tried unloading and then reloading the chunk they were in but they are still gone. Any advice regarding what I can do as a client or ask for on server side is helpful. Thank you.

**Comment by generalshear** [comment]
Apologies if I did not format this correctly

**Comment by AtomicStryker** [comment]
Sorry friend, i really dont support those ancient versions anymore. As far i recall Minions should have unsummoned when their master no longer was in the same dimension as them. The only "fix" i can think of is to delete your Minion entities from the server savefile, which that server owner probably cannot do.

**Comment by generalshear** [comment]
I understand you don't support them. Thank you so much for replying regardless. I appreciate the help.
