### ISSUE TITLE
Ruins ignoring biomesToSpawnIn in generic folder

### ISSUE THREAD

**Issue by LemADEC** [AtomicStryker/atomicstrykers-minecraft-mods#43]
To my understanding, biomesToSpawnIn is ignored when the related template is in the generic folder.
I would suggest to report this as a warning in the ruins.log file so we don't get confused on why those templates are still generating everywhere when we have the biomesToSpawnIn constrain set.
Something like:
"template xxxx.tml is in the generic folder, it's biomesToSpawnIn constrain will be ignored."

**Comment by AtomicStryker** [comment]
It is not a constraint, it is a way to register ADDITIONAL biomes other than the template root folder. If that root folder happens to be "generic", the template is already registered to every biome.

Ruins logic is biome-centric, not template-centric
