### ISSUE TITLE
Multimine 1.18.2 Incompatibility with HT's Treechop

### ISSUE THREAD

**Issue by Atlantispy** [AtomicStryker/atomicstrykers-minecraft-mods#432]
Hi,

When multimine is installed it causes issues with: https://www.curseforge.com/minecraft/mc-mods/treechop

It no longer causes the chopping stages and just cuts the log block

**Comment by AtomicStryker** [comment]
Duplicate of https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/432. My recommendation remains to just blacklist trees in Multi Mine if you are using a different mod doing a similar thing.
