### ISSUE TITLE
CurseForge Project Distribution

### ISSUE THREAD

**Issue by JulianVennen** [AtomicStryker/atomicstrykers-minecraft-mods#433]
Hi, I work at Aternos (a large free Minecraft server host).

The only way users can download mods on our servers is by using our mod search, which can download thousands of mods from CurseForge or Modrinth.

CurseForge recently started applying the project distribution which means that we can no longer download mods, that disabled project distribution (https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle), from the API.

We wanted to ask if you could allow project distribution again. I understand that you work hard for your mod and would like to get paid for it, but since most people will still download it from the website either way, blocking API access on CurseForge probably has a very small effect on that.

We also support a lot of developers in the Minecraft community using GitHub sponsors (https://github.com/orgs/aternosorg/sponsoring) and would love to add you to this list if you sign up for GitHub sponsors.

**Comment by AtomicStryker** [comment]
I'm willing to check and see exactly how big the effect is. I have re-enabled third party downloads to all my mods on curse for now. I don't exactly depend on the money, but it does feel nice to be appreciated.
