### ISSUE TITLE
Particles Accumulate When the Game is Paused

### ISSUE THREAD

**Issue by Darkosto** [AtomicStryker/atomicstrykers-minecraft-mods#434]
Hello!

Currently, there seems to be an issue with Infernal Mobs particles. When the game is paused, the infernal particles continue to accumulate. If the game is paused for a long enough time, there will significant lag for a few moments while the particles dissipate. Would you be able to look into pausing them while the game is not running?

Thank you!

MC: 1.18.2
Infernal Mobs: 1.18.4
Forge: 40.1.23

**Comment by AtomicStryker** [comment]
Yeah, sure
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/b0fc75bdf043a620fe0811fe2cd1f72e8a5858cc

Pushed 1.18.5 to curse
