### ISSUE TITLE
Mod completely breaks if Phosphor is installed.

### ISSUE THREAD

**Issue by MagmaSlime123** [AtomicStryker/atomicstrykers-minecraft-mods#435]
Title.

Mod acts as if its not installed if Phosphor is being used.

**Comment by AtomicStryker** [comment]
Which mod? Which versions of mc and the mod? Why the heck would you use a "solid material that emits light, or luminesces, when exposed to radiation such as ultraviolet light or an electron beam" with minecraft mods?

**Comment by MagmaSlime123** [comment]
See https://www.curseforge.com/minecraft/mc-mods/phosphor-forge. It's a lighting optimization mod.

**Comment by AtomicStryker** [comment]
Mods that do sweeping changes to the same game system (in this case the light engine) usually don't work together. Same for Optifine.
