### ISSUE TITLE
ruins mod crash (1.12.2)

### ISSUE THREAD

**Issue by rebarakuk** [AtomicStryker/atomicstrykers-minecraft-mods#436]
version 1.12.2

forge 14.23.5.2860

ruins (Jun 7, 2019)

[crash report](https://www.minecraftforum.net/linkout?remoteUrl=https%253a%252f%252fgist.github.com%252frebarakuk%252f68a0adcb021ac849e40b3612bb0a3d67)

[latest log](https://www.minecraftforum.net/linkout?remoteUrl=https%253a%252f%252fgist.github.com%252frebarakuk%252f664542ebd85e77d0a226a9a4050e0bf8)

-how to reproduce
1. maybe I see an ore top structure in ruins mod (big ore top)
2. then I leave and enter again the world
3. this crash happens

**Comment by rebarakuk** [comment]
![Uploading 2022-06-01_13.12.08.png…]()

**Comment by rebarakuk** [comment]
big ore top doesn't make this crash. I misunderstood XD

**Comment by AtomicStryker** [comment]
It appears to be crashing because it tries to load some entity from NBT and fails. Ruins does not modify entities. I would suspect something else from your long list of mods

That being said, i do not support 1.12.2 anymore

**Comment by rebarakuk** [comment]
ok bye...
