### ISSUE TITLE
Incompatible with HT Tree Chop

### ISSUE THREAD

**Issue by itsdinkd** [AtomicStryker/atomicstrykers-minecraft-mods#437]
When using HT Tree Chop with Multimine on forge 1.18.2, you cannot chop trees. You have to strip the tree first to do so (as you can blacklist the chop from multi mine config). Yes you can blacklist the individual logs, however, having a huge modpack with tons of tree's and what seems to be no tag support in the blacklist, this is not a option.

**Comment by AtomicStryker** [comment]
So what you actually ask for is tag support in the Multi Mine blacklist? Why didn't you say so?

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/5b5ff4d08c1f505011699702fa4800d41957a840

1.18.3
- added tag support for items and blocks in the blacklist configuration
- example: bannedBlocks entry "minecraft:logs": true will prevent Multi Mining on all kinds of tree blocks including mods
- implemented serverside blacklist clearing affected clientside progress - before, even blacklisted blocks could still be multi mined as long as you did not change blocks

Pushed new version to curse

**Comment by itsdinkd** [comment]
More or less :D
