### ISSUE TITLE
[Infernal Mobs] NBT?

### ISSUE THREAD

**Issue by itsdinkd** [AtomicStryker/atomicstrykers-minecraft-mods#438]
For 1.18.2, what is the nbt used to detect if a entity is any type of Infernal mob tier?? I ask because I would like to set up some rules using In Control! and I would basically have to set the condition based around using a NBT

**Comment by AtomicStryker** [comment]
"InfernalMobsMod". If an entity has that tag it is infernal something

**Comment by itsdinkd** [comment]
thank you, i am not so great with working around NBT's, would it be something like this,

{Tag: "InfernalMobsMod"} ?  is there a way to erase a tag or set InfernalMobsMod to false in the nbt? I'd like to basically prevent mobs from spawning in a spawner if they are infernal (Without using antimobfarm). In Control allows editing nbt in spawner spawned mobs

**Comment by AtomicStryker** [comment]
Even if you removed the nbt from a "live" infernal mob, they would remain infernal until you saved and loaded the level. The nbt tag is set by infernal mobs AFTER the mob spawned, so doing anything on spawn would not help.

There is no way for Infernal Mobs to tell if a spawned mob came from a spawner. Hence antimobfarm.
