### ISSUE TITLE
Please mark as forge mods on curseforge.com

### ISSUE THREAD

**Issue by pavog** [AtomicStryker/atomicstrykers-minecraft-mods#439]
For every release you can set a game version, a java version and a modloader.
Could you please add the modloader "forge" to your mods and releases?

It's like next to the game version.
This makes it easier for third party apps to know if it's a forge or a fabric mod.

Example:
https://www.curseforge.com/minecraft/mc-mods/easy-hammers/files/all

-> You can filter for "modloader" -> "forge"

**Comment by AtomicStryker** [comment]
I did a pass through my mods and set the forge tag for the most relevant versions (usually the latest and 1.12.2). I'll see if my build uploader can set this tag automatically in the future.

**Comment by pavog** [comment]
- [x] [Multi Mine](https://www.curseforge.com/minecraft/mc-mods/multi-mine)
- [x] [AtomicStryker's Infernal Mobs](https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-infernal-mobs) 
- [x] [Finder Compass](https://www.curseforge.com/minecraft/mc-mods/finder-compass)
- [x] [Dynamic Lights](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights) 
- [x] [BrassAmber Battle Towers](https://www.curseforge.com/minecraft/mc-mods/brassamberbattletowers)
- [x] [Stalker Creepers](https://www.curseforge.com/minecraft/mc-mods/stalker-creepers) 
- [x] [Ruins (Structure Spawning System)](https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system)
- [x] [AtomicStryker's Battle Towers](https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-battle-towers)
- [x] [Pet Bats](https://www.curseforge.com/minecraft/mc-mods/pet-bats)
- [x] [Minecraft Minions](https://www.curseforge.com/minecraft/mc-mods/minecraft-minions)
- [x] [Simply Hax](https://www.curseforge.com/minecraft/mc-mods/simply-hax)
- [x] [Necromancy](https://www.curseforge.com/minecraft/mc-mods/necromancy)
- [x] [AtomicStryker's Magic Yarn](https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-magic-yarn)
- [x] [Kenshiro Mod](https://www.curseforge.com/minecraft/mc-mods/kenshiro-mod)
- [x] [Ropes+](https://www.curseforge.com/minecraft/mc-mods/ropes)

**Comment by AtomicStryker** [comment]
I assume you look up this information in some sort of mod explorer. You are probably not looking at the relevant versions, the mods "end" having updates at various different MC versions. I assure you, i did what i said.

**Comment by pavog** [comment]
Oh yes, I think it was a caching problem on my side.
I fixed the problem and updated the comment.
Thank you!
