### ISSUE TITLE
items dropped by Infernals show as blocks that are missing textures.

### ISSUE THREAD

**Issue by Darkmega18** [AtomicStryker/atomicstrykers-minecraft-mods#44]
atomicstryker, it appears you might have a slight problem, perhaps an incompatability somewhere. I've mapped this stuff to my infernals: 

S:droppedItemIDsElite=minecraft:diamond-1-3,minecraft:emerald-1-3,flammpfeil.slashblade:proudsoul-1-3,minecraft:glowstone-5-10,minecraft:blaze_rod-3-6,minecraft:experience_bottle-20-30

S:droppedItemIDsInfernal=minecraft:diamond-6-9,minecraft:emerald-6-9,flammpfeil.slashblade:proudsoul-6-9,minecraft:glowstone-15-20,minecraft:blaze_rod-9-12,minecraft:experience_bottle-40-50

S:droppedItemIDsUltra=minecraft:diamond-3-6,minecraft:emerald-3-6,flammpfeil.slashblade:proudsoul-3-6,minecraft:glowstone-10-15,minecraft:blaze_rod-6-9,minecraft:experience_bottle-30-40

it appears to work, but the items that have dropped (not sure about the glowstone, since I haven't gotten lucky enough yet) turn up as blocks which have the black and purple missing texture texture. but when you pick them up you can search for recipes etc and they're perfectly functional, such as the XP bottles. You can also merge them with an existing stack of items and they'll change back just fine. But I figured I'd bring it up and ask what the problem could be and if you've encountered it before.

as a side note, it also happened to netherquartz which I had set to spawn in one of my battle tower lists, but everything else seemed fine, it was the only thing I saw out of place from the tower I went through before I decided to report this to you.

**Comment by AtomicStryker** [comment]
This is a problem specific to the items you spawned, not Infernal Mobs. You probably missed the meta values or spawned items that are not supposed to be obtainable (or exist in "dropped" form).

**Comment by Darkmega18** [comment]
Soooo how do I go about adding meta values to the minecraft items then? I only copied how you added diamonds to the infernal level ones only adding "minecraft:" to the beginning of diamond just for good measure... :V I'm guessing I misread the 0-3 as 0 to 3 diamonds dropped rather than diamonds-metadata-exactnumberbeingdropped. >_>

**Comment by AtomicStryker** [comment]
ID-meta-stackSize-stackSizeRandomizer
