### ISSUE TITLE
[1.19] DynamicLights: Incompatible with Forge 41.0.98

### ISSUE THREAD

**Issue by jellybean13** [AtomicStryker/atomicstrykers-minecraft-mods#441]
Minecraft version: 1.19
Forge version: 41.0.98
Log: https://pastebin.com/uUh1cMX0

**Comment by AtomicStryker** [comment]
Odd. They should start a new version increment (e.g. 41.1.01) when they make breaking rename changes like this in forge.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/520ffdcc4abd8d8b6067bed9f1faab3507268d45

Dynamic Lights 1.19.2 is pushed to curse

**Comment by jellybean13** [comment]
> Odd. They should start a new version increment (e.g. 41.1.01) when they make breaking rename changes like this in forge.
> 
> [520ffdc](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/520ffdcc4abd8d8b6067bed9f1faab3507268d45)
> 
> Dynamic Lights 1.19.2 is pushed to curse

This mod is working after this commit. Thanks.
