### ISSUE TITLE
[infernalmobs] Spam Skipping Entity with id [1.18.2  Last version]

### ISSUE THREAD

**Issue by javierlechuXD** [AtomicStryker/atomicstrykers-minecraft-mods#443]
Hi,

The mod makes the message Skipping Entity with id appear on my console all the time

https://hastebin.com/fasaguloju.css

My server is Forge 1.18.2 in the last version.

This error does not crash the server, but it is annoying

> [03ago2022 19:26:00.033] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: player ServerPlayer['Adri2043'/13181, l='ServerLevel[world]', x=-2907.16, y=63.75, z=-3429.32] from string Adri2043 querying server for mods of entity id 19713
> [03ago2022 19:26:00.033] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: resolves to entity Salmon['Salmon'/19713, l='ServerLevel[world]', x=-2913.50, y=51.72, z=-3366.10] modifiers null
> [03ago2022 19:26:00.033] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: player ServerPlayer['Adri2043'/13181, l='ServerLevel[world]', x=-2907.16, y=63.75, z=-3429.32] from string Adri2043 querying server for mods of entity id 19712
> [03ago2022 19:26:00.033] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: resolves to entity Salmon['Salmon'/19712, l='ServerLevel[world]', x=-2913.52, y=52.92, z=-3365.91] modifiers null
> [03ago2022 19:26:00.363] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: entity Bee['Bee'/19867, l='ServerLevel[world]', x=92.50, y=73.20, z=93.40] was spawned in unmodified before, not modifying it
> [03ago2022 19:26:00.363] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.423] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.425] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: player ServerPlayer['Adri2043'/13181, l='ServerLevel[world]', x=-2905.88, y=63.50, z=-3427.21] from string Adri2043 querying server for mods of entity id 9835
> [03ago2022 19:26:00.425] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: resolves to entity EntityDeer['Deer'/9835, l='ServerLevel[world]', x=-2832.42, y=64.00, z=-3285.42] modifiers null
> [03ago2022 19:26:00.467] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.522] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.537] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Greenbell22 has made the advancement [Getting an Upgrade]
> [03ago2022 19:26:00.565] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.567] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: player ServerPlayer['Nexus_17'/617, l='ServerLevel[world]', x=4924.59, y=40.00, z=-5428.30] from string Nexus_17 querying server for mods of entity id 19868
> [03ago2022 19:26:00.567] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: resolves to entity Creeper['Creeper'/19868, l='ServerLevel[world]', x=4997.50, y=37.00, z=-5358.50] modifiers null
> [03ago2022 19:26:00.581] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: player ServerPlayer['Greenbell22'/665, l='ServerLevel[world]', x=4922.20, y=49.00, z=-5441.30] from string Greenbell22 querying server for mods of entity id 19868
> [03ago2022 19:26:00.581] [Server thread/DEBUG] [atomicstryker.infernalmobs.common.InfernalMobsCore/]: resolves to entity Creeper['Creeper'/19868, l='ServerLevel[world]', x=4997.50, y=37.00, z=-5358.50] modifiers null
> [03ago2022 19:26:00.622] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.666] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.721] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.765] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.817] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.865] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.918] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:00.966] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.017] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.064] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.120] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.170] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.221] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.266] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.323] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.366] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.422] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 
> [03ago2022 19:26:01.464] [Server thread/WARN] [net.minecraft.world.entity.EntityType/]: Skipping Entity with id 

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/43497705/182738657-cfad82fa-12b5-4ebe-a23b-6c432a5adfa4.png">

**Comment by AtomicStryker** [comment]
Hmm thats a vanilla class complaining about an entity compound tag it cant map. Are you sure Infernal Mobs is causing this? Or did you remove a mod that had added custom entities? One could reduce the log level of net.minecraft.world.entity.EntityType
