### ISSUE TITLE
Question: is it possible to add NBT data to a dropped item?

### ISSUE THREAD

**Issue by belathus** [AtomicStryker/atomicstrykers-minecraft-mods#445]
I tried adding the following to the list of items dropped by an infernal mob, but it just dropped a tome with no NBT data attached:
```
"{Count:1b,id:\"quark:ancient_tome\",StoredEnchantments:[{lvl:3,id:\"minecraft:unbreaking\"}]}"
```
I'm not sure what the right format would be to add a specific enchantment to the list of drops.

**Comment by AtomicStryker** [comment]
Sorry, i don't know either. Ask in minecraft modding forums or discords, people there should be able to point you to the correct NBT format

**Comment by belathus** [comment]
I got it. This is what it should look like:
```
"{Count:1b,id:\"quark:ancient_tome\", tag: {StoredEnchantments:[{lvl:3,id:\"minecraft:unbreaking\"}]}}"
```
