### ISSUE TITLE
Dynamic Lights not working in the Nether

### ISSUE THREAD

**Issue by Hyperz6** [AtomicStryker/atomicstrykers-minecraft-mods#446]
Dynamic lights is working just fine in the overworld and lights up the path around me when I hold a torch in my hand, however when I'm in the nether, dynamic lights mysteriously stops working and no longer lights up the path around me upon holding a torch. I am using the latest version of the mod for version 1.18.2

**Comment by AtomicStryker** [comment]
in dynamiclights.cfg, bannedDimensions contains nether and end by default. Remove nether as banned dimension and it should work, i dont recall why it is banned, this might be legacy reasons
