### ISSUE TITLE
[1.7.10] Advanced Machines Quartz Ore

### ISSUE THREAD

**Issue by xJon** [AtomicStryker/atomicstrykers-minecraft-mods#447]
This is obviously quite dated, but I just wanted to inquire about the reason for this recipe added by Advanced Machines:
![image](https://user-images.githubusercontent.com/8945347/186873419-adbad1d2-ed3e-43f0-a5a4-3c9853d971d3.png)
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/7eb52de056a07a29a4dc959b87a6eca713281d9c/AdvancedMachinesAS/src/main/java/atomicstryker/ic2/advancedmachines/ModAdvancedMachines.java#L108

(reported to my modpack over https://github.com/xJon/The-1.7.10-Pack/issues/1974)

**Comment by AtomicStryker** [comment]
I didn't add it, or noticed it. No clue. Possibly debugging, and left in.
