### ISSUE TITLE
1.19.2 Berserker Damage

### ISSUE THREAD

**Issue by Daniel190403** [AtomicStryker/atomicstrykers-minecraft-mods#448]
Berserker does not make more than 10 HP Damage. Even if the entety is a Warden.

**Comment by AtomicStryker** [comment]
There is a config setting for how much damage Infernal Mobs can do in a single strike, that will probably be limiting

**Comment by Daniel190403** [comment]
Thanks for your respondVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AtomicStryker ***@***.***> Datum: 02.09.22  11:21  (GMT+01:00) An: AtomicStryker/atomicstrykers-minecraft-mods ***@***.***> Cc: Daniel190403 ***@***.***>, Author ***@***.***> Betreff: Re: [AtomicStryker/atomicstrykers-minecraft-mods] 1.19.2 Berserker Damage (Issue #448) 
There is a config setting for how much damage Infernal Mobs can do in a single strike, that will probably be limiting
