### ISSUE TITLE
Battletower golem derps through the ground then destroys tower forever

### ISSUE THREAD

**Issue by Darkmega18** [AtomicStryker/atomicstrykers-minecraft-mods#45]
Hi again Atomicstryker, I've got another problem. This one doesn't have a log or anything, but I went up a battle tower (the first one I bothered to do entirely since I installed it, since I usually just snuck in, grabbed some loot for a boost and bailed out) and went to fight the golem.

I saw that it had blast-off, ghastly, and 1 UP. so I got my stuff ready about being surprise fireballed before he even started. A slashblade katana, a keyblade and a battlesign and after doing shenanigans to steal the loot out from under him so he wouldn't blow it up by accident I fought him.

But within about 5 seconds if juggling him a bit with the katana within the bounds of the tower and hitting him a few times with the keyblade he seemed to fall into the ground and just disappear. I have a bad feeling that he ended up in the void somehow cause it said a battle tower golem had fallen.

Once the tower began falling not only did the sounds not play at the top but once the tower had finished exploding to the last 2 levels where it usually stops the message came up again and the same tower began exploding it's now already destroyed self from the top up. It happened about 5 more times, each blast causing a FPS dip for each hit, before I stopped to come tell you.

Could I have an incompatibility or did you miss something? I do remember someone on the minecraft forums thread mentioning golems falling through worlds and stuff... :< did you ever figure it out or make a world around? and what could cause the eternally exploding tower glitch I just got? nothing strange comes up on the console other than dungeon tactics mod spamming my console which I've since reported also. :V

**Comment by AtomicStryker** [comment]
Yes, there is some bug that causes the golem to fall infinitely through the ground. It is probably some unintended interaction with the jump attack, although that one doesn't disable collision at any point (nor would i know how to do that). I do not have the spare time to go on an extensive bug hunt, sorry, unless someone manages to reproduce this it is unlikely i will make a fix.

**Comment by Darkmega18** [comment]
could "golem explosions true/false" be a factor? the other guy never did mention if that was a set on or not. and my golem blasts were turned off, since he seemed to do it after I made him hit the ground when I got him with the launcher + downstrike smash attack with slashblades which tends to effect even those who are knockback immune. since I was fighting him directly on top of the tower so he wouldn't have a reason to apoc-smash, right...? 

perhaps also something with how he idles? cause I know sometime a fair way back I observed a thing where the golem went back into inactive mode but was in the air but upon coming back online when I returned he fell through one floor before he hit the ground which got him salty and he apoc exploded the floor out from under me... :V
