### ISSUE TITLE
Infernal mobs effects affect players in creative mode

### ISSUE THREAD

**Issue by saltyseadoggo** [AtomicStryker/atomicstrykers-minecraft-mods#450]
Infernal mobs will apply their effects to players in creative mode. For example, one with blastoff will launch creative mode players into the air, and one with alchemist will throw potions at creative mode players.
Mobs don't attack creative mode players, so one would expect infernal mobs effects to not affect creative mode players.

**Comment by AtomicStryker** [comment]
Sure, why not.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/9b6dcbea0365e988b51c2aef36feaed552d3f0b9

Infernal Mobs 1.19.2.2	
- creative players are no longer targeted by infernal effects
