### ISSUE TITLE
1.19.2 'What was changed in Infernal mobs?"

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AtomicStryker/atomicstrykers-minecraft-mods#451]
What is changed between infernalmobs-1.19.2.1.jar and infernalmobs-1.19.2.2.jar I am modpack dev so I need to know if it affects me.

**Comment by AtomicStryker** [comment]
See the changelog, the github commits, or the very next issue https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/450

**Comment by P3rf3ctXZer0** [comment]
ty yeah this is something I had issues with XD grabbed ;)
