### ISSUE TITLE
Impossible to disable a given mob 'tier' from spawning

### ISSUE THREAD

**Issue by saltyseadoggo** [AtomicStryker/atomicstrykers-minecraft-mods#453]
It doesn't appear to be possible to prevent a given mob 'tier'- rare, ultra or infernal- from spawning at all. I tried setting ultra and infernal's rarities to 0, which stopped *all* mobs with modifiers from spawning, including the rare tier ones that should still spawn. Setting their rarities to -1 had the same effect.
It should be possible to disable given tiers from spawning at all. If a player or modpack dev doesn't want the harder tiers to spawn, they should have the option. Likewise, if a player or modpack dev doesn't want the easier tiers to spawn, only the harder ones, that should be an option too.~

**Comment by AtomicStryker** [comment]
Wasnt the config implementaton "one in X" - if you dont want to see higher tiers, you need to set the values HIGH, not low.

You can force high percentages of high tiers with this. If you configure 1, 1, 1 all new mobs will be high tier infernals.

**Comment by saltyseadoggo** [comment]
Setting the mod rarities higher, to my knowledge, cannot possibly make them never spawn, only make them spawn very rarely.
You misunderstood what I was saying with only wanting to see high rarities. I meant that a player or modpack dev might want the ultra and infernal rarities to spawn as often as they currently do, but the rare ones to never spawn, so the only mobs with modifiers that they'll see have more modifiers. This would again require a way to disable a given tier from spawning at all.

**Comment by AtomicStryker** [comment]
Yes but effectively "one in a million" is the same as "never" to me, and good enough.

It is possible we are misunderstanding each other, so i will give examples:

This is the default config, i shall call this 15,7,7

  "eliteRarity": 15,
  "ultraRarity": 7,
  "infernoRarity": 7,

If i wanted ONLY ELITES without changing their absolute rate: 15,1000000,1000000
If i wanted ONLY ULTRAS without changing their absolute rate: 15,1,1000000
If i wanted ONLY INFERNALS without changing their absolute rate: 15,1,1

If i wanted the same rates as default except no ultras at all: 15,7,1
If i wanted the same rates as default except only ultras and infernals: 15,1,7
