### ISSUE TITLE
Infernal mob healthbars overlap WTHIT interface

### ISSUE THREAD

**Issue by saltyseadoggo** [AtomicStryker/atomicstrykers-minecraft-mods#454]
When looking at a mob with infernal mobs modifiers, the list of modifiers overlaps the interface from [WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit-forge), rendering the effect list illegible. One would expect Infernal Mobs to move the WTHIT interface down below its lines of text listing the effects the mob has, so they can always be read.

![2022-10-15_18 57 20](https://user-images.githubusercontent.com/69029346/196014377-518fe03f-c1db-48ac-9f5f-fe75e541e3e6.png)
![2022-10-15_19 01 31](https://user-images.githubusercontent.com/69029346/196014379-b9086ddd-69ca-405a-b5c8-11db259dabc7.png)

**Comment by AtomicStryker** [comment]
Infernal Mobs hacks into the vanilla boss bar in the current versions. In other words, WTHIT overlays the vanilla boss bar and you should complain there.

**Comment by saltyseadoggo** [comment]
> WTHIT overlays the vanilla boss bar

If you look at the pictures again, you can clearly see that it doesn't. WTHIT has a deliberate feature for moving out of the way of the vanilla boss bar; it's usually higher, and it will move lower if more boss bars are added. What it can't know to accommodate is text *under* the boss bar, which doesn't happen in vanilla or any mods other than Infernal Mobs, to my knowledge.

**Comment by AtomicStryker** [comment]
I checked and you are correct, the modifier text is actually drawn by me. Now you need to understand something about minecraft UI: They draw "blindly" onto the same canvas. They do not know about other mod UI. They can check the status of the vanilla boss bar. Infernal Mobs stops showing Infernals if a vanilla boss is displayed. WTHIT moves down a little if a vanilla boss bar [or Infernal Mob, as that uses vanilla boss bar] is visible. I can't "move" WTHIT on the screen whatsoever. What you are actually requesting is for WTHIT to check if an Infernal Mobs bar is visible and translate down the screen a little bit more.

**Comment by AtomicStryker** [comment]
Looking at WTHIT, i think you can configure the position of the overlay in your own config files, look for something like IWailaConfig.Overlay.Position

Alternatively, you can always disable Infernal Mobs boss bars
