### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KostromDan** [AtomicStryker/atomicstrykers-minecraft-mods#458]
Looks like Mutimine caused crash. 
[crash-2022-10-23_15.05.17-client.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/9846523/crash-2022-10-23_15.05.17-client.txt)
[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/9846524/latest.log)
This user has same error. https://forums.minecraftforge.net/topic/117065-error-javalangnullpointerexception-cannot-invoke-itunimidsifastutilintsintarraylistgetintint/

**Comment by AtomicStryker** [comment]
Yes, the packet handling was not thread safe and could have resulted in this.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/7e44892e308346d1c5242ba399c6484c409af282

Should fix it. I played a couple of minutes solo and on a local server and couldnt make it crash.

Version 1.19.2.2 is pushed to curse.

Thanks for the report.
