### ISSUE TITLE
RUINSTRIGGER scans the global te tick list

### ISSUE THREAD

**Issue by Player3324** [AtomicStryker/atomicstrykers-minecraft-mods#46]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.8/Ruins/src/main/java/atomicstryker/ruins/common/RuinsMod.java#L120

This scans the world's list, which isn't a great idea from a performance POV, and happens to conflict with Fastcraft avoiding to tick non-tickable tile entities. I could of course work around this, but the code should really scan the chunk's te map instead.

**Comment by AtomicStryker** [comment]
While the code is triggered by the player entering a chunk, it isn't exclusive to the chunk being entered. The set distance of 64 is multiple chunks across, so the chunk te map won't be enough. I could of course do something elaborate and have it scan the relevant adjacent chunks ...

**Comment by AtomicStryker** [comment]
Like this https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/4c134ef07a9a00ea70007d4c9013b050033ab4f3

**Comment by Player3324** [comment]
Ah I didn't look too closely, but this looks good. Scanning 81 chunks may potentially cause issues with heavy microblock/chisel users though.

**Comment by AtomicStryker** [comment]
ANYTHING causes issues with mods that overload a feature past the point of ridicule. What people are doing to nbt tags...
