### ISSUE TITLE
Dynamic Lights not working when joining server

### ISSUE THREAD

**Issue by EldraTheThird** [AtomicStryker/atomicstrykers-minecraft-mods#462]
when I join the server, the torch in my hand doesn't glow like in single player mode.
Here are the pictures I took when:
        In a server:
![2022-12-19_21 10 44](https://user-images.githubusercontent.com/108326998/208445560-99b34f10-6460-4a30-a864-edbba4390e59.png)
        In the single player world:
![2022-12-19_21 12 42](https://user-images.githubusercontent.com/108326998/208445662-bdd5b9a3-6404-4e71-94a3-5173e643aed2.png)
Use the latest Forge and mod versions

**Comment by EldraTheThird** [comment]
I use another skin in the server (with support for changing skins for Offline accounts)

**Comment by AtomicStryker** [comment]
In MC 1.18 and later, Dynamic Lights is no longer a clientside mod but a serverside mod.
That means in multiplayer the server needs to have it installed, not you.

**Comment by EldraTheThird** [comment]
Thank you! I guessed the same and installed another mod with the same feature Rubidium Dynamic Light
________________________________
Từ: AtomicStryker ***@***.***>
Đã gửi: 19 Tháng Mười Hai 2022 9:52 CH
Đến: AtomicStryker/atomicstrykers-minecraft-mods ***@***.***>
Cc: Itzz Parsher ***@***.***>; Author ***@***.***>
Chủ đề: Re: [AtomicStryker/atomicstrykers-minecraft-mods] Dynamic Lights not working when joining server (Issue #462)


In MC 1.18 and later, Dynamic Lights is no longer a clientside mod but a serverside mod.
That means in multiplayer the server needs to have it installed, not you.

**Comment by AtomicStryker** [comment]
Neat, hadn't heard of that before. They appear to manage the hack into the light cache which i decided was too hard to do in 1.18
