### ISSUE TITLE
For some reason it makes my game lag as hell, 1.16.5

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#465]
:/

**Comment by ghost** [comment]
Optifine Dynamic Light works fine in same time

**Comment by AtomicStryker** [comment]
Optifine has the massive advantage of doing light in the GPU Shader, which does not tax the CPU at all. Downside is it can't really do light sources other than yourself. (Atleast it used to be like that).

Dynamic Lights currently fakes constantly putting and removing light blocks, which is very CPU intensive.

**Comment by ghost** [comment]
Will you improve this?

**Comment by AtomicStryker** [comment]
No. I cannot. Dynamic Lights used to hack into the MC light cache for somewhat better performance, but with their improvements on the light engine in recent years this has went beyond my abilities. Using a stronger PC alleviates the issue.

**Comment by ghost** [comment]
Stronger PC than Ryzen 2600 + RX 6600? Why? It's not even loaded at all

**Comment by AtomicStryker** [comment]
Thats because that Ryzens strength is multicore work, MC is very much single core load, which that CPU does not excel at.

**Comment by ghost** [comment]
Or your mod poorly written since I never had lags like this even with 300+ mods pack
