### ISSUE TITLE
Crash when breaking travelers backpack

### ISSUE THREAD

**Issue by KostromDan** [AtomicStryker/atomicstrykers-minecraft-mods#466]
[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/10704013/latest.log)
[crash-2023-02-10_08.40.28-client.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/10704017/crash-2023-02-10_08.40.28-client.txt)

**Comment by AtomicStryker** [comment]
TickEvent.LevelTickEvent is somehow firing concurrently in your crash log. A second tick of phase END is executing before the first is finished. I can only suspect another mod is responsible for that?!

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/9bcf22cb044e98ae778ed457566d4aefcdd7c2a0
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/130986d742d786ef469ff868827b0fc66459f479
Well i am pushing the same concurrency bugfix i did here https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/467 for Multi Mine 1.18, same reasoning.

You probably have another mod causing a problem and will now crash with something else. Multi Mine 1.19.3.2 is pushed to curse

**Comment by AtomicStryker** [comment]
Should be fixed with the changes from https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/467. It was my fault after all ;)
