### ISSUE TITLE
InfernalMobs - Webber Range

### ISSUE THREAD

**Issue by xd4rkzghost01** [AtomicStryker/atomicstrykers-minecraft-mods#468]
Got a little issue with the Webber effect. As soon as i enter a cave with a couple of mobs, those one with "Webber" Effect can cast their thing like 100 block away from me. I was mass stuck with web and force to looks with Spectator mode to search where the mobs are. I was at level  y103 and Skellys was at -37 and still Webbing me. I dunno if you can reduce the range of this effect. Effect still cool but at a close combat range, not when i'm building "couple" block away.

Some encounter here
![2023-02-20_14 57 46](https://user-images.githubusercontent.com/63568312/220189678-c0443615-56b5-403c-bdc4-a857a8a2b49e.png)
Another Culprit there
![2023-02-20_14 58 24](https://user-images.githubusercontent.com/63568312/220189680-06e96cd5-5f78-4599-a9a1-c413880c363e.png)
And the picture before. Webbing me at this height.
![2023-02-20_15 00 16](https://user-images.githubusercontent.com/63568312/220189683-6229b1fe-2b03-438f-a3ba-a3c4c6d787d0.png)

**Comment by AtomicStryker** [comment]
Hmmm i do not in fact have a range limit implemented, it works off the Minecraft "target aquisition", that Skeleton is trying to arrow you. Also breaking line of sight (25% visibility) should prevent you getting webbed.

This is 1.19?

**Comment by xd4rkzghost01** [comment]
Minecraft 1.19.2 (modded as u see, 212 in this) 
Forge 43._2.0_
Also that baby Skellys is from Born in Chaos but as i said, he was underground at -55 (pic2), and i was in spectator mode to take the Screenshot. As soon as i exit spectator mod on top of my building (pic3), i got webs. The mobs you can see on the map (red dot) don't have any effect on them. And it only happen when i try to go into a cave under that base. The tunnel i made drop into an amethys cluster and i being web even if i or any mobs can see me.

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/81b01eb4988bebb7c24ffa7c297bc85c1b09fcb5

Pushed new version of Infernal Mobs to curse which both introduces a max spell range of 20 blocks and also fixes the wrong implementation of the visibility check. Its called "isVisible" in the mappings but does something different (checking if you are wearing a skull head etc... )

**Comment by xd4rkzghost01** [comment]
Sorry my english is not very good. I don't understand what you mean by "pushed" new version. But i also encounter this with the effect "BlastOff" (dunno if i need to open a new issue for that, tho i think its the same situation)
I was killing zombie and skellys here, peacefully.
![2023-02-23_11 29 50](https://user-images.githubusercontent.com/63568312/221009457-9afa1d99-7d23-41b0-9995-183c99b9cdad.png)

And then got "Blastoff" by this dude. A couple block away from me.
![Blastoffguy](https://user-images.githubusercontent.com/63568312/221010631-4241e38c-326f-425d-89e6-c180cd6eeac8.gif)

The effect start as soon as i hit the 1st mob in the previous area. Its look like whenever i hit a zombie, the new mechanic (the leader king zombie) make them all agro to me and those with Infernal Effect like "BlastOff" and "Webber" can use thier effect on me. And as i said before , even if i leave the cave and climb up to Y70, i still got kick in the air. I'm force to go in spectator mode to avoid another lunch/webs. 
For the moment, i disable Webber because it was very annoying (got Web on an island thousand block away).
![2023-02-23_14 37 22](https://user-images.githubusercontent.com/63568312/221012523-8f001e96-96ff-400f-b719-f43758a8d07b.png)

**Comment by AtomicStryker** [comment]
It means i have made 1.19.3.3 of Infernal Mobs available at curse, see here:
https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-infernal-mobs/files

It contains the bugfix for you
