### ISSUE TITLE
Mutimine small freze.

### ISSUE THREAD

**Issue by KostromDan** [AtomicStryker/atomicstrykers-minecraft-mods#470]
https://youtu.be/Jcfq_5MkOQ0

**Comment by AtomicStryker** [comment]
It's a slight client/server desync because Multi Mine triggers a block break the client doesnt "expect" yes.
Can't really do anything about it.

**Comment by KostromDan** [comment]
But sometimes it can take up to 15 seconds. Its annoying. Now i filmed 5 second freeze. I don't know much about creating mods, but isn't it possible to do when the block is actually broken on the client side, send a request to the server, which will be processed immediately and break the block on the server side? After all, I do not experience any frieze when the block breaks with a pickaxe with an efficiency of 5.

**Comment by KostromDan** [comment]
https://youtu.be/OpFMnAhuhbI

**Comment by AtomicStryker** [comment]
But this only happens if you "inch" towards block completion, no? If you mine it as if Multi Mine wasnt there, it breaks normally?

**Comment by KostromDan** [comment]
This occurs mostly when using the initial tools during a hike in the mine. It was when he accidentally did not break the block, moved on to the next one, noticed that the block was not broken and broke it. That is, it is the case of multimine.

**Comment by KostromDan** [comment]
![image](https://user-images.githubusercontent.com/90044015/226444639-96c67eed-91e7-4b20-98ca-bebd1eb2353e.png)
@AtomicStryker  Unfortunately, as the creator of the millionaire modpack, I am tired of receiving such messages. And forced to remove the mod. I would advise you to think about how to fix it. There is a problem not only with "inch" towards block completion, but also in almost all cases when multimine works. A lot of players of my modpack face this and it annoys them a lot. This problem can clearly be solved with a delay of at most a player's ping. Now, while the server realizes that the block is broken, it may take 10 seconds. I once again suggest implementing a client-side check, which, if it sees that the block is really broken, and the server says that it is not, and forcibly breaks the block, is possible, the only question is how difficult it is

**Comment by KostromDan** [comment]
https://www.youtube.com/watch?v=rL8yOm4Dg80

**Comment by AtomicStryker** [comment]
I'd like to point out in that newest video you again "inch" the final block breakage, which is the known issue. OK i can generally speaking have a look at this topic again, but please:

- which version of MC, forge, and the mod is this
- is this local host? dedicated online server?

**Comment by KostromDan** [comment]
1.19.2 , 43.2.7, MultiMine-1.19.2.3
Absolutely same in single, server.
Here is not inch, but std multimine case.
https://youtu.be/2oskZ34tdxQ

**Comment by AtomicStryker** [comment]
I could recreate your issue and create a version that worked for me, both singleplayer and localhosting a server.
MC now keeps block destruction progress in the serverside gamemode i guess.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/0eeee47ce80b9689449e1ec3f67c53dd16707acd

I have pushed this as version 1.19.2.3 to curse, which did not exist until then. 1.19.2.2 was the latest.

**Comment by KostromDan** [comment]
Yes, the problem is completely fixed. I can't even repeat "inch" the final block breakage.
