### ISSUE TITLE
1.18.2 config Question

### ISSUE THREAD

**Issue by PatrickPichler98** [AtomicStryker/atomicstrykers-minecraft-mods#471]
Hello is there a way to blacklist all "wood log" ?
i play with HT's TreeChop, but with MultiMine the chop system doesn't work

**Comment by AtomicStryker** [comment]
See the changelog or the closed issues, please, this was already asked and handled.
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/440
