### ISSUE TITLE
[Request] A way to prevent Multi Mine's config from populating itself

### ISSUE THREAD

**Issue by aaronhowser1** [AtomicStryker/atomicstrykers-minecraft-mods#477]
I understand this is probably a holdover from older versions, where knowing the block/item ID wasn't easy. But it's a lot easier these days, and if I want to add something to the blacklist, it should be on me to find its ID.

Plus, it's rather annoying for pack dev, as it's always filling up the changed files list
![image](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/15698722/17eaa7c2-98ce-42fc-9f44-7d360d5d17f8)

This is on MultiMine-1.19.2.3 as well

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/ad91f5b14dcb1d227a7f4e0113511084558872b2
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/bad7349bcea18634a8c8b5ba8ca08d4f208a4a82

I have implemented your request for the current 1.19.4 and 1.20.1 versions and also pushed a build for 1.19.2 to curseforge for you

**Comment by aaronhowser1** [comment]
Thank you!
