### ISSUE TITLE
this mod literally not working with modded items...

### ISSUE THREAD

**Issue by Gintas2002** [AtomicStryker/atomicstrykers-minecraft-mods#478]
Is modded items even compatible??? Because config exists so i guess you can put modded item to make them glow but how?? The mod i want to make glow is hardcore torches, so i put the lines there's, and now when joining world its not responding, am i doing something wrong?
![image](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/79921055/4bc09d69-fe2c-48c3-939d-1bf7ee3699f9)

**Comment by AtomicStryker** [comment]
The last commas in lines 4 and 8 may have to go. The final items in a json list do not have comma after them.

Otherwise post the error log you get from MC.
