### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [AtomicStryker/atomicstrykers-minecraft-mods#479]
Is this GitHub for all mods combined?

**Comment by AtomicStryker** [comment]
yes

**Comment by Fireworkstars46** [comment]
Cause I have a question about the dynamic lights mod. Is there a setting or way for me to change the lights type (fancy fast etc)?

**Comment by AtomicStryker** [comment]
You mean on top of the Minecraft option itself? no

**Comment by Fireworkstars46** [comment]
What about in general or the config file or something?

**Comment by AtomicStryker** [comment]
I dont follow. Dynamic Lights is not implementing a seperate light engine that could be configured. It uses the minecraft light engine which you can set to fancy in ingame options, and that is it.

**Comment by Fireworkstars46** [comment]
Cause I'm on the 1.6.4 version of the mod and in the Minecraft settings there's no options for fancy etc.

**Comment by AtomicStryker** [comment]
No, the mod does not add new light options to minecraft.

**Comment by Fireworkstars46** [comment]
So on my version of it I won't be able to change it?

**Comment by AtomicStryker** [comment]
No, the mod does not add new light options to minecraft.

**Comment by Fireworkstars46** [comment]
Would you be be willing to add that option in a later update of it? If so I'm hoping all the versions will have it and not only the newer ones.

**Comment by AtomicStryker** [comment]
No, the mod does not add new light options to minecraft.

**Comment by Fireworkstars46** [comment]
So it won't be possible add that feature in a next update and the mod can't support that feature?

**Comment by Fireworkstars46** [comment]
Also is there any discord for it?

**Comment by AtomicStryker** [comment]
No, there is no Discord, at least not run or visited by me

**Comment by Fireworkstars46** [comment]
Cause I have an issue with the dynamic lights mod and was hopping for a faster place for it
