### ISSUE TITLE
modded storage and Ruins

### ISSUE THREAD

**Issue by Nykrdaudr** [AtomicStryker/atomicstrykers-minecraft-mods#491]
Hi again.
in [490](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/490) you helped me out quite a bit, but im still stuck on one thing... how do i write this out?
"chestgenhook" [to get the loot table] +
"sevendaystomine:bookshelf" [the name of the block] +
"sevendaystomine:bookshelf_common" [the name of the loot table]

**Comment by AtomicStryker** [comment]
You should ask in minecraftforums or a forge discord, this is not a support hotline. I will help this final time

See an existing chest from some template i pulled:
rule1=0,100,{Ruins:{entity:{ForgeData:{LootTable:"minecraft:chests/simple_dungeon"},Items:[],Lock:""}},Properties:{waterlogged:"false",facing:north,type:"single"},Name:"minecraft:trapped_chest"}

Adjust the relevant fields to your case, drop the chest specific ones
rule1=0,100,{Ruins:{entity:{ForgeData:{LootTable:"sevendaystomine:bookshelf_common"}}},Name:"sevendaystomine:bookshelf"}

This may work, it may not, you need to use the ingame parser to store one of these bookshelf tile entities so you can see which properties they have. There will very likely be a facing property at the very least.
