### ISSUE TITLE
backport "anyNbtMatch" tag to 1.19.2

### ISSUE THREAD

**Issue by 0culist** [AtomicStryker/atomicstrykers-minecraft-mods#493]
Could you consider backporting functionality added in 1.19.4 commit [74b2c68](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/74b2c68c1344bffe0944b18395003c319c8c7fce) to 1.19.2?

**Comment by AtomicStryker** [comment]
I've pushed this version to curse for you.

1.19.2.2 (backport)
- you can now configure itemstacks to ignore nbt tag equality, to shine light from items that could be
  enchanted or damaged. example: {anyNbtMatch:true,lightLevel:14s,nameId:\"minecraft:flint_and_steel\"}
  the important part is adding anyNbtMatch:true to the tag list
