### ISSUE TITLE
AtomicStryker's Infernal Mobs crashes once I write text id to the config in "dimensionIDBlackList": [],

### ISSUE THREAD

**Issue by Artemian** [AtomicStryker/atomicstrykers-minecraft-mods#494]
AtomicStryker's Infernal Mobs (The latest 1.20.1 version) crashes once I write text id to the config in "dimensionIDBlackList": [], for example when I write "dimensionIDBlackList": [aoa3:archaic_extraction_station_arena]. I have attached the crash-log
[crash-2023-11-28_13.07.37-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/13487718/crash-2023-11-28_13.07.37-server.txt)
.

**Comment by Artemian** [comment]
![config](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/48186035/d5c5126d-56e9-48e4-a1a5-bc27f7a61386)
And this is how the config looks.

**Comment by AtomicStryker** [comment]
dimensionIDBlackList is a String list, exactly the same as droppedItemIDsInfernal for example. So it has to have the same json/gson format. Try like this:

  "dimensionIDBlackList": [
    "aoa3xxxxx"
  ],

(You are missing the quotes around your aoa3 string)

**Comment by Artemian** [comment]
Thank you for the fast reply. That was indeed the problem, it works now! 

Also thank you for this great mod. I have been using it for so many mc versions throughout the years :)
