### ISSUE TITLE
Ruins Double Spawning

### ISSUE THREAD

**Issue by helixyuri** [AtomicStryker/atomicstrykers-minecraft-mods#496]
I was wondering if there was a way to fix ruins spawning in doubles. I have tried changing the ruins distance options to no effect.
I am using the latest 1.12 version.

![2024-01-09_12 28 57](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/48564473/e5865337-adc3-4394-9d60-7ab6df3f1e9d)
![2023-11-28_07 04 22](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/48564473/38b0537e-73d7-45bb-befd-5db1c505425a)

**Comment by AtomicStryker** [comment]
Sorry, i dont support the old 1.12 version anymore. Just looking at the changelog, version 17.3 which you should be running should have variables "spawnMinDistance" and "spawnMaxDistance" implemented.

Ask in the mcf thread for Ruins, perhaps the good people there can help you: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1282339-1-15-2-ruins-structure-spawning-system
