### ISSUE TITLE
Help with config please! (version 1.12.2)

### ISSUE THREAD

**Issue by diploscat** [AtomicStryker/atomicstrykers-minecraft-mods#499]
I don't know if the mob health factor affects only infernal/elite/ultra mobs? Also, under droppable items in the loot tables, can I pick from any mod and in what way do I list it? For example, do I list a transmutation table (from ProjectE) as transmutation_table or mod specific such as projecte:transmutation_table???

**Comment by AtomicStryker** [comment]
The health formula affects all modded mobs and amounts to:
mob class modifier (per-mob configurable value) * amount of infernal mods * mod health factor (configurable)

You can put in any modded item in its nbt/json string format. If you don't know how to figure that out, i'm sure there is resources and mods for that. I don't have any built-in methods.

**Comment by diploscat** [comment]
Thank you! you are the best!

> The health formula affects all modded mobs and amounts to: mob class modifier (per-mob configurable value) * amount of infernal mods * mod health factor (configurable)
> 
> You can put in any modded item in its nbt/json string format. If you don't know how to figure that out, i'm sure there is resources and mods for that. I don't have any built-in methods.
