### ISSUE TITLE
Crash after hitting a creeper on a slime at a dungeon

### ISSUE THREAD

**Issue by AikamiT** [AtomicStryker/atomicstrykers-minecraft-mods#500]
I'm testing the mods I've installed in a Minecraft version **1.20.2** and when I tried to **hit** the creeper, it crashed my game.
The same happened when the creeper **tried to explode**.
I also tried with other entity (zombie) and the same happened when I hit the zombie.

![Error creepr](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/74986182/b557eb68-6344-47e7-93a8-7f80b56f5693)
[crash-2024-02-21_15.57.33-server.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/14365561/crash-2024-02-21_15.57.33-server.txt)

I don't really know what could be wrong, but maybe there's a lot of incompatibility with the mods I have?

**Comment by AtomicStryker** [comment]
It looks like a forge version incompatibility. You use forge 48.1.0, that version of infernal mobs was built against 48.0.6

Let me see about updating that for you: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/e80b02ae230f516c7624e225c38d6c4a57b5659f

Pushed a new version of infernal mobs for MC 1.20.2 to curse for you.

**Comment by AikamiT** [comment]
Thank you so much Atomic, I tested the mod and everything's working just fine!

Biiiiig W
Sorry for putting on you more work tho.
