### ISSUE TITLE
Can you give more information of the config of Infernal Mobs?

### ISSUE THREAD

**Issue by HySand** [AtomicStryker/atomicstrykers-minecraft-mods#501]
What mobFarmCheckIntervals and mobFarmDamageTrigger mean and what are their units.

**Comment by AtomicStryker** [comment]
So if Infernal Mobs mob farm check is enabled, every time a mob is hurt (not just infernals), i increment a "damage" counter for the world chunk the damage happened in.

mobFarmCheckIntervals is ms, how often should the timer logic checking for a mob farm run.
mobFarmDamageTrigger is MC damage sum that chunk should not go over.

If a check in mobFarmCheckIntervals finds that any map chunk has its damage counter go over mobFarmDamageTrigger value, we assume a player has built some automated torture device there rapidly damaging/killing mobs, far faster than a player could.

This posts a forge MobFarmDetectedEvent ... and does nothing else.
Huh, i thought i had implemented tnt explosions in response or something, but maybe i forgot.

**Comment by HySand** [comment]
Maybe stop spawn infernal mobs or remove their loot if `X` mobs are killed in `Y` minutes in one chunk for `Z` minutes

**Comment by AtomicStryker** [comment]
Nah, the entire concept is backwards. What should be done instead is catching all the damage types that can be automated (crushing, drowning etc) and simply despawn Infernal Mobs being killed by those, or turn them into normal mobs.

But that would require research and effort on my part, and i do not have the spare time.
