### ISSUE TITLE
NeoForge version not able to join vanilla servers.

### ISSUE THREAD

**Issue by Jeppa** [AtomicStryker/atomicstrykers-minecraft-mods#502]
Using the NeoForge version I can not connect to vanilla servers anymore (this is possible with forge version...)

Other plugins in NeoForge like MiniMap or JEI don't have this issue/limitation.

There's not much in the logfile: (test on a local server)

`[02März2024 12:37:51.297] [Render thread/INFO] [net.minecraft.client.gui.screens.ConnectScreen/]: Connecting to 192.168.1.1, 25560`
`[02März2024 12:37:51.303] [Server Connector #1/DEBUG] [net.neoforged.neoforge.network.DualStackUtils/]: Detected IPv4 address: "192.168.1.1"`
`[02März2024 12:37:52.728] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl/]: Client disconnected with reason: You are trying to connect to a server that is not running NeoForge, but you have mods that require it. A connection could not be established.`
`[02März2024 12:37:55.907] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!`

**Comment by AtomicStryker** [comment]
Which mod is this? I found something in the neoforge packet registry, but it shouldn't affect my mods which dont do networking (Dynamic Lights for example).

**Comment by Jeppa** [comment]
Hups, I did forget to say it's 
FinderCompass ;)

**Comment by AtomicStryker** [comment]
Alright, i have updated the relevant neoforge mods so that connections with clients/servers lacking the mods is possible.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/c662924d8b304cee561b32a1fbaf5f08120fd6f2

Pushed new versions to curse, they should be available there shortly.

**Comment by Jeppa** [comment]
Update works great ;)
