### ISSUE TITLE
Light semi-working?

### ISSUE THREAD

**Issue by BORTlort** [AtomicStryker/atomicstrykers-minecraft-mods#503]
![2024-03-04_12 38 54](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/161553551/667e3e18-c6e5-4fd8-ac79-aec8c46dba5f)

As you can see in the screenshot, there is no light; but block entities, such as the chest, glow. I don know what causes this. Any help would be appreciated.

**Comment by BORTlort** [comment]
The problem was that I had a version that was incompatible with Sodium, which is a problem that has been addressed by the author (for future reference)

**Comment by AtomicStryker** [comment]
For future reference, you always want to mention exactly what is malfunctioning (Dynamic Lights? Which version of it, which version of minecraft?), and ideally provide the minecraft logfile.

**Comment by BORTlort** [comment]
I didn't mean for your future reference. I meant for people who go scouring the internet like I did to find a solution, so don't get offended and use that sarcastic tone with me. You made the mod; have a bit of humility.

**Comment by AtomicStryker** [comment]
I was in fact thinking of the same people. How would they google upon this? You left out all the important key words. I was not being sarcastic.
