### ISSUE TITLE
Any plans to add a mod to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [AtomicStryker/atomicstrykers-minecraft-mods#504]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if Battle Towers was also in Modrinth, otherwise I have to download it separately for each modpack, but this is very inconvenient when creating modpacks.

**Comment by AtomicStryker** [comment]
No plans, no. I haven't developed Battletowers since MC 1.12.2, so late 2017. There is atleast two successor mods for more current versions. Ask them :)

**Comment by Alter73** [comment]
OK, thanks for the reply! It's a pity, I just need a version for 1.12.2, but there are no any forks for this version (
