### ISSUE TITLE
[1.20.1] Multi Mine: Server Hangs When Rejoining World After Breaking Multiple Blocks

### ISSUE THREAD

**Issue by DeshiDesu** [AtomicStryker/atomicstrykers-minecraft-mods#507]
MC 1.20.1
Forge 47.2.32
multimine-1.20.1.3.jar

Break multiple blocks but not completely, then leave and rejoin the world and the loading gets stuck at 100%

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/120287925/518b021e-beab-4e2f-a0f9-020dd01766a6

**Comment by AtomicStryker** [comment]
Nicely comprehensive report, thank you.
Fixed: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/f5f72402fdb41e329756aeb1b0ccbcd8eb17220d

I also fixed it for 1.20.6, but i wont bother merging to my dozen branches. It's kind of a niche issue.
