### ISSUE TITLE
Modded item support?

### ISSUE THREAD

**Issue by xJon** [AtomicStryker/atomicstrykers-minecraft-mods#508]
From looking at the config files, it seems only vanilla item IDs are supported, is that true?

`dynamiclights_dropitems.cfg`
```
# Configuration file

general {
    # Item IDs that shine light when dropped in the World.
    S:LightItems=torch,glowstone=12,glowstone_dust=10,lit_pumpkin,lava_bucket,redstone_torch=10,redstone=10,golden_helmet=14

    # Item IDs that do not shine light when dropped and in water, have to be present in LightItems.
    S:TurnedOffByWaterItems=torch,lava_bucket

    # Update Interval time for all Item entities in milliseconds. The lower the better and costlier.
    I:"update Interval"=1000
}
```

Playing on 1.12.2.

**Comment by ACGaming** [comment]
Looks like you can provide any item with domain, you can just omit `minecraft:` when specifying vanilla items: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.12.2/DynamicLights/src/main/java/atomicstryker/dynamiclights/client/ItemConfigHelper.java#L65-L68

**Comment by AtomicStryker** [comment]
Yes, the only nod to vanilla items is that i automatically add the minecraft: prefix otherwise they are not handled any differently than mod items. Configure away
