### ISSUE TITLE
Dynamic Light Selflight File Not Working Past 2 Original Entries

### ISSUE THREAD

**Issue by 704Prod** [AtomicStryker/atomicstrykers-minecraft-mods#509]
Hey, I'm confused. Am I not formatting this correctly?
Nothing besides the original minecraft:torch & minecraft:glowstone will emit light from the  selflight.cfg
Here's how I have it set up

https://pastebin.com/ecnuC8fL

**Comment by AtomicStryker** [comment]
What version of MC is this? If the mods use very complex items with nbt metadata, you may have to add anyNbtMatch for Dynamic Lights to recognize matches. I checked one of your strings, ars_additions:golden_lantern seems to be the correct string to me.

**Comment by 704Prod** [comment]
Hey, sorry for the late reply.
I'm on 1.19.2

**Comment by AtomicStryker** [comment]
Try it like this

    "{anyNbtMatch:true,lightLevel:15s,nameId:\"ars_additions:golden_lantern\"}",

**Comment by 704Prod** [comment]
Sorry for the late response, going to try this soon
