### ISSUE TITLE
[1.20.1] Game crashes during world generation

### ISSUE THREAD

**Issue by GenericCherrySwitch** [AtomicStryker/atomicstrykers-minecraft-mods#517]
The game crashes during world generation due a JSON-related issue.
I've also noticed that in the logs as a world was being generated, the same error message keeps appearing in the logs until it crashed.
I'm not sure if this is a valid report given I'm using an older version of Forge which I'm using for Sinytra, but I figured it might be worth reporting regardless.

The crash report file can be found here:
https://gist.github.com/GenericCherrySwitch/aa60fbb2bfa6f14f50a07a148fc77098

**Comment by AtomicStryker** [comment]
Hi, this means you have an old infernal mobs config in that folder. The format changed and cant be read anymore.
Just delete it and let it auto-regenerate.
