### ISSUE TITLE
License file no longer accessible

### ISSUE THREAD

**Issue by Libadoxon** [AtomicStryker/atomicstrykers-minecraft-mods#521]
The License on CurseForge for [stalker-creepers](https://www.curseforge.com/minecraft/mc-mods/stalker-creepers) says to find it at http://atomicstryker.net/about.php but I get a File not found error when trying to open it. There also isn't a License on github so maybe consider adding one in the future

**Comment by AtomicStryker** [comment]
Thanks for the info. I have updated the readme in the 3 main branches of this repository and also the curse stalker creepers "license" entry.
