### ISSUE TITLE
Inventory Generator Recipe Error

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [AtomicStryker/atomicstrykers-minecraft-mods#522]
**Versioning**
Minecraft 1.20.1, NeoForge (final version for 1.20.1), Inventory Generators 2.0.0

**What did you do**
I have EMI and JEI installed, and when looking at the recipe for the Halitosis Generator, I noticed that the recipe was flawed.  Instead of 5 purpur blocks, it shows the red cross out missing item symbol, and hovering over them it says "Empty Tag:minecraft:purpur_block" (which is how I know that it's supposed to be a purpur block).

I checked out the purpur block, as I have CraftTweaker, and running /ct hand, the correct tag for the purpur block is <item:minecraft:purpur_block>, so I'm guessing you got the "<item:" part wrong or something?!?  Don't know...

**Expected behavior**
A valid recipe for the Halitosis Generator.

**Screenshots/Video**
I can if you want, but it's exactly as I described (I made sure i typed the error message exactly as it is spelled in game)...

**Comment by AtomicStryker** [comment]
A bit confused ... and why are you here? Inventory Generators is over there: https://github.com/kjmaster1/Inventory-Generators-New

**Comment by 7OOTnegaTerces** [comment]
Sorry about that, I don’t know how I got here either!!!
