### ISSUE TITLE
Certain attributes seem to crash the server

### ISSUE THREAD

**Issue by darock830** [AtomicStryker/atomicstrykers-minecraft-mods#523]
**Versioning**
Minecraft version 1.21.1
Latest neoforge launcher

**What did you do**
Both server and clients have the mod installed. As the player, I do not need to do anything. I am just moving around, and suddenly, there is a crash, and the server shuts down. I can then reopen the server, but the moment I join the game it crashes again. I have to uninstall the mod on both server and client to be able to join. Then, with the mod uninstalled, sometimes, as soon as my player joins first time after uninstalling the mod, it dies. Other times, the player simply joins the game with no issue. Afterwards, I am able to add the mod again for both server and clients, and the game runs fine until I run into a similar issue. I have managed to reduce the crashes by disabling attributes that the crash report tells me caused the crash. So far they were "gravity" and "sprint." I attached the crash reports to this report.

**Expected behavior**
I expected all the attributes to work.

**Screenshots/Video**
[crash-2024-10-09_12.27.58-server.txt](https://github.com/user-attachments/files/17311865/crash-2024-10-09_12.27.58-server.txt)
[crash-2024-10-04_21.59.24-server.txt](https://github.com/user-attachments/files/17311866/crash-2024-10-04_21.59.24-server.txt)

**Comment by AtomicStryker** [comment]
Cheers, found a problem with choke, gravity and blastoff mods. Sprint does not send packets.
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/d7451a31aef9657628a752e8eeb62d325b21024d

New version is pushed to curse.

**Comment by darock830** [comment]
Amazing. Thank you! I am going to test it right now :)
