### ISSUE TITLE
Another ruins issue encounter on 1.19.2

### ISSUE THREAD

**Issue by Paraasoul** [AtomicStryker/atomicstrykers-minecraft-mods#528]
**Versioning**
Which version of Minecraft, which mod version, and which modloader are you using (Forge, Neoforge etc).
Some error reports don't even specify which mod has a bug...
I'm using Forge 1.19.2-43.2.14 and ruins 1.19.2.1
**What did you do**
What do i have to do on my end to see the problem.
I installed forge 43.2.14 for optifine to also work but instead i was greeted with an error saying "atomicstryker/common/Ruinsmod.<init>()
**Expected behavior**
Like forge 43.4.6, i expected it to work even with your help fixing the bug/issue but nope. and even with the ruins config put into the configs file, nope. I hope you can fix my problem right now with the current mod.
**Screenshots/Video**
If applicable, add media to help explain your problem.
![Screenshot_2024_1205_213406](https://github.com/user-attachments/assets/1ce7fe70-7e3d-4f0a-ab2a-89ae4431b94e)

**Comment by AtomicStryker** [comment]
Click open latest.log and upload that file here. It works with the non Optifine Forge?


Just from looking at the error message, it looks like Optifine Forge is expecting a mod constructor without arguments, but that is not the Forge API. It would suggest Optifine Forge needs to be updated?

**Comment by AtomicStryker** [comment]
Ruins for 1.19.2 requires the current forge 43.4.5

There is no Optifine version that supports that version of forge.

See https://forums.minecraftforge.net/topic/144050-exit-code-1-when-running-forge-4330-with-optifine/

Apparently there is another optimization mod called Rubidium which is compatible, and you can use something called Oculus for shaders.

**Comment by Paraasoul** [comment]
Oh alright.
