### ISSUE TITLE
Infernal Mobs Crash

### ISSUE THREAD

**Issue by Svedrigailov** [AtomicStryker/atomicstrykers-minecraft-mods#53]
Crash Log
http://hastebin.com/disihobane.vala

Assuming it's the same forge voodoo.

**Comment by AtomicStryker** [comment]
Dealt with as of https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/06d62249ef93279a4ea8393edb9c97e2ba2a97bd
