### ISSUE TITLE
[1.9] InfernalMobs Network NPE

### ISSUE THREAD

**Issue by MrKrabat** [AtomicStryker/atomicstrykers-minecraft-mods#56]
Hello,

directly after connecting to a server the client gets a network error and disconnect.
For the server its just a disconnect.

Client-Log: https://gist.github.com/MrKrabat/57dd3d4fd40c3d6bad3cd9da3a729f0a
The NPE which terminates the connection occurs after line 9000.

**Comment by AtomicStryker** [comment]
Error is in MobModsPacket.java:48, i will check it out later.

**Comment by AtomicStryker** [comment]
See https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/37fe71fc64d78bd8ce76081878de8ac91d98adfe which likely fixes it.

I am not pushing a new version as Forge has once again done a total refactor which will necessitate a new port anyway.
