### ISSUE TITLE
Config Request

### ISSUE THREAD

**Issue by bookerthegeek** [AtomicStryker/atomicstrykers-minecraft-mods#57]
Hello!

Just a quick question and request:
- Global config for dimension Whitelist
- % of mobs spawned to be infernal.

I am attempting to make every mob in the nether infernal. But only in the nether. If this is already possible and I derped while looking at the configs I do apologize and abase myself for your forgiveness.

**Comment by AtomicStryker** [comment]
Dimension specific numbers aren't implemented. The second is done by config, and you can force certain (nether only) entities to be always infernal too.

**Comment by bookerthegeek** [comment]
Thanks for the quick response. I will go and scour the configs to make those changes. :)

Would Dimension Specific be something that could be added? Preferable as a whitelist.

**Comment by AtomicStryker** [comment]
There is already a dimension blacklist, i checked. So, no.
