### ISSUE TITLE
Infernal Mobs cause server to skip 400 ticks

### ISSUE THREAD

**Issue by APolarBaer** [AtomicStryker/atomicstrykers-minecraft-mods#58]
constantly, started happening just with the addition of infernal mobs, its not every but it seems to be one type that does it, its fairly common but just sitting at a spawner does it

**Comment by APolarBaer** [comment]
1.9.4 infernal mobs only 1.9.4 version lol

**Comment by AtomicStryker** [comment]
Try disabling the "mob farm detection" feature, i dont recall the config line

**Comment by APolarBaer** [comment]
i shall and will let you know if it fixes it

**Comment by APolarBaer** [comment]
I forgot to let you know, I am so sorry. I believe it did because I haven't had the issue since

**Comment by AtomicStryker** [comment]
No problem. Issues resolving themselves are the best ones

**Comment by APolarBaer** [comment]
Still using the mod btw, love it. Hate sticky though xD your so cruel. Have to turn either ninja or ender off because they jump into the ground and then regen as fast as they die most of the time

**Comment by siccaxe** [comment]
Sorry to necro this, hoping I can address a similar issue. 

    I:AntiMobFarmCheckInterval=30
    B:AntiMobfarmingEnabled=true

Does this feature just prevent infernal's from spawning in an identified mob farm?

Is setting it to false enough to disable this feature, or does the checkinterval need to be changed?

Thanks!

**Comment by AtomicStryker** [comment]
I think it does nothing, as of now. It was intended to eventually block mob farms, but nobody ever got back to me with the information it is providing so i could implement it into something actually working ... i think ... i don't remember honestly

EDIT:
To answer your question, changing true to false will disable it.

**Comment by siccaxe** [comment]
Cool, figured it was worth a shot. thanks

**Comment by APolarBaer** [comment]
Atomic if youd like information for it let me know what i need to do and ill do what i can owo idm helping out
