### ISSUE TITLE
No 1.10.0 version

### ISSUE THREAD

**Issue by kesu1** [AtomicStryker/atomicstrykers-minecraft-mods#60]
There is no 1.10.0 version, just 1.10.2 and 1.9.4, The 1.9.4 version does load up, but it doesn't work. Inside the downloaded zip, there is a file called "MultiMine 1.10.jar" ,but it also require 1.10.2 forge. Please add a 1.10.0 version, Thanks.

**Comment by AtomicStryker** [comment]
Sorry. The Version does exist in the repo history but I won't bother
