### ISSUE TITLE
[1.10.2] Client NPE

### ISSUE THREAD

**Issue by t3f** [AtomicStryker/atomicstrykers-minecraft-mods#61]
Client Null pointer exception encountered.

https://gist.github.com/t3f/d3e8ee968322a558498e3230f741d920

**Comment by AtomicStryker** [comment]
What was the situation in which this happened? Either FML controller or internal mc server were null, which should never happen during playtime ever.

**Comment by t3f** [comment]
I had just battled a lightning creeper, not sure what else was going on.

**Comment by AtomicStryker** [comment]
Well the problem is that i _could_ add null checks to my code, but then you'd only crash elsewhere because said situation is untenable... does it reoccur or was it a one-time affair?
