### ISSUE TITLE
1.11 Update

### ISSUE THREAD

**Issue by adeep** [AtomicStryker/atomicstrykers-minecraft-mods#62]
Will you update to 1.11. Now it says Forge not want to run.
![finder](https://cloud.githubusercontent.com/assets/374042/20449547/bf7b9006-adf2-11e6-9777-4b85489323ff.png)

**Comment by AtomicStryker** [comment]
That is entirely expected. I will definitely update to 1.11 as the changes appear to be less of a pain than usual, however, i will also wait a week or two because they will probably spit out a version 1.11.2 or something anyway. They always do.

**Comment by adeep** [comment]
Thanks, i like to using your mod instead of using quarry. Digging mine is fun :)

**Comment by AtomicStryker** [comment]
For the record, they did release a 1.11.2 like two days after i updated

**Comment by adeep** [comment]
And they broke your mod again :)
