### ISSUE TITLE
Lag progressively gets worse using this mod

### ISSUE THREAD

**Issue by DatrixTHLK** [AtomicStryker/atomicstrykers-minecraft-mods#63]
I noticed that when using your mod for 1.10.2 lag in the game increases until the game becomes unplayable. I know you must be busy and all, but can you fix this? I mentioned this in the curseforge page about 2 months ago and haven't received a response as of yet. I'm a very patient person usually (as well as being forgetful), but I don't think it should take 2 months to respond.

Minecraft 1.10.2
Forge 12.18.2.2151
Dynamic Lights

**Comment by AtomicStryker** [comment]
I won't dedicate a lot of time into maybe possibly reproducing this, if you can use a jvm profiler for more information go for it and I will see if there is something concrete to fix.

**Comment by DatrixTHLK** [comment]
JVM Profiler?

**Comment by DatrixTHLK** [comment]
I have a feeling it'll take more time to figure out than for a response on curseforge, at least for me anyways. *sigh* Oh well, thanks for responding anyway.
