### ISSUE TITLE
Arrow Cam Mod Crash

### ISSUE THREAD

**Issue by APolarBaer** [AtomicStryker/atomicstrykers-minecraft-mods#65]
http://pastebin.com/cD61k934

when firing an arrow holding shift

**Comment by APolarBaer** [comment]
https://github.com/jasonpaulos/ArrowCamMod/issues/2

**Comment by AtomicStryker** [comment]
Thank you, been a long time since i had an actual current-version bug(-report), have https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/8f02da6b95951ecb285222e1b519e84d66798a10 for a fix

**Comment by APolarBaer** [comment]
Thanks Stryker ill check it out when the update gets pushed to curse

**Comment by APolarBaer** [comment]
has this been pushed yet? i cant find it
