### ISSUE TITLE
Dynamic Lights compat for 1.7.10?

### ISSUE THREAD

**Issue by KryptonCaptain** [AtomicStryker/atomicstrykers-minecraft-mods#67]
Would it be possible to add compatibility with Mine&Blade Battlegear's offhand slot, so torches and such can be carried to light things?
Items/torches carried in the BG main hand slot (while equipped) *do* light things around you, but that's not as practical if you want a sword or pick in main hand.

**Comment by AtomicStryker** [comment]
One would have to write a module that monitors that offhand slot. It's not very hard. Since 1.10.2 added an offhand slot (which dynamic lights supports) one could check out how that is done. I don't feel very much like doing this myself, honestly.
