### ISSUE TITLE
Pet Bats [Concept Request]

### ISSUE THREAD

**Issue by seanamor** [AtomicStryker/atomicstrykers-minecraft-mods#68]
Any chance you would be interested in Pet owls? Basically the same exact mod as you have here but with owl sounds/models/Textures, a perching rather than hanging. I also think a p2p delivery of items would be quite nice!

**Comment by AtomicStryker** [comment]
I am merely maintaining my mods, not adding to them :)
As for p2p item delivery, the only way for this to be feasible is for the owl to "disappear" and teleport to the vicinity of the target later, 3d flight pathfinding is fiendishly expensive as soon as any sort of obstruction comes into play.

**Comment by seanamor** [comment]
Understandable if youre no longer making them. The "teleporting of Owls its totally what I forgot to mention, yes... I wouldnt expect the owl to fly to a player in that great of a distance. I basically would love for the bat concept to be replicated for owls, just minus the hanging upside down, and replace the bat sounds/textures with owls. But once again... Understandable if youre not making new mods.
