### ISSUE TITLE
Minions sometimes turn invisible

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#69]
On version 1.11, my minions have a disconcerting tendency to turn invisible overnight.  It's not always all of them, but even with no minion in sight, I can still hear their response when I call them to follow me or assign a task.  I initially realized this when I couldn't place a few blocks (because an invisible minion was in the way).  Exiting and restarting seems to fix the problem.  (ETA:  Well, sometimes.)

ETA:  Forge 2189.

**Comment by AtomicStryker** [comment]
This bug has been around for several versions now and i don't know what causes it.
