### ISSUE TITLE
Minions don't want to go through fencegates and doors.

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#70]
Even when I "charge" the staff with them in sight through an open door and fencegate, they don't come through.  When I broke the door, I finally managed to get some of them to come through the gate.

**Comment by AtomicStryker** [comment]
That's because the block targeting algorithm doesn't understand the concept of non-opaque blocks. You cannot target through gates, fences, glass or anything. You are hitting them.

**Comment by MentalMouse** [comment]
No no, I'm not trying to hit them with the staff, just hold-right-clicking as usual to summon them.  They for their part are hanging out outside the open gate.  Though after I broke the gate, for a while I had two of them blocking each other cow-style.

**Comment by AtomicStryker** [comment]
The pathfinding algorithm may or may not understand the concept of doors either, i dont remember

**Comment by MentalMouse** [comment]
The real irony here is that although they won't open a fence gate, I've occasionally seen them hopping onto and over a fence!  

And they do use that to escape my perimeter:  Whenever I tell them to cut trees inside my base perimeter, one or two of them will go to the trees I point out, the others will go looking for Moar Trees, eventually wandering far away from my base, but when I call them back they return with wood from the trees _outside_ my fence.

**Comment by AtomicStryker** [comment]
That's because the fences are technically pathable (they are only 1 block high), the minions fail to actually climb them, but the pathfinding time out will teleport them over instead. I will put "fences and doors" on my tentative (read: unlikely) todo list.
