### ISSUE TITLE
Minion's animal abduction is glitchy.

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#71]
Version 1.11"

First:  Went and found some chickens.  Each minion picked one up.  Returned to my base.  A visible minion was apparently stuck in a complex tree-base near my house, charge-staff didn't help, nor did cutting a path to my pen.  Grabbed a seed, went over and clicked on the minion to make it drop the chicken.  minion toddled off... leaving the chicken thrashing in midair!  When I punched the chicken, it went pink and stayed pink, so clearly in some frozen state.

In the course of this, I saw the drops of two chickens (that is, feathers and meat) appear in different places, presumably from invisible minions.  The last minion, happily, managed to drop his chicken successfully.

Next day, off to find cows.  Two minions pick up cows.  I returned to my base, to find all 4 minions visible (for a change ;-/), but none of them holding cows.  Sigh....

**Comment by AtomicStryker** [comment]
I am seriously considering to just kill and respawn Minions every minute to fix this annoying invisibility issue.

**Comment by MentalMouse** [comment]
I'm not sure that would actually help.  Since my report on that, I've found them invisible on startup (where they had been present on save), and had them vanish right in front of me.  Oh yeah, it's annoying.  

Maybe you could try some intensive debugging, say watching what's happening to their model and any relevant flags.  I don't have MCP source access myself, but some ideas from Back When I used to be a programmer:
  
1) read through whatever MC routine is responsible for "painting" mobs, looking for places where it might give up on the display due to an error.  Then put conditional breakpoints/tracepoints there.  
2) For the flip side,  use tracepoints to verify that the routine keeps getting called to display your minions, and/or that whatever value is necessary for it to do so remains valid.

One or the other approach is likely to yield a hint.  If the bug has persisted through several versions of Minecraft, odds are good that the origin of the problem is in your code, it's just a matter of convincing the debugger to reveal where it is.

**Comment by AtomicStryker** [comment]
If you have a save of a Minions world where they reliably turn invisible upon load, i'd love to have it. Debugging is very time intensive. I don't have much time to invest and don't want to, either.

**Comment by MentalMouse** [comment]
I'll see what I can do, might be a while.  Happily, I just got AromaBackup installed.
