### ISSUE TITLE
No mcmod.info file for most of your mods, no mod version for most of them

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#72]
The mcmod.info file is wanted by the mod browser, and having a mod version in the filename will really help when (if?) you fix bugs and/or add features.

**Comment by ktole1999** [comment]
i think this is one of those annoyances that will never get fixed on any mod. it is what it is.

**Comment by AtomicStryker** [comment]
That would require me to keep seperate links for versions, and i am too lazy. If you absolutely must have older versions, just grab them off one of the pirateer sites or the github.io repository history.
