### ISSUE TITLE
Feature Request: "Minions stay here".

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#73]
Especially with the new entity collisions and their tendency to turn invisible, the minions can be quite in the way sometimes.  And especially once Fortune comes into play there will be times we just want to leave them at home.

The M menu would be a good place for this (along with, perhaps, "teleport to me").

**Comment by AtomicStryker** [comment]
If you order them to a spot (right click on ground from above) they will stay there. If you give them an order close to you and they are really far away, they ... will teleport if they find they can't walk the distance ... but they will try to walk the distance. You can always unsummon them using M and re-summon them.

**Comment by MentalMouse** [comment]
In fact, they do not seem to stay near the point I chose, but instead go wandering around.

**Comment by AtomicStryker** [comment]
Yes they will loiter, but only with 6 or so blocks of the spot you indicated

**Comment by MentalMouse** [comment]
This is not what I'm seeing.  After arriving at the spot, they disperse over the landscape, not even staying within 16 blocks of the original target.  ETA2:  And jumping over fences at whim.

ETA:  On the other hand, they do stop following and teleporting after me.

**Comment by AtomicStryker** [comment]
It's a bit surprising because the algorithm only looks for a "target spot" in a radius. However, it doesn't check how long the way to that target spot is. It might be half a mile. The minion will try to walk it.
