### ISSUE TITLE
DynamicLights doesn't seem to be working in 1.11

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#74]
At least, wielding a torch does not light my way.

**Comment by AtomicStryker** [comment]
Works for me.

**Comment by MentalMouse** [comment]
Not for me.  Second world too -- switching to and from a wielded torch next to a wall or dark area shows no difference.  I'm finding 1.11 is a lot darker in general, almost like Hardcore Darkness -- that may be connected.  At this point, I don't think I'm using any other mods that ought to be affecting lighting, and I encounter the darker environment even in a straight vanilla 1.11 game.

My modlist:

> 1.10-chunkedgeindicator-1.3.jar
> [1.11]UncraftingTable-1.7.jar
> AbyssalCraft-1.11-1.9.3.9.jar
> ArmorDamageRecalc-1.11.x.jar
> Aroma1997Core-1.11-1.2.0.0.b79.jar
> AromaBackup-1.11-2.1.0.0.b64.jar
> BattleTowers-1.11.jar
> Baubles-1.11-1.4.0.jar
> BedBugs-1.11-1.1.3.jar
> BiomesOPlenty-1.11-6.0.1.2128-universal.jar
> Cavern_1.11-v1.6.2.jar
> compatlayer-1.11-0.1.4.jar
> DynamicLights-1.11.zip
> forge-1.11-13.19.1.2199-installer.jar.log
> FriendlyFire-1.11-1.4.0.jar
> GiacomosFishingNet1.10.2-1.4.5.jar
> GraveStone Mod 1.6.2.jar
> gud_deathshot-1.0.jar
> HowBoutThatFurniture-1.1.3.jar
> IvToolkit-1.3.jar
> jei_1.11-4.1.0.205.jar
> journeymap-1.11-5.3.2.jar
> LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar
> mdecore-1.11-0.2.jar
> Minions-1.11.jar
> multistorage-1.11.0-1.3.1.jar
> mysticalagriculture[1.11]-1.3.6.jar
> OpenEye-1.11-0.8.jar
> PackingTape-1.11.0-0.6.1.jar
> parachutemod-ng-1.11-1.6.0-418.jar
> PassthroughSigns-1.11-2.1.1.jar
> PetBat-1.11.jar
> RecurrentComplex-1.2.5.1.jar
> reptilemod-1.11-3.6.0-60.jar
> resources
> RoguelikeDungeons-1.11-1.6.1.jar
> Ruins-1.11.jar
> shetiphiancore-1.11.0-3.4.1.jar
> simplemagnet-1.11.0-1.2.3.jar
> SimpleTeleporters-1.11-2.0.1.jar
> slimer-1.2.jar
> TimeHUD-Forge-1.11-7.1.0.jar
> UpdateCheckerMod-1.11.jar
> Waddles-1.11-0.5.1.jar
> Waystones_1.11-3.0.5.jar
> WIT-1.11-1.0.22-41.jar

**Comment by AtomicStryker** [comment]
Put your client logfile up somewhere (pastebin or such)

**Comment by MentalMouse** [comment]
[Here you go](https://pastebin.com/v57x1PYC).

**Comment by AtomicStryker** [comment]
DynamicLights-1.11.zip
You need to extract that

**Comment by MentalMouse** [comment]
D'Oh!   I know I had it installed correctly at some point, because I have the config files; but I was pulling mods in and out for a while, and must have muffed one of the transitions.  And now carrying a torch does indeed work!  (I'm oddly pleased that Light-Level Overlay responds to this correctly.)
