### ISSUE TITLE
Minions don't put stuff in chests

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#75]
So, the various sites say you're supposed to be able to set a chest as target, and indeed I get a minion response when right-clicking the staff on a chest from a distance.  However, they don't put anything in there, and instead give me their loads in person as usual.  This last time, though , they were digging a mineshaft, surface to level 9, and they had no ores for me at all, not even "in person".

**Comment by AtomicStryker** [comment]
Without version information i can't even tell you "works for me"

**Comment by MentalMouse** [comment]
Version 1.11.  Forge 2189 and 2199 both showed the behavior.
