### ISSUE TITLE
Multi-Mine not functioning in MC 1.11.2

### ISSUE THREAD

**Issue by Zarepheth** [AtomicStryker/atomicstrykers-minecraft-mods#77]
As the title says, multi-mine functionality does not seem to work in MC 1.11.2 with a load of mods installed.
Any interruption while mining a block resets the blocks progress back to zero - just like vanilla MC.

I didn't see any Multi-Mine specific errors or warnings in the Log file - though looking it over did point out a couple 1.10.2 mods that have not been upgraded to 1.11.2.

[fml-client-latest.log.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/691957/fml-client-latest.log.txt)

Let me know if you need some further testing to narrow down the problem.

**Comment by AtomicStryker** [comment]
Unless you mean "use the version they were made for" as further testing, no, i think i know where the problem is. I will update my stuff to 1.11.2, don't you worry.

**Comment by Zarepheth** [comment]
Thank you for the upgrade! MultiMine for 1.11.2 is now working fine.

**Comment by AtomicStryker** [comment]
Glad to hear it.
