### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by seanamor** [AtomicStryker/atomicstrykers-minecraft-mods#78]
I know you're simply maintaining, but would you consider adding the bat sound events into the mod vs having it called from the Minecraft vanilla resource?  1.10.2

**Comment by AtomicStryker** [comment]
What is a bat sound event? I don't know what that is

**Comment by seanamor** [comment]
I mean rather than the mod use the bat sounds from vanilla minecraft, it will use custom bat sounds from the mods resources.

**Comment by AtomicStryker** [comment]
Oh you want me to copy the vanilla bat sounds and redistribute them with the mod so you can replace them, but not the default bat sounds? I'm pretty sure that would violate copyright

**Comment by seanamor** [comment]
If I provide you with royalty free sound files would you consider it?

**Comment by AtomicStryker** [comment]
Sure why not

**Comment by seanamor** [comment]
Thanks! Here you go! https://drive.google.com/file/d/0B4JNb1UGLZ68ZEJNTkVEcHIwSVk/view?usp=sharing

**Comment by AtomicStryker** [comment]
See https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/70fa46401600152ab8cecca73fce2e6b7fe06cef and https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/bdc0ff7fa573337e19234765cf083c4879f47424, i have pushed the downloadable files too. And thank you for the files.

**Comment by seanamor** [comment]
Would I need to compile this myself for 1.10.2, or do you have link, thanks! This is great to see!

**Comment by AtomicStryker** [comment]
I have pushed the downloadable files. You can grab them from my github.io repo, from my website, or tomorrow from curse
