### ISSUE TITLE
Suggestions for Ruins:

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#80]
A synthetic "village" biome, to add buildings to villages.  Try to avoid creating villager deathtraps (doored but incomplete buildings).

A command to locate the nearest ruin, and say whether you are currently _in_ a ruin.  If there is one, please document it, I just looked and didn't see anything.

ETA:  Go ahead and special-case the End as well as the "Village" biome (and the Nether), to only get biome-specific ruins, not biome-generic ones.

**Comment by AtomicStryker** [comment]
That is not how villages (and other mc structures) work. Basically the game tries to find a spot, similar to how Ruins works, then "unfolds" the structure from a central spot using premade puzzle pieces. Yes i kinda copied it for the "adjacent" Ruins tech. But what i'm saying is that Ruins does not offer "attachments" to this or a "biome". You could create your own Ruins-powered village using adjacent rules.

The commands are possible, but no, they dont exist yet. I'm putting them on my wishlist.

End is a biome, isnt it?

**Comment by MentalMouse** [comment]
> End is a biome, isnt it?

Well yes, it's the Sky biome.  Which is why it ought to be trivial to _not_ put generic ruins in the End.  Something End-specific, sure -- odd structures of End materials, or even buildings from prior explorers (not necessarily dragon-safe, even), but _not_ the same stables, farms, and orespikes you've been seeing all over the Overworld.

**Comment by AtomicStryker** [comment]
It is trivial, just go through the generic ruins and add the end_stone or whatever it is called to the disallowed blocks

**Comment by MentalMouse** [comment]
OK then, I'll modify that suggestion to exclude end_stone.  It's just silly to go to the end and see all the familiar ruins somehow littering that exotic dimension..

**Comment by AtomicStryker** [comment]
I agree the default Ruin set needs work. Constant maintenance, even. And i freely admit i can't or won't do that as much as needed. Don't have the time.
