### ISSUE TITLE
Pet Bats 1.10.2 

### ISSUE THREAD

**Issue by seanamor** [AtomicStryker/atomicstrykers-minecraft-mods#81]
https://hastebin.com/mininizafe.vbs

17.01 08:51:48 [Server] INFO Minecraft Forge: 12.18.3.2202
17.01 08:51:48 [Server] INFO SpongeForge: 1.10.2-2202-5.1.0-BETA-2020
17.01 08:51:48 [Server] INFO SpongeAPI: 5.1.0-SNAPSHOT-e221622
17.01 08:51:48 [Server] INFO Minecraft: 1.10.2

**Comment by AtomicStryker** [comment]
Thanks, hopefully fixed in https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/04d9f699b288f17b228aae775e9e93fdb74a2c8f

Re-download from my site, my github.io or later from curse and check again
