### ISSUE TITLE
error with iveria mod

### ISSUE THREAD

**Issue by EnderStar** [AtomicStryker/atomicstrykers-minecraft-mods#82]
Hi, the iveria mod changes some blocks that arent next to air for the same blocks but that take 10 times more to break with any tool exept diamond, with multimine installed those blocks take he same time to break as normal stone blocks
Thanks!
Edit: im using latest version 1.10.2

**Comment by AtomicStryker** [comment]
I suggest just putting that kind of blocks on the blacklist
