### ISSUE TITLE
WTF's Expedition Dense Ores

### ISSUE THREAD

**Issue by Myth494** [AtomicStryker/atomicstrykers-minecraft-mods#86]
With WTF's Expedition mod, while using multimine dense ores break fully on first break. One dense ore should supply multiple ores (as in mine the same block --changes state to less dense-- and supplying the ore as well)

**Comment by AtomicStryker** [comment]
Blocks that break in non-vanilla ways usually aren't supported. You need to add them to the multi mine exclusion list.
