### ISSUE TITLE
Minions don't have textures, crash game (1.11.2)

### ISSUE THREAD

**Issue by MentalMouse** [AtomicStryker/atomicstrykers-minecraft-mods#87]
In my newest game, the minions are appearing with black-and-purple skins, and the game is regularly crashing on them.  This seems to be the version from January 9th, 2016, on Forge 2224 (MC 1.11.2).

Crash report:  https://www.dropbox.com/s/hik3pkzgy35epty/hs_err_pid23440.log?dl=0

**Comment by AtomicStryker** [comment]
Thats not a crash report, thats a segfault, apparently in the garbage collector. I will have to check my Minions with the current Forge, they did work for the version i ported them to (2206)

**Comment by MentalMouse** [comment]
Also happens in Forge 2228.

**Comment by AtomicStryker** [comment]
For the record, the problem is a miscapitalized texture under assets/minions/textures/model/AS_EntityMinion-png  which should be as_entityminion.png.

As for your GC crash, i didn't get it (in my 2 minutes of testing) and as far i could there there was no heinous memory leak either.
