### ISSUE TITLE
[1.11.2] Infernal Mobs crash

### ISSUE THREAD

**Issue by ThomasAunvik** [AtomicStryker/atomicstrykers-minecraft-mods#90]
Well, i am having crashes when i go to my base. I do not know what is wrong

Infernal Mobs: Latest?

[Crash Log](http://pastebin.com/BSANJ5hD)
The crash that happened just before this crash:
https://github.com/gigabit101/QuantumStorage/issues/69

**Comment by AtomicStryker** [comment]
Crashing code is in HammerCore_1.11.2-1.4.3.jar
Go report this there
