### ISSUE TITLE
[1.11.2][Ruins]Hyphenated block

### ISSUE THREAD

**Issue by drakray** [AtomicStryker/atomicstrykers-minecraft-mods#91]
As discussed [here](https://github.com/Chisel-Team/Chisel/issues/220), if a ruin have a block with a Hyphen/Dash in its name, it error in [latest.log](https://pastebin.com/cSkr8jBN)
[Obelisk_Sandstone.tml](https://pastebin.com/Mn4zn0qj) rule6

**Comment by drakray** [comment]
Trying to parseruin an Obelisk with scribble in it [log](https://pastebin.com/SC0Uv5Q2)

**Comment by AtomicStryker** [comment]
Yes. Hyphen/Dash is a reserved character as far as Ruins is concerned, using it in a blockname is not supported behaviour.

**Comment by AtomicStryker** [comment]
This used to be minecraft behaviour too, however they fixed it at some point in time

**Comment by drakray** [comment]
could it be fixed by using colon/other symbol instead of hyphen to split meta/rotation?

**Comment by AtomicStryker** [comment]
Sure, it would only mean breaking most Ruins templates. To support something that has literally never come up in all these years. I'll see if i can hack something together that catches this special case without invalidating the scheme.

**Comment by drakray** [comment]
maybe use a config file for special blockname?

**Comment by AtomicStryker** [comment]
That might be a working but dumb solution. I'll try something cute first.

Aaaand done. Download the current zip from my github.io project and check if the issue is fixed.
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/a308a192e10f57da5bd0b2e3fa8329363d8b09d2

**Comment by drakray** [comment]
Seems to work nicely :D
