### ISSUE TITLE
Taking damage in MP server

### ISSUE THREAD

**Issue by routinet** [AtomicStryker/atomicstrykers-minecraft-mods#92]
Just installed a new MC 1.11.2 server on Ubuntu.  Flying is turned on in server.properties, and the mod works normally when I play in my SP worlds.  When playing on the MP server, though, I take damage whenever I land.  The damage seems to track with my highest altitude minus landing altitude.

**Comment by AtomicStryker** [comment]
I assume you are talking about Simply Hax? Well, all it does is tell a client "yes this is creative mode you can totally fly". If the server imposes fall damage on it's lonesome i dont think a client-only mod can change that.

**Comment by routinet** [comment]
Yes, Simply Hax.  I am unfamiliar with Minecraft modding, so I'm not sure where the line is between server and client.  Your point sounds reasonable...do you know how I can configure the server to not inflict damage on landing, in the case of flying?

[This thread](http://www.minecraftforge.net/forum/topic/4225-taking-fall-damage-on-landing/) has some suggestions for how to cancel damage.  Is that applicable to this problem?

**Comment by AtomicStryker** [comment]
It's not that i don't know how to fix it, i do. The solution would be to run Simply Hax as a server and clientside mod both. But that's against the idea of Simply Hax. I could make an optional serverside similar to how Finder Compass works but i am too busy currently to do any new development. Or do much of anything really.

**Comment by routinet** [comment]
Do you have any suggestions on how to address this while keep the client-side approach?  It seems to work just fine in single player..

**Comment by AtomicStryker** [comment]
Not using Simply Hax, unfortunately. You need some mod that has a serverside component to avoid the issue.
