### ISSUE TITLE
Infernal Mobs: Pigmen that have infernal attritbutes affect you even while they are not aggressive towards you.

### ISSUE THREAD

**Issue by oneandonlyflexo** [AtomicStryker/atomicstrykers-minecraft-mods#93]
Not sure if this is intended or not, but infernal pigmen will hit you with their random effects while walking around in the nether ignoring you (e.g. cobwebs, knockback).

I feel like this should either check if the mob is aggressive towards the target, or infernal pigmen are always aggressive towards everyone.

**Comment by AtomicStryker** [comment]
Infernal Mobs uses the LivingSetAttackTargetEvent provided by Forge to catch mob attack targets. Mojang code apparently does this even if no actual attacking is going on.

I'll just go with "intended" ... compare with Diablo 3 Molten or Fire Chains modifiers. Even if you are invisible or something those still hurt you. So my modifiers still do their shenanigans.

**Comment by oneandonlyflexo** [comment]
Fair enough. Can't really complain too much about infernal mobs being a pain the ass.
