### ISSUE TITLE
Crash when trying to destroy Little Tiles tile

### ISSUE THREAD

**Issue by Videonauth** [AtomicStryker/atomicstrykers-minecraft-mods#94]
[crash-2017-04-07_23.06.49-client.txt](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/906878/crash-2017-04-07_23.06.49-client.txt)

Just hit this crash as I tried to destroy a tile I created with Little Tiles.

**Comment by AtomicStryker** [comment]
Thank you, fixed in https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/172b896bd5ffd8609c17bb302d19f003a09eca23

**Comment by Videonauth** [comment]
Wow, that was a quick fix! Thank you very much.
