### ISSUE TITLE
[1.11.2] [Infernal Mobs] Storm attribute continues to be applied when set to False

### ISSUE THREAD

**Issue by Rosethorns** [AtomicStryker/atomicstrykers-minecraft-mods#95]
Mobs appear to be continuing to spawn with the Storm attribute when it has been correctly set to false in the config.

Reproduce:
1. set B:"MM_Storm enabled"=false
2. find infernal that still has lightning strikes

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2260
InfernalMobs: 1.7.2

**Comment by AtomicStryker** [comment]
Attributes are only read from the "enabled" pool when a mob first spawns. However, a previously spawned mob that was saved in the world file can still have modifiers you disabled since.

**Comment by Rosethorns** [comment]
These were new spawns.

**Comment by AtomicStryker** [comment]
I've looked at the source and i have to amend above statement. The config actually does affect previously saved mobs and can strip modifiers off them. Check your console / log files for the line "InfernalMobsCore load() completed! Modifiers ready: " and compare the number printed there to the number you have enabled in your config. If they do not match, try deleting the config and letting it regenerate.

**Comment by Rosethorns** [comment]
Thanks Atomic,
Will check and get back to you :)
