### ISSUE TITLE
Petbat Console Spam

### ISSUE THREAD

**Issue by Scratchman** [AtomicStryker/atomicstrykers-minecraft-mods#96]
When a player drops something from their inventory, there is console spam, lots of it, for every object that's dropped.

[Server thread/INFO] [STDOUT/]: [atomicstryker.petbat.common.PetBatMod:onItemToss:303]: onItemTossEvent hooked, isRemote: false
[Server thread/INFO] [STDOUT/]: [atomicstryker.petbat.common.PetBatMod:onItemToss:307]: PlayerDropsEvent iterating over drop EntityItem['item.enderio.itemPowerConduitEnder'/64800, l='world', x=-2964.14, y=72.32, z=-368.52]

**Comment by AtomicStryker** [comment]
Must have forgotten to remove that. Thank you for reminding https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/da44250b7a424ac2f882964e7ef446bc5969362e

**Comment by Scratchman** [comment]
I guess I should have said this is in petbats for 1.10..2

**Comment by AtomicStryker** [comment]
Yes. Yes you should have. But i'm in a giving mood https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/691b1c47c79afdd7235190b6c4c87acc4330d5d9

**Comment by Scratchman** [comment]
\o/ .. Thanks
