### ISSUE TITLE
Just constructive information (Some mob enhancements are ridiculous)

### ISSUE THREAD

**Issue by Videonauth** [AtomicStryker/atomicstrykers-minecraft-mods#97]
Just had to face a 'Bulwark Sticky Ender Re-Gen Ninja Skeleton' with 160+ life. Just to say its not killable without referring to console commands. So some enhancements should maybe not go in conjunction with others by default.

Don't mind facing hard mobs as long I can somehow kill them without referring to the console.  :)

**Comment by AtomicStryker** [comment]
There is actually a system in place to prevent certain combinations, but i never really fleshed it out.
